### ISSUE TITLE
invalid URLs are reported as 505 HTTP Version Not Supported

### ISSUE THREAD

**Issue by agenteo** [tsenart/vegeta#106]
I had a few malformed URLs containing markup left from a crawling an HTML page. This is definitely user mistake but vegeta was reporting those as 505 (505 HTTP Version Not Supported
The server does not support the HTTP protocol version used in the request.)

What do you think about flag and ignore invalid URLs?

Example URL causing problem:

```
GET valid_url" class="accordion-toggle-sub"
```

**Comment by tsenart** [comment]
@agenteo: Did you manage to reproduce the bug?
