### ISSUE TITLE
Report plot with status code detail

### ISSUE THREAD

**Issue by davideicardi** [tsenart/vegeta#108]
Do you think it is possible to plot a report where each status code is drawed in its own line?
For example let's say that I execute 200 request, 50 requests have HTTP 200, 150 have HTTP 500. I think it should be useful to have different lines in the output.

regards
Davide Icardi

**Comment by tsenart** [comment]
This was a bug. Thanks for finding it and reporting! https://github.com/tsenart/vegeta/releases/tag/v5.5.1

**Comment by davideicardi** [comment]
Thanks very much for your prompt response and fix!

Unfortunately I think that there is one more little problem: often pages that return 500 also return complex HTML error pages. For example:

- https://github.com/projectkudu/kudu/asd
- http://www.thomas-bayer.com/sqlrest/cxz/zx

Other times the page is empty:

- https://www.youtube.com/feed/history/asd

With your last commit you write the body of the page as the error, correct me if I'm wrong. But this can a problem because it is a waste of memory, the message is a complex HTML difficult to read or worst an empty message that potentially can cause the page to be considered OK by the reporter.

My suggestion is to just put the HTTP status or description like "HTTP error 500".

What do you think?

I will be happy to submit a pull request but I never written a line with golang...

thanks!
Davide

**Comment by tsenart** [comment]
That was indeed an oversight. Thanks for your diligence. https://github.com/tsenart/vegeta/releases/tag/v5.5.2

**Comment by davideicardi** [comment]
Perfect! Thank you!
