### ISSUE TITLE
Crawling mode

### ISSUE THREAD

**Issue by pengux** [tsenart/vegeta#112]
When load testing websites, you usually wants to simulate real web browsers. It would be great if vegeta could do this by parsing the HTML DOM and make requests against assets (JS, CSS, images etc.) just like a real browser would do. Eventually, maybe vegeta can follow links to other URLs randomly and automatically. This can be in cycles (configurable) to simulate the time a user stays on a page before leaving (so new requests hits landing page and start crawling from there again)

**Comment by tsenart** [comment]
Hello @pengux,

I completely understand your use case. However, Vegeta was built to load test HTTP exposed services in a SOA, not web sites directly. This is explicitly a non-goal of this project.

**Comment by pengux** [comment]
Thanks for the response. Then I'll fork this into a new project.
