### ISSUE TITLE
If chunked encoding is used, vegeta reports 0 bytes transferred

### ISSUE THREAD

**Issue by pwaller** [tsenart/vegeta#113]
I just instrumented Vegeta [here](https://github.com/tsenart/vegeta/blob/670b8caab6c833181cae772c293664017d035bf1/lib/attack.go#L207) and discovered that my ContentLength is set to -1.

Vegeta is reporting 0 BytesOut, and I would really like to know the size. Could vegeta measure it by doing an `io.Copy(ioutil.Discard, req.Body)`, or would that have a negative performance impact?

**Comment by tsenart** [comment]
Given that the response body can be of arbitrary size, even with chunked encoding, reading it (even if just to discard it) would indeed have a potentially negative performance impact.

**Comment by pwaller** [comment]
I'm wondering a couple of things here. 

1) It seems you should have to read the whole body anyway to accurately gauge the performance of your setup.

2) [Does go already copy to `ioutil.Discard`](https://github.com/golang/go/blob/b2843becab6f4571be1c117da870393198edf01f/src/net/http/transfer.go#L703)?

**Comment by pwaller** [comment]
Hm, WRT (2) I guess not since that only applies if you're reading trailer headers.

So, uh, what about (1)? Isn't the experiment a bit invalid if we don't actually read the body? I mean, sure, it tests the performance of GET calls, but if we're not actually moving bytes through the entire network stack, I don't see how my results will be a realistic representation of what the system will achieve under load.

**Comment by tsenart** [comment]
I was previously under wrong assumptions and you are right about this. With chunked encoding, an HTTP server sends the response headers right away and then streams the body chunks which can be lazily generated. Without chunked encoding, network transfer time of the body wasn't previously being accounted for. I'll have a patch ready for you to review in a bit. Thanks for digging into this!
