### ISSUE TITLE
Attack time grows unexpectedly while latency is low

### ISSUE THREAD

**Issue by vdel26** [tsenart/vegeta#120]
I am running some tests with Vegeta and, while at lower rates everything was going fine, I am hitting something weird when increasing the rate. The duration of the test is increasing a lot, but latencies are still relatively low.
See the results below for example for a 20 second test that eventually took nearly 2 minutes:

```
echo "GET http://api-server/path" | vegeta attack -rate=6000 -duration=20s -timeout=5s | tee results.bin | vegeta report
Requests	[total]				120000
Duration	[total, attack, wait]		1m57.971208919s, 1m57.922599203s, 48.609716ms
Latencies	[mean, 50, 95, 99, max]		28.419263ms, 39.337944ms, 43.668078ms, 206.692678ms, 206.692678ms
Bytes In	[total, mean]			6940836, 57.84
Bytes Out	[total, mean]			0, 0.00
Success		[ratio]				100.00%
Status Codes	[code:count]			200:120000
Error Set:
```

Btw, Vegeta is running in a 4 core machine and none of the cores goes beyond 50% utilization throughout the test.

Any advice or insight into what might be happening here will be welcomed!

**Comment by tsenart** [comment]
Hello @vdel26,

Thanks for reporting. Would you please provide me with the intermediate results for me to debug your case? You can obtain them by redirecting `vegeta attack` to a file.

**Comment by tsenart** [comment]
Oh, I see you did this. Could you send me your `results.bin`?

**Comment by vdel26** [comment]
Here is my results.bin file: https://transfer.sh/Ts2se/results.bin
Thanks for your help!

**Comment by tsenart** [comment]
@vdel26: You're welcome. What were the attack parameters for the results.bin file you sent me?

**Comment by vdel26** [comment]
They were these:
```
vegeta attack -rate=8000 -duration=20s -timeout=5s
```

**Comment by tsenart** [comment]
@vdel26: Which version of vegeta are you running? On which OS? 64 or 32 bits?

**Comment by vdel26** [comment]
The OS is Ubuntu 14.04.2 LTS, 64 bits. More info below:

```
$ vegeta -version
v5.6.2

$ uname -a
Linux ip-172-30-0-218 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tsenart** [comment]
I'm working on a bunch of performance improvements which will allow a single instance of vegeta to drive higher rates.

**Comment by vdel26** [comment]
Sounds great :) I'll be looking forward to try that when it is ready.

**Comment by tsenart** [comment]
@vdel26: https://github.com/tsenart/vegeta/releases/tag/v5.6.3

**Comment by vdel26** [comment]
@tsenart :+1: the changes work great, I was able to reach much higher rates than before on the same server.

I am not sure I understand the purpose of the new **connections** option? Is it to set an upper limit to avoid reaching the max number of open sockets?

Thanks again for the super quick turnaround on this issue.

**Comment by tsenart** [comment]
The `-connections` flag defines how many open idle connections can exist per target host. When using HTTP keepalive, TCP connections are reused. However, due to the high throughput that Vegeta can generate, one connection isn't enough and more are created. We don't want to tear down idle connections before the end of the test because that would create large latency spikes if they're needed again, reducing the effective rate of the attack.
