### ISSUE TITLE
Distributed test

### ISSUE THREAD

**Issue by janisz** [tsenart/vegeta#122]
Does Vegeta supports distributed tests? If I run it on multiple machines and grab results into one place and generate report from them then reports will be properly generated?

I'm trying to create [Mesos framework](http://mesos.apache.org/documentation/latest/mesos-frameworks/) for distributed performance tests and search for best tool for that stuff.

**Comment by tsenart** [comment]
Absolutely! Vegeta has load generation and reporting decoupled. Look here
for inspiration:
https://github.com/tsenart/vegeta/wiki/Distributed-Attack

Since that page was written, the dump command has been implemented which
can make it easier for you to integrate with.

Let me know if I can help in any way!

On Thursday, April 16, 2015, janisz <notifications@github.com> wrote:

> Does Vegeta supports distributed tests? If I run it on multiple machines
> and grab results into one place and generate report from them then reports
> will be properly generated?
>
> I'm trying to create Mesos framework
> <http://mesos.apache.org/documentation/latest/mesos-frameworks/> for
> distributed performance tests and search for best tool for that stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsenart/vegeta/issues/122>.
>


-- 
Sent from Gmail Mobile

**Comment by tsenart** [comment]
You can integrate with the command line tool or with the Go library.

On Thursday, April 16, 2015, Tomás Senart <tsenart@gmail.com> wrote:

> Absolutely! Vegeta has load generation and reporting decoupled. Look here
> for inspiration:
> https://github.com/tsenart/vegeta/wiki/Distributed-Attack
>
> Since that page was written, the dump command has been implemented which
> can make it easier for you to integrate with.
>
> Let me know if I can help in any way!
>
> On Thursday, April 16, 2015, janisz <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Does Vegeta supports distributed tests? If I run it on multiple machines
>> and grab results into one place and generate report from them then reports
>> will be properly generated?
>>
>> I'm trying to create Mesos framework
>> <http://mesos.apache.org/documentation/latest/mesos-frameworks/> for
>> distributed performance tests and search for best tool for that stuff.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tsenart/vegeta/issues/122>.
>>
>
>
> --
> Sent from Gmail Mobile
>


-- 
Sent from Gmail Mobile

**Comment by janisz** [comment]
Great! That's what I've been searching for. I think you should add link to readme. It's really useful. I didn't expect that it could be described in wiki (even that wiki exists).

**Comment by tsenart** [comment]
https://github.com/tsenart/vegeta/issues/123
