### ISSUE TITLE
Case Sensitive headers

### ISSUE THREAD

**Issue by hi-t-ch** [tsenart/vegeta#124]
Hi there.
A quick issue that I've encountered today using vegeta binary (v5.6.3 amd64). Considering the following target file:

![image](https://cloud.githubusercontent.com/assets/5638840/7571146/dba0b8b8-f815-11e4-8ad4-0b4e0ffab9f2.png)

If you proxy the requests sent by vegeta, you got something like this (Headers are sorted and Capitalized) :
![image](https://cloud.githubusercontent.com/assets/5638840/7571217/5b33bf26-f816-11e4-86d2-35750c1850cc.png)
 
I know that RFC 2616 specifies that headers should be case-insensitive, but the REST application that I'm testing is sensitive.
I understand that http.header's function add and set canonicalize headers, but is there any quick hack to make vegeta respect cases?
Thanks !

**Comment by tsenart** [comment]
I'm sorry but adding a hack to vegeta to support non-standard HTTP behaviour doesn't make sense. Also, the code that needs patching isn't in vegeta itself but in the Go standard library.

**Comment by GeertJohan** [comment]
I had this same problem once when working with a case-sensitive API (third party software). I agree that this is non-standard HTTP behaviour, but making it work wouldn't hurt vegeta and only increase it's use cases. The solution is extremely simple: http://stackoverflow.com/questions/26351716/how-to-keep-key-case-sensitive-in-request-header-using-golang

**Comment by GeertJohan** [comment]
It looks like only one line needs to be changed to omit the canonicalization by Go's net/http and apply the headers with their original casing: https://github.com/tsenart/vegeta/blob/80e72220d6d9e2803004a9f47f04a8e870debe52/attack.go#L189

**Comment by tsenart** [comment]
@GeertJohan: Thanks for digging further! OK, it seems that given how easy it is, it's worth doing it. Would you be interested in providing a patch with tests for this?

**Comment by GeertJohan** [comment]
Sure I'll be able to do that, but gotta go now so it'll probably be later this week if thats okay.
