### ISSUE TITLE
Quantiles are incorrectly calculated

### ISSUE THREAD

**Issue by alexeyrodriguez** [tsenart/vegeta#129]
In some executions of vegeta the metrics command generates incorrect quantiles, namely the value of the 99th quantile is the same as max, which is wrong. I double checked by dumping the results file into a CSV and calculating the quantiles using R. I'll be happy to provide the offending binary file (I see no way to attach it here).

**Comment by tsenart** [comment]
Vegeta is using github.com/bmizerany/perks/quantile for quantile calculation. As paraphrased below, this library trades accuracy for guaranteed low memory and CPU bounds over unbounded data streams.

Now, it might be worth to re-evaluate if we need those properties since the percentiles are computed in batch, not over a stream as they once were supposed to be.

What would your advice be on the matter? Thanks for reporting this. :-)

```go
// Package quantile computes approximate quantiles over an unbounded data
// stream within low memory and CPU bounds.
//
// A small amount of accuracy is traded to achieve the above properties.
//
// Multiple streams can be merged before calling Query to generate a single set
// of results. This is meaningful when the streams represent the same type of
// data. See Merge and Samples.
//
// For more detailed information about the algorithm used, see:
//
// Effective Computation of Biased Quantiles over Data Streams
//
// http://www.cs.rutgers.edu/~muthu/bquant.pdf
```

**Comment by alexeyrodriguez** [comment]
Hi Tom, thanks for writing Vegeta and nice meeting you at lunch yesterday :).

Using approximations makes sense indeed. However, the approximation errors should be within some bounds for "metrics" to be usable (I had to use R to complete my tests). It would seem to me that the perks implementation might have a bug. One could try a different implementation of the same paper (for example https://github.com/streadway/quantile) and see whether it is also wrong (or maybe we discover that the underlying algorithm is a bad approximation in some cases). I'd be happy to supply my test file if it is useful.

**Comment by tsenart** [comment]
@alexeyrodriguez: Would you be able to verify if PR #130 gives you equivalent results to R's 8th type of quantile estimation?
