### ISSUE TITLE
Documentation of -reporter=plot doesn't explain what it is

### ISSUE THREAD

**Issue by pwaller** [tsenart/vegeta#131]
Hello again @tsenart !

I just started playing with this:

https://github.com/tsenart/vegeta#plot

But it is very unclear what it is, or how to read it. The documentation (linked above) explains that it's made with dygraphs and how to zoom it, which is cool and all, but maybe isn't the main thing I need to know about if I'm considering using it.

Features of the graph which are surprising:

* There are very fine grained points in time. Is each point a request? Or are they synthesised somehow?
* The graph exhibits a kind of decay. Is that a feature of my application, or of how vegeta is reporting this "latency"?
* What does the Y axis "latency" mean? The latency of the most recently completed request at that point in time? I just have to guess.

**Comment by tsenart** [comment]
Hello @pwaller!

Thanks for bringing this up. I hadn't noticed the documentation for this reporter was lacking at this level.
Answering your questions:
> There are very fine grained points in time. Is each point a request? Or are they synthesised somehow?

`vegeta attack` outputs the result of every single performed hit / request. `vegeta report` consumes such output to generate the reports. The `plot` reporter is no different and each point in the graph is a real data point. This makes it a performance bottleneck for the browser to parse and render very large data sets. This is something to improve by compressing the results with minimal loss of information.

> The graph exhibits a kind of decay. Is that a feature of my application, or of how vegeta is reporting this "latency"?

I couldn't tell without looking at the graph. But vegeta doesn't manipulate the results in anyway besides using a logarithmic scale to represent the data. This allows result sets with very large standard deviation to be understandable.

> What does the Y axis "latency" mean? The latency of the most recently completed request at that point in time? I just have to guess.

Each data point (X, Y) represents the latency of a request performed at a certain time. Hence X = request timestamp and Y = request latency

**Comment by pwaller** [comment]
Can you elaborate on `request timestamp`? Is it the beginning or end of the request. Or TTFB, or? I assume it must be the end of the request.

**Comment by tsenart** [comment]
Request timestamp marks the beginning of a request.
