### ISSUE TITLE
Report processing runs out of memory with large report file.

### ISSUE THREAD

**Issue by ohookins** [tsenart/vegeta#132]
Report file was 1.5GB, physical memory on this instance is about 7GB. Anything I can do to successfully process this report?

**Comment by tsenart** [comment]
Hi Oliver,

The reporters are currently implemented to process in batch. That explains your OOM. Which reporter were you using? What were the parameters to the attack stage?

**Comment by ohookins** [comment]
I used the default parameters to report, so I guess `text`.
On the attack it was this: `cat list_of_targets | vegeta attack -duration=24h -lazy=true -rate=200 > results.bin`
The list of targets was a file with 13.5 million URLs.

**Comment by tsenart** [comment]
Wow. That's some impressive scale, my friend :-) What's the use case for a 24h load test? I'm very curious!

**Comment by ohookins** [comment]
Actually I'm just looking to hit the servers with all of the requests in the input file to pre-warm some caches. The 24h period and request rate should be enough to cover all of the target URLs in the file, which is the only reason behind those settings - ideally I'd ask the test tool to just cycle sequentially through the targets until complete, but that's not an option.

**Comment by tsenart** [comment]
@ohookins: From your explanation, you're not actually looking to use vegeta's reports, only the load generation with `attack`. In any case, I'm working on making the reporters work with in streaming, but won't be able to finish it too soon. However, I got something that should work for you to process that data set with report. Would you mind building the branch https://github.com/tsenart/vegeta/tree/streaming-reporters and running:
```console
$ cat results.bin | ./vegeta report -window=24h
```

Let me know if it worked.

**Comment by ohookins** [comment]
Yes, that did work.

Actually I do need to use the reports, since I need to tell what level of success the load test had. For example I didn't set high enough ulimit and I think that led to a bunch of problems resolving DNS and creating new sockets. It's also still useful to see if there were any significant performance problems during these kinds of tests to judge whether it has been successful or just hitting something which doesn't perform any computation.

**Comment by tsenart** [comment]
OK, makes sense. Remember though, that you can also use the dump command in combination with jq to analyse the raw results. For your case, something like this would work:
```console
$ cat results.bin | vegeta dump | jq '.error'
```

**Comment by ohookins** [comment]
:cool:
