### ISSUE TITLE
Bad Method: DELETE

### ISSUE THREAD

**Issue by shriiitk** [tsenart/vegeta#134]
Got this error when trying to load my server with DELETE requests:
**xxx$** vegeta attack -header=Content-Type:application/json -body=deletebody.json -targets=delete-targets.txt -duration=5s | tee results.bin | vegeta report
_2015/09/03 21:21:11 bad method: DELETE_
Requests	[total, rate]			0, 0.00
Duration	[total, attack, wait]		0, 0, 0
Latencies	[mean, 50, 95, 99, max]		0, 0, 0, 0, 0
Bytes In	[total, mean]			0, 0.00
Bytes Out	[total, mean]			0, 0.00
Success		[ratio]				0.00%
Status Codes	[code:count]			
Error Set:
**xxx$** cat delete-targets.txt
DELETE http://localhost:8080/cache/api/v1/buckets/responses/bulk
**xxx$** vegeta -version
5.8.0

As per readme, target file can contain something like this:
DELETE http://goku:9090/path/to/remove
but this is not working. Can you please let me know why DELETE request support is revoked?

Also does it create some logs in which I can look and see why some particular error(s) are happening?

**Comment by tsenart** [comment]
Thanks for reporting!

**Comment by shriiitk** [comment]
When will this be available as pre compiled linux binary and in Homebrew package?

**Comment by tsenart** [comment]
https://github.com/tsenart/vegeta/releases/tag/v5.8.1

**Comment by tsenart** [comment]
Homebrew will be updated soonish with a new release that will include new features.
