### ISSUE TITLE
multipart/form-data as body

### ISSUE THREAD

**Issue by deyvsh** [tsenart/vegeta#135]
Hi,

Hopefully I'm not doing something extremely n00bful... I'm trying to use a lump of multipart/form-data with some JSON and an image as the body (included with @filename) but something's going wrong and I'm getting a 400 back -- any reason this shouldn't work?

Many thanks,
Dave

targets.txt:
```
POST https:/blah.com/still
Host: blah.com
Content-Type: multipart/form-data; boundary=Boundary+0xAbCdEfGbOuNdArY
@still-bits2.req
```

still-bits2.req:
```
--Boundary+0xAbCdEfGbOuNdArY
Content-Disposition: form-data; name="data"

{
  "status" : "live",
  "uid" : "329475.1",
  "time" : "1441380329.607740",
  "mode" : "stills",
  "session_id" : 1441380329,
  "version" : "1.1.0",
  "token" : "tokenytoken",
  "type" : "StillImage"
}
--Boundary+0xAbCdEfGbOuNdArY
Content-Disposition: form-data; name="file"; filename="file.jpg"
Content-Type: image/jpeg

LOADS OF JPEG BLAH
--Boundary+0xAbCdEfGbOuNdArY--
```

**Comment by tsenart** [comment]
Perhaps looking at the server logs would hint about why the requests are being rejected.

**Comment by deyvsh** [comment]
Working through that, but thought it was probably worth checking I wasn't trying to do something you knew to be unsupported. I'm not getting Bad Request on the equivalent curl call.

**Comment by deyvsh** [comment]
OK, narrowed down to a server issue. Working nicely. Thanks for the polite response :)

**Comment by tsenart** [comment]
Great! :-)

**Comment by alkaphreak** [comment]
> OK, narrowed down to a server issue. Working nicely. Thanks for the polite response :)

@deyvsh, i would be interrested by your solution :)

**Comment by deyvsh** [comment]
@alkaphreak I can't remember, sorry!

For the avoidance of doubt, it was nothing to do with vegeta. Either I was constructing the request wrongly (perhaps I was using LFs instead of CRLFs for line endings? That's a classic!) or it was some detail of the server implementation where curl and vegeta appeared to be doing something subtly different (e.g. I think curl sends `Expect: 100-continue`). Either way, I probably identified the difference by capturing the raw request in Wireshark or dumping it on the server.

Good luck!
