### ISSUE TITLE
Headers not set on redirect

### ISSUE THREAD

**Issue by damjankuznar** [tsenart/vegeta#151]
If a 301 redirect is received, Vegeta fails to set headers (at least Authorization header) on a subsequent request. See output from Wireshark bellow:
```
GET /user HTTP/1.1
Host: example.com
User-Agent: Go-http-client/1.1
Authorization: Token e1b844e7491da2b57382008a507191809e5af5e4
Accept-Encoding: gzip

HTTP/1.1 301 MOVED PERMANENTLY
Server: nginx/1.4.6 (Ubuntu)
Date: Fri, 16 Oct 2015 06:11:17 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Location: http://example.com/user/

0

GET /user/ HTTP/1.1
Host: example.com
User-Agent: Go-http-client/1.1
Referer: http://example.com/user
Accept-Encoding: gzip

HTTP/1.1 401 UNAUTHORIZED
Server: nginx/1.4.6 (Ubuntu)
Date: Fri, 16 Oct 2015 06:11:17 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN
WWW-Authenticate: Token
Allow: GET, HEAD, OPTIONS

{"detail":"Authentication credentials were not provided."}
```

I'm using Vegeta that was compiled from source using instruction on the main Vegeta github page:
```
$ go get github.com/tsenart/vegeta
$ go install github.com/tsenart/vegeta
$ ./vegeta -version
???
```

**Comment by tsenart** [comment]
We've been bitten by this issue: https://github.com/golang/go/issues/4800

**Comment by tsenart** [comment]
As described in the linked issue, it's not obvious how to handle certain sensitive headers on a redirect. Wouldn't it be possible for you direct your attack at the final location instead?

**Comment by damjankuznar** [comment]
Yes, I did fix it by changing the URL, but I thought this is unwanted
behaviour. Reading the related issue I understand that it is a more complex
problem. As far as I'm concerned you can close the issue.
