### ISSUE TITLE
Support pre-target report ?

### ISSUE THREAD

**Issue by wcp1231** [tsenart/vegeta#158]
Hi

I love this project and I wonder if it will support pre-target report?

thrank

**Comment by tsenart** [comment]
Sorry, what does that mean?

**Comment by wcp1231** [comment]
eh.. sorry for my poor english and typo.
I mean `per-taget`

when I attack a tagets list:
```
GET http://localhost:3000/post/1
POST http://localhost:3000/post/1/like
```
I can get report like this:
```
Summary
Requests      [total, rate]             1200, 120.00
Duration      [total, attack, wait]     10.094965987s, 9.949883921s, 145.082066ms
Latencies     [mean, 50, 95, 99, max]   113.172398ms, 108.272568ms, 140.18235ms, 247.771566ms, 264.815246ms
Bytes In      [total, mean]             3714690, 3095.57
Bytes Out     [total, mean]             0, 0.00
Success       [ratio]                   55.42%
Status Codes  [code:count]              0:535  200:665

GET http://localhost:3000/post/1
Requests      [total, rate]             1200, 120.00
Duration      [total, attack, wait]     10.094965987s, 9.949883921s, 145.082066ms
Latencies     [mean, 50, 95, 99, max]   113.172398ms, 108.272568ms, 140.18235ms, 247.771566ms, 264.815246ms

POST http://localhost:3000/post/1/like
Requests      [total, rate]             1200, 120.00
Duration      [total, attack, wait]     10.094965987s, 9.949883921s, 145.082066ms
Latencies     [mean, 50, 95, 99, max]   113.172398ms, 108.272568ms, 140.18235ms, 247.771566ms, 264.815246ms
```

**Comment by tsenart** [comment]
No. For that, you perform one attack per endpoint, separately.

**Comment by wcp1231** [comment]
> No. For that, you perform one attack per endpoint, separately.

I put the list of targets as something like load generation tool, and want to konw which is slowest in list.

Did I misuse? What is the purpose for the list of targets?

**Comment by tsenart** [comment]
The purpose of the list of targets is for an attack to a single endpoint to be parameterised over a wide range of inputs.
```
GET /users/1
GET /users/2
GET /users/3
...
```

To achieve what you want to achieve, you should perform individual attacks with similar parameters to each endpoint (target) and then compare the results.

**Comment by wcp1231** [comment]
Ok, I will find another way... Thank~
