### ISSUE TITLE
Realtime feedback?

### ISSUE THREAD

**Issue by sage-oli-wood** [tsenart/vegeta#159]
Is it possible at the moment (or as a future feature) to get realtime feedback whilst Vegeta is running?  I'm running tests over multiple hours and being able to get a rough idea of the count of status codes returned or average times would be tremendous.

NB: a genuinely brilliant project - helping me no end.

**Comment by aidylewis** [comment]
Hi @tsenart 

I know you are reticent of adding new features, but I also see realtime feedback as important. I was thinking of response time percentiles, current RPS and error rate printed to stdout every x number of seconds. If we could also format these metrics as Graphite data, we could push this data to InfluxDB and visualise them through Chronograf.

**Comment by sage-oli-wood** [comment]
I'll experiment with piping the results binaries into another instance of vegeta later today and shout back if that's doable or not.

**Comment by sage-oli-wood** [comment]
This works fine.  In another session cat the output and pipe into "vegeta report" and you get running stats.  Shouldn't be that hard to ask for them as JSON and then pipe into Statsd/whatever

**Comment by tsenart** [comment]
@sage-oli-wood: Glad you found your way around. @aidylewis: You can use `vegeta dump` for your use case I think.

**Comment by aidylewis** [comment]
yes, that's a good idea by @sage-oli-wood.

shell_1
```sh
echo "GET https://www.google.co.uk/" | vegeta attack -duration=2m -rate=2 | tee results.bin | vegeta report
```

shell_2
```sh
while true; do cat results.bin | vegeta report ; sleep 2; done
```

Thanks

**Comment by aidylewis** [comment]
And of course the dumper works as well. This tool is extremely well designed.
