### ISSUE TITLE
latency computation off if "low rate, high speed"

### ISSUE THREAD

**Issue by client9** [tsenart/vegeta#164]
Hello and thanks for a great project.

The server being tested is expected to respond in a few milliseconds.  The latency computations at a low rate seem to be off since they seem to include some time waiting for the "tick" to happen.  This causes the server to appear to improve performance as load goes up (if only this were true!).

```
Rate - followed by mean/50/95/99/max
1- 4.448309ms, 4.029548ms, 6.519311ms, 6.519311ms, 6.573537ms
2  - 4.430776ms, 4.435549ms, 6.573555ms, 6.573555ms, 6.82999ms
4 - 4.975884ms, 5.598255ms, 6.516992ms, 6.564416ms, 6.663549ms
8 - 4.734556ms, 4.630934ms, 6.60105ms, 6.621163ms, 6.809839ms
16 - 4.808476ms, 5.485431ms, 6.522268ms, 6.638545ms, 7.933011ms
32 - 4.484903ms, 4.745573ms, 6.503815ms, 6.591089ms, 9.119002ms
64 - 3.931232ms, 4.397094ms, 4.97487ms, 5.916436ms, 8.16732ms
128 - 2.680071ms, 2.835058ms, 3.256831ms, 4.773234ms, 10.610524ms
256 - 1.938694ms, 1.96593ms, 2.19879ms, 4.416436ms, 13.78734ms
```

changes `hit` to use the current time instead of the passed in time

```diff
 func (a *Attacker) hit(tr Targeter, tm time.Time) *Result {
+       tm = time.Now()
        var (
```

produces better results.  Due to my hack testing, the higher loads produce better performance, but that is likely due to very few requests at the low-rate, and various approximations.

That said I'm a bit surprised that even at 256 RPS, the difference was noticeable between the two (orig 1.9ms vs. new 1.15)

(1 RPS had  only 10 requests, while 256 had 2560)

```
1 -1.473785ms, 1.332038ms, 1.568132ms, 1.568132ms, 2.653567ms
2 - 1.332685ms, 1.241887ms, 1.823347ms, 1.823347ms, 2.525506ms
64 - 1.200786ms, 1.12479ms, 1.3951ms, 3.601153ms, 5.328444ms
256- 1.154427ms, 1.07069ms, 1.254707ms, 3.684137ms, 13.999406ms
```

thoughts?  and thanks again for a great project.

n

**Comment by client9** [comment]
Oh sorry, I just saw the contributing file...

## What version of the project are you using?

latest from github as of 2015-12-14.

## What operating system and processor architecture are you using?

for this test I'm on  Mac OS X  `Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015`, although I suspect it will be the same on Linux as well.

## What did you do?

Using API, but mostly copying exactly what is in attack.go in root dir.

I varied the RPS rate while keeping the duration fixed (this isn't great.. ideally same number of requests, and vary duration would be better for statistics)

## What did you expect to see?

RPS of 1 to have less latency than RPS of 256.  Normally I would expect this server to run about 1.5ms 

## What did you see instead?

Server latency decreased as load went up.  1 RPS was 4 or 5 ms, while RPS 256 it was ~ 2ms.

thx again

**Comment by tsenart** [comment]
Hey there! Sorry for not looking into this for a while. I hope to be able to dig into it before the end of the year. Busy times!

**Comment by tsenart** [comment]
In any case, it'd be good to try to make a reproducible test case of this. Perhaps record your attack results so that we can analyse them in different ways.

**Comment by tsenart** [comment]
Any news?
