### ISSUE TITLE
When http response header Content-Length: -1,  io.Copy cause error:Expected EOF

### ISSUE THREAD

**Issue by wangming1993** [tsenart/vegeta#166]
When I had a attack with  reponse header: 
```
Content-Type: -1
```
Will cause error: ***Expected EOF***
 in: **lib/attack.go**   function **hit**  io.Copy,   line **235**

**Comment by tsenart** [comment]
Contributions welcome!

**Comment by tsenart** [comment]
Can't reproduce. If you can provide a reproducible test case, please do! Closing for now.
