### ISSUE TITLE
Collect response bodies and headers

### ISSUE THREAD

**Issue by Loofort** [tsenart/vegeta#168]
It seems to me that Vegeta collects and groups response only by HTTP response code.
I propose to add feature to extract and collect custom headers, (even body parts with help of  regex).
I understand It's a lot of work ( and sorry if it doesn't correspond to the spirit of the project.)

**Comment by tsenart** [comment]
What's the use case?

**Comment by Loofort** [comment]
1) under high load various artefacts could appears in response (especially if race condition take place), sript could extract and check some text with expected one.
2) some of the API implementations always return http 200 but and provide error messages in body or in custom http headers.

this is just first what come to mind.
I'm shure there is could be many more cases like:
check if load balancing works properly- collect and group node num avilable in response. etc.

**Comment by aidylewis** [comment]
Yes. I've seen that one before. A 200 response, but an error message in the body. But is that not a SUT design flaw?

**Comment by Loofort** [comment]
>  But is that not a SUT design flaw?

this is the question for another holywar topic. 
anyway sometimes you just have to deal with what you've been asked.

**Comment by tsenart** [comment]
This is out of scope of a load testing tool.

**Comment by machulav** [comment]
We have two use cases where we also need to analyze the response body:
- GraphQL load testing - GraphQL always responds with HTTP 200. In case of an error, it also returns HTTP 200 and the error messages in the body.
- We also have a case when we need to test the race condition under a high load; in this case, we have to analyze the response. It seems like a similar use case that @Loofort brought up.

Can you please reconsider and open the issue?

**Comment by tsenart** [comment]
@machulav: This has been implemented since. Just pipe `vegeta attack` to `vegeta encode` and you'll see the response body and headers.
