### ISSUE TITLE
Vegeta closes all programs and crashes Macbook

### ISSUE THREAD

**Issue by mholt** [tsenart/vegeta#169]
What version of the project are you using?

6.0.0

What operating system and processor architecture are you using?

Macbook Pro (64 bit, Mac OS 10.11.3)

What did you do?

```
echo "GET http://localhost:8080/test.html" | vegeta attack -duration=10s -rate=100000 | tee results.bin | vegeta report
```

What did you expect to see?

The test results

What did you see instead?

All my programs quit then my computer froze (iTunes started looping the same ~100ms of audio) and then it finally restarted.

Perhaps there could be a rate limit to prevent this from happening.

**Comment by tsenart** [comment]
Hello Matt,

One hundred thousand requests per second seems a bit too much for your
MacBook to service. For local tests on normal hardware I'd recommend a more
reasonable rate.

**Comment by mholt** [comment]
Wrk can crank them out, unless I'm misunderstanding something about wrk's results.

**Comment by tsenart** [comment]
Wrk seems to be doing a fine job at benchmarking your local test server.
What are you trying to do with Vegeta?

**Comment by mholt** [comment]
Same thing I guess. I'm following up a conversation in Slack where people were mentioning vegeta in combination with wrk and ab and other tools. Thought I'd give it a go, but am unable to make the server break under any load vegeta can attack with (i.e. all 200 status codes). Maybe I'm doing it wrong?

**Comment by tsenart** [comment]
Vegeta isn't a benchmarking tool like wrk is. It's a load testing tool.
Instead of answering the question "What's the maximum capacity my system
can service", it answers "How does my system behave at X req/s"?

**Comment by mholt** [comment]
Ah. I was not aware of that distinction. I'll mention that back in Slack. Thanks!
