### ISSUE TITLE
what's the limit of request rate of this tool? thanks!

### ISSUE THREAD

**Issue by junneyang** [tsenart/vegeta#172]

**Comment by tsenart** [comment]
That entirely depends on the hardware and OS configuration you run it on :-)

**Comment by aidylewis** [comment]
I ran 30,000 RPS on a c3.2xlarge against a Go web server provided by @tsenart: https://github.com/bbc/notes-on-perf-testing/blob/master/ch/vegeta.md#examples 

I might have increased the max open file limit:
https://github.com/bbc/notes-on-perf-testing/blob/master/ch/tuning/open_file_limit.md

Not very scientific, I know, I didn't investigate it much more. I thought this was enough and distribution using pdsh is easy to set-up,
