### ISSUE TITLE
Redirects with redirects parameter set to -1 are not counted correctly

### ISSUE THREAD

**Issue by homar** [tsenart/vegeta#173]
Redirects with redirects parameter set to -1 are not counted correctly.

when I do query like: 
echo "GET http://localhost:8080/clicks?emission_unit_id=blablabla&redirect=http://pageTo.redirect" | ./vegeta attack -rate=1 -duration=5s -redirects -1 > target/result-1-5s.bin

I got results like:
Success       [ratio]                  0.00%
Status Codes  [code:count]             0:5 

When I chang -redirects to 1:
echo "GET http://localhost:8080/clicks?emission_unit_id=blablabla&redirect=http://pageTo.redirect" | ./vegeta attack -rate=1 -duration=5s -redirects -1 > target/result-1-5s.bin

result looks like =:
Success       [ratio]                  0.00%
Status Codes  [code:count]             200:5 

which proves that server response correctly.

**Comment by tsenart** [comment]
Hi @homar. Would you mind filling in an issue with our new templates? That'd help. Thank you.
https://github.com/tsenart/vegeta/issues/new/choose
