### ISSUE TITLE
Get over 9000 stars + forks!!

### ISSUE THREAD

**Issue by suizman** [tsenart/vegeta#175]
Make the project more popular and get "over 9000!" stars + forks :smile:

**Comment by alrik11es** [comment]
This is a MUST HAVE

**Comment by pyros2097** [comment]
Its not yet over 9000 so shouldn't the description be like its over 6000. Haha.

**Comment by daluu** [comment]
Well, I see it went over 6k now.

And for this issue thread, maybe get to 9k likes of the original post as well?

I would think it would also be quite interesting and an achievement if we can get over 9k forks, PRs, or watches of the project, not just stars. Alluding to DBZ, if we're forking, you have a fighting competition with others to continually improve, and PRs are others helping you to improve. Stars (and watchers) are just your fanbase, not how good you are.

**Comment by suizman** [comment]
@daluu I've changed the issue name. From now I'll count stars + forks until we can reach a total of 9000

**Comment by tsenart** [comment]
We're almost there!

**Comment by pyros2097** [comment]
Well atleast its.
![1znrw8](https://user-images.githubusercontent.com/1687946/42360086-19c925ec-8104-11e8-9ea1-4584d3cc7872.jpg)

**Comment by mikematthews** [comment]
I think we're there.

**Comment by tsenart** [comment]
Stretch goal: 9k stars without counting forks :-)

**Comment by suizman** [comment]
@tsenart Seems legit :smiling_imp:

**Comment by tsenart** [comment]
Nearly there....

**Comment by NavyAdmiral** [comment]
🌟 🌟 🌟
🌟  30  🌟 left
 🌟 🌟 🌟

**Comment by pyros2097** [comment]
star2 star2 star2 26  star2 left  star2 star2 star2

**Comment by NavyAdmiral** [comment]
<h1 align="center"><img src="https://user-images.githubusercontent.com/40662484/45461959-c092c900-b6d3-11e8-9987-3bbbc8264c69.png"/></br>IT'S  O V E R    9000!!!</h1>
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by daluu** [comment]
So close issue? Or what's next target/goal? I'd like to see 9k forks!

**Comment by tsenart** [comment]
We made it. Thanks everyone for the enthusiasm and support :-)

**Comment by tsenart** [comment]
This arrived today...

![dnsr3wlw0aimjyw](https://user-images.githubusercontent.com/67471/45635261-d1ad5280-baa4-11e8-8d78-2cf118b32769.jpg)

**Comment by xla** [comment]
@tsenart Congratz!!!

**Comment by caarlos0** [comment]
Congratzz!
