### ISSUE TITLE
Feature request: Supporting SNI

### ISSUE THREAD

**Issue by sumikawa** [tsenart/vegeta#178]
To benchmark https site which only accessible with SNI extension, I want to specify servername otherwise TLS handshake will failure from server side.

Reference:
https://golang.org/pkg/crypto/tls/#ClientHelloInfo

```
        // ServerName indicates the name of the server requested by the client
        // in order to support virtual hosting. ServerName is only set if the
        // client is using SNI (see
        // http://tools.ietf.org/html/rfc4366#section-3.1).
        ServerName string
```

**Comment by tsenart** [comment]
Yes, this is doable.

**Comment by chrismoos** [comment]
@sumikawa How do you know SNI is not working? Using the below command I can verify the `server_name` is properly set in the `Client Hello` packet with `go version go1.7.3 darwin/amd64`:

```
echo "GET https://www.yahoo.com/" | vegeta attack -duration=1s | tee results.bin | vegeta report
```
