### ISSUE TITLE
bad target: http:// what is it and why?

### ISSUE THREAD

**Issue by denisbetsi** [tsenart/vegeta#184]
When I run the following comman
`echo "http://localhost:9001/config/base/" | vegeta attack -rate=1000 -duration 5s | vegeta report`

The error I get is 
`2016/05/20 12:57:46 bad target: http://localhost:9001/config/base/`

When I run
`curl http://localhost:9001/config/base/`

I get 
`curl "http://localhost:9001/config/base"
{"videos":{"lastupdate":1463198400000,"list":{ ...`

Bad Target isn't documented and searching google it appears somehow I am the only one that encountered this issue. What is the issue and what am I doing wrong?

**Comment by tsenart** [comment]
You're missing the HTTP method before the target URL. I suppose you want
GET.

**Comment by denisbetsi** [comment]
Yes, I just realized. That was quick! Thank you
