### ISSUE TITLE
Feature request: Better plot output for multiple attacks

### ISSUE THREAD

**Issue by balazswmann** [tsenart/vegeta#188]
Sometimes it would be nice to display multiple attacks on each other rather than beside each other. An illustration below:

![attacks](https://cloud.githubusercontent.com/assets/1757012/15632167/f1a15af8-2589-11e6-85ef-ff91226ccbe1.png)

To achieve the above output, I merged the output of 4 different request rates (100, 200, 250, 300) with a common ground sampling. More specifically I "converted" higher request rates (200, 250, 300) to the lowest one (100) so each one can be displayed at once. This can be achieved with less frequent sampling at higher request rates (e.g. using only every second data in case of request rate 200). In this way some data will be lost (won't be displayed), but the result is much more compact and transparent.

Another question is how errors should be displayed. Maybe another plot could be used where the result would be displayed in the same way as I described above.

**Comment by tsenart** [comment]
You already plot multiple results in a single graph, but they'll be sequential by time.

```shell
vegeta report -inputs="results.100.bin,results.200.bin,results.250.bin,results.300.bin" -reporter=plot > plot.html
```

Would this be good enough for your use case?

**Comment by balazswmann** [comment]
I noticed that option, but it is hard to see differences between the results due to the sequential order.

**Comment by raunakb94** [comment]
@balazswmann is there a way to use this enhancement. 
May be by forking a particular branch?
I actually needed the same thing to compare different qps request by transposing them onto one another.

**Comment by tsenart** [comment]
Fixed by https://github.com/tsenart/vegeta/commit/eb9b3637e10fe4b7706cd2c628e83616030a6087

**Comment by tsenart** [comment]
Actually, just noticed I should have bumped the major version. Re-releasing...

**Comment by tsenart** [comment]
https://github.com/tsenart/vegeta/releases/tag/v8.0.0

**Comment by MetalBlueberry** [comment]
Can you provide a simple example of how the command will be?
Maybe I'm a bit sleepy but I can't get it to work
the example above is not working for me

`vegeta report -inputs="results.100.bin,results.200.bin,results.250.bin,results.300.bin" -reporter=plot > plot.html`

I've just installed vegeta with go get and vegeta --version outputs
```
Version: 
Commit: 
Runtime: go1.10.4 linux/amd64
Date:
```

thanks!

**Comment by tsenart** [comment]
This has change meanwhile as indicated by the output of `vegeta plot -h`.

Try this: `vegeta plot results.*.bin > plot.html`

**Comment by MetalBlueberry** [comment]
Thanks tsenart
Looks like you also need to take into account #333 or you will get an error.

**Comment by tsenart** [comment]
Have you run into that error with the latest version? If so, please file a new bug report.

Sent via Superhuman iOS ( https://sprh.mn/?vip=tsenart@gmail.com )
