### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by rakor1986** [tsenart/vegeta#189]
when i install use "go get github.com/tsenart/vegeta",throw error：
package golang.org/x/net/http2: unrecognized import path "golang.org/x/net/http2" (https fetch: Get https://golang.org/x/net/http2?go-get=1: dial tcp 216.58.203.17:443: i/o timeout)

**Comment by tsenart** [comment]
Seems like you were having connectivity issues. Maybe try again? Otherwise
just download a pre-compiled release.
