### ISSUE TITLE
Vegeta modifies header values

### ISSUE THREAD

**Issue by shevanid** [tsenart/vegeta#191]
I am using vegeta to load test, and the use case is to POST request with headers. I pass "X_MESSAGE_ID" but it is received at server as "X_message_id"

I understand that underscores are not used in headers as per RFC 822, but in my case I have to use them. Is there a flag to avoid this transformation ?

**Comment by tsenart** [comment]
This is a bug. It's been reported and fixed previously in https://github.com/tsenart/vegeta/issues/124, but apparently we missed the headers set via target definition (as opposed to the ones set via the `-header` flag in the attack command).
