### ISSUE TITLE
Reporter not displaying which endpoint is causing errors

### ISSUE THREAD

**Issue by uchagani** [tsenart/vegeta#194]
I have a targets file with 3 endpoints.  One of them is causing a 404 but the reporter is not displaying which endpoint it is.  It is displaying that the error set has a 404.  Here's the output:

```
Requests      [total, rate]            500, 50.10
Duration      [total, attack, wait]    9.982790925s, 9.979999893s, 2.791032ms
Latencies     [mean, 50, 95, 99, max]  2.878237ms, 2.866436ms, 3.424179ms, 3.902979ms, 22.258044ms
Bytes In      [total, mean]            3262594, 6525.19
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  66.60%
Status Codes  [code:count]             404:167  200:333
Error Set:
404 Not Found
```

The above is an output from the following ```attack``` command:

```vegeta attack -targets=perf.target -duration=10s > results.bin```

**Comment by tsenart** [comment]
Attacking heterogenous targets in one attack can't yield statistically sound metrics whatsoever. All you can do in this manner is to use Vegeta as a simple load generator and gather metrics through your own monitoring systems.

In sum, the right way to use Vegeta is to attack a single endpoint at once.
