### ISSUE TITLE
Use with Proxy.

### ISSUE THREAD

**Issue by dpc** [tsenart/vegeta#196]
I want to "attack" a proxy. In Go I'm able to easily do such thing by changing `http.Transport` in `http.Client`, but `vegeat` binary does not expose anything like that. 

Will a PR for such feature be accepted if I manage to hack it myself?

**Comment by tsenart** [comment]
Would you please elaborate? A proxy will be listening on some port. What's missing in Vegeta for you to be able to attack it?

**Comment by dpc** [comment]
In the example:

```
  echo "GET http://localhost/" | vegeta attack -duration=5s | tee results.bin | vegeta report
```

The  http://localhost/ is both the url to fetch, and place to connect. I want these two to be separate. I want to fetch `http://google.com/` but connect to eg. `localhost:8080`. Is there a way to do it already?

**Comment by tsenart** [comment]
You can set the `$HTTP_PROXY` environment variable indicating the address of your proxy server.

Try this:

```
export HTTP_PROXY="http://localhost:8080/"
echo "GET http://google.com" | vegeta attack -duration=5s | tee results.bin | vegeta report
```

**Comment by tsenart** [comment]
@dpc: Did you manage to run Vegeta through a proxy?

**Comment by dpc** [comment]
Yes. It works perfectly for me. Thank you.

**Comment by seanalexander** [comment]
When your address is HTTPS, use HTTPS_PROXY

```
export HTTPS_PROXY="http://localhost:8080/"
```
