### ISSUE TITLE
Support a dynamic body for each request

### ISSUE THREAD

**Issue by alephnull** [tsenart/vegeta#199]
We have an app that has just one endpoint and there is a nonce (`TransactionId` below) that needs to be set differently for each request. I tried the following:

```
payload["TransactionId"] = uuid.NewV4().String()
body, err :=  json.Marshal(payload)
util.Check(err)
t := vegeta.NewLazyTargeter(r, body, nil)
for res := range attacker.Attack(t, util.Config.Rate, time.Duration(util.Config.Duration)*time.Second) {
		metrics.Add(res)
}
```

But this sends the same body (as expected). Do you have any thoughts?

**Comment by tsenart** [comment]
Have a look at this blog post: https://thisdata.com/blog/load-testing-api-interfaces-with-go-and-vegeta/

In sum, you can generate the input targets for vegeta attack with your own program and pipe that out.
