### ISSUE TITLE
Running a list of URLs in a loop?

### ISSUE THREAD

**Issue by mrichman** [tsenart/vegeta#200]
Is it possible to have multiple workers, each executing a list of URLs in succession? This is opposed to having multiple workers, each executing a URL in the list in parallel.

i.e.

http://server:port/url1
http://server:port/url2
http://server:port/url3
...
http://server:port/urlN

**Comment by tsenart** [comment]
What's the use case? I suppose the easy way would be to set `-rate=1` but that'd be issuing one request per target per second, wrapping around the targets reaching EOF. I'm not sure that's what you want.

**Comment by mrichman** [comment]
Use case is basically a repeated web test, where the test is a sequence of URLs that a user might GET/POST to in order.

Similar to what Visual Studio's web test does:

![image](https://cloud.githubusercontent.com/assets/11228/19091248/cfea61d6-8a4f-11e6-9f95-f12842772a8f.png)

**Comment by tsenart** [comment]
Vegetal was built for load testing and it doesn't seem like the right tool for your job. I don't know the specifics of what you mean by "web test" because I don't use Visual Studio. What is being tested exactly?

**Comment by mrichman** [comment]
In its simplest form, which is what I need, all it is doing is executing it ordered series of URLs looking for an expected result.

**Comment by tsenart** [comment]
OK, then Vegeta definitely isn't what you're looking for, which can easily be done with a simple shell script that checks the status codes of the responses.

**Comment by mrichman** [comment]
A shell script isn't going to run through the set of URLs in a goroutine, and have N of those goroutines run concurrently.

**Comment by tsenart** [comment]
> (...) This is opposed to having multiple workers, each executing a URL in the list in parallel.

Vegeta hits the given targets with a fixed defined request rate, distributing load to them with a round-robin policy.

What you want is for it to issue a single request to each of those targets once and sequentially, right?

What part of the output of Vegeta are you going to be using to assert success?

**Comment by mrichman** [comment]
Sequentially, yes, but not just once. I want to run the sequence in loop, and have each of those loops running concurrently.

As far as asserting success, I'm not sure. 

I don't know if Vegeta (or parts of it) can help me, so that's why I ask.

I will likely end up rolling my own solution since we seem to be approaching the problem with different goals.
