### ISSUE TITLE
Proposal: Use the `net/http/httptrace` package

### ISSUE THREAD

**Issue by jcorral** [tsenart/vegeta#201]
Would you consider a PR that uses the golang 1.7 httptrace package to retrieve request metrics?

No changes on the current features just on the implementation.

I also asked myself if the idea of fine-grained information about the lifecycle of the requests (as an option), won't break the tool's simplicity.

**Comment by tsenart** [comment]
Can you elaborate on the proposal? How would the end result of using that package look like?

**Comment by tsenart** [comment]
@jcorral: Ping?

**Comment by jcorral** [comment]
sorry for the delay, busy days prior to dotGO.

The idea that i had on mind was to create a customized `Transport` struct pretty much like the second example with the title [Tracing with http.Client](https://blog.golang.org/http-tracing) on the original Golang blog, the tracking the Roundtrip time would be there instead of the `hit` func, but the `Latency` would be still copied on the hit func.

Personally i'm not totally happy with that approach as the `Transport` gets reused, but  i'm not yet proficiency enough with your lib to get a better one.

I think that i would do it just for hacking so feel free to close this issue as a PR would come, but any concern that you may have will be welcome.

**Comment by tsenart** [comment]
@jcorral: Find if there's a tangible and obvious benefit in leveraging this new package and come back to me with your proposal :-)
