### ISSUE TITLE
Using Vegeta for writing to an EventStore stream

### ISSUE THREAD

**Issue by jg8481it** [tsenart/vegeta#203]
Hi,

I just started using Vegeta and I am not sure how to proceed with applying it to a POST for a Single Event for EventStore. 

EventStore Single Event is documented here...
http://docs.geteventstore.com/http-api/3.0.3/writing-to-a-stream/

The Single Event headers that EventStore requires look like this...

> -H "Content-Type:application/json" -H "ES-EventType: SomeEvent" -H "ES-EventId: C322E299-CB73-4B47-97C5-5054F920746E"

From what I can understand from the documentation (I may be wrong but not sure), it requires a unique non-duplicate "ES-EventId:" UUID for every single one. I am not sure how to proceed with using Vegeta on this. My goal is to run a test that will demonstrate and visualize to my client that EventStore can handle a Vegeta rate of at least 500 per second. I appreciate any advice on how to approach this...

Thank you

**Comment by tsenart** [comment]
Have a look at this blog post: https://thisdata.com/blog/load-testing-api-interfaces-with-go-and-vegeta/

**Comment by jg8481it** [comment]
Thank you. I will give that a try.

**Comment by marceloboeira** [comment]
it seems the blogpost link is not valid anymore...
