### ISSUE TITLE
Is there a way to correlate attack hits to results?

### ISSUE THREAD

**Issue by andreasmaier** [tsenart/vegeta#205]
I am currently running vegeta against one endpoint and would retroactively like to understand why some of the requests failed. As the url is the same for all of the requests and they only differ in the request body, I'm having a hard time figuring out which ones failed from reading the dump.

Is there any identifying element where I can correlate a result to an attack hit?

**Comment by tsenart** [comment]
Errors should be visible in the text report. For finer grained analysis I'd recommend monitoring your server logs for errors.
