### ISSUE TITLE
[Feature Request] support configurable 'baseUri' for targets

### ISSUE THREAD

**Issue by missedone** [tsenart/vegeta#206]
hi @tsenart 

let's take a sample targets file below:
```
GET http://user:password@goku:9090/path/to
X-Account-ID: 8675309

DELETE http://goku:9090/path/to/remove
Confirmation-Token: 90215
Authorization: Token DEADBEEF
```

we need to specify the full url in it.

in our case, we have several test environments, but I'd like to reuse the targets file, for now I have to find-replace the hostname before target to new tests env. or have multi copy but that gets out-of-sync between the targets file.

so could we introduce a new switch for example named `baseTargetUri`, in the above sample, `-baseTargetUri=http://goku:9090`
and the targets file can be simplified as env independent:
```
GET /path/to
BasicAuthentication: user:password
X-Account-ID: 8675309

DELETE /path/to/remove
Confirmation-Token: 90215
Authorization: Token DEADBEEF
```

thanks

**Comment by tsenart** [comment]
Vegeta embraces the UNIX software philosophy. In this spirit, you can easily achieve what you want with some simple pre-processing of the targets with i.e. `sed` or `awk` before feeding them to Vegeta.
