### ISSUE TITLE
vegeta report -reporter json fails with 1 request

### ISSUE THREAD

**Issue by chriswatrous** [tsenart/vegeta#208]
### What version of the project are you using?
6.1.1

### What operating system and processor architecture are you using?
macOS Sierra
Version 10.12.1 (16B2555)
MacBook Pro (Retina, 15-inch, Mid 2014)
Processor: 2.5 GHz Intel Core i7

### What did you do?
I have a vegeta attack output file with only 1 request.
`cat attack_output.data | vegeta report -reporter json`

### What did you expect to see?
a json report

### What did you see instead?
```
> cat attack_output.data | vegeta report -reporter json
2016/12/14 19:38:29 json: unsupported value: +Inf

> echo $?
1
```

Looks like go's json formatter can't handle +Inf. In python, `json.dumps(float('inf')) == 'Infinity'`.

**Comment by tsenart** [comment]
Hey @chriswatrous, thanks for reporting this edge case. Just for me to understand where you're coming from, do you use Vegeta for single requests?

**Comment by chriswatrous** [comment]
If I have a call with a complicated body or set of headers, I sometimes use 1 call until I get everything right. I have a microservice that actually runs vegeta attack and a script that calls that microservice and generates the reports. My script fails if vegeta exits with a nonzero code.
