### ISSUE TITLE
Error report for multiple result files

### ISSUE THREAD

**Issue by chenzhiwei** [tsenart/vegeta#210]
Is there something wrong?

The requests rate seems not right.

## report 1

```
[root@server1 vegeta]# vegeta report -inputs=result1.bin
Requests      [total, rate]            6000, 100.02
Duration      [total, attack, wait]    59.990650162s, 59.989999661s, 650.501µs
Latencies     [mean, 50, 95, 99, max]  653.597µs, 654.05µs, 725.378µs, 900.028µs, 3.56416ms
Bytes In      [total, mean]            36000, 6.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:6000
Error Set:
```

## report 2

```
[root@server1 vegeta]# vegeta report -inputs=result2.bin
Requests      [total, rate]            6000, 100.02
Duration      [total, attack, wait]    59.9907269s, 59.989999665s, 727.235µs
Latencies     [mean, 50, 95, 99, max]  682.266µs, 667.233µs, 840.243µs, 915.14µs, 1.617746ms
Bytes In      [total, mean]            36000, 6.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:6000
Error Set:
```

## report 1 and 2

```
[root@server1 vegeta]# vegeta report -inputs=result1.bin,result2.bin
Requests      [total, rate]            12000, 9.18
Duration      [total, attack, wait]    21m47.89116987s, 21m47.890442635s, 727.235µs
Latencies     [mean, 50, 95, 99, max]  667.931µs, 661.355µs, 814.57µs, 915.14µs, 3.56416ms
Bytes In      [total, mean]            72000, 6.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:12000
Error Set:
```

**Comment by tsenart** [comment]
Hello @chenzhiwei. The rate is the ratio of requests in a given time span in seconds. Those two attacks were likely not overlapping so the timestamp must be quite long, which makes the rate very low.

**Comment by chenzhiwei** [comment]
But I used pdsh to make the attacks.

Is there a better way to make parallel attack?

And when I use it to attack haproxy, there are too many 408 error requests,
do you know the reason?

Thanks!

On Dec 25, 2016 23:07, "Tomás Senart" <notifications@github.com> wrote:

Hello @chenzhiwei <https://github.com/chenzhiwei>. The rate is the ratio of
requests in a given time span in seconds. Those two attacks were likely not
overlapping so the timestamp must be quite long, which makes the rate very
low.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tsenart/vegeta/issues/210#issuecomment-269126285>, or mute
the thread

**Comment by tsenart** [comment]
> But I used pdsh to make the attacks.

Ensure your node's clocks are synchronized. You may also inspect the individual results with:

```shell
$ vegeta dump < results.bin
```

> Is there a better way to make parallel attack?

pdsh is a fine choice for a distributed parallel attack. 

> And when I use it to attack haproxy, there are too many 408 error requests,
do you know the reason?

408s are usually served when your backends are timing out. Try to reduce the rate with which you're hitting the servers. Start small and increment gradually until you know at which point your bottlenecks emerge.

**Comment by chenzhiwei** [comment]
Thanks.

I encountered another issue, when I set one backend behind haproxy, the
rate can be 30000, but when I set two backends, the rate is less than 20000.

It's weird and I still can't find the reason.

**Comment by tsenart** [comment]
Good luck with your debugging session :-)
