### ISSUE TITLE
high (and nonlinear) cpu usage when calling some https endpoints

### ISSUE THREAD

**Issue by chriswatrous** [tsenart/vegeta#211]
I'm seeing high cpu usage when calling some https endpoints. The program [hey](https://github.com/rakyll/hey) (also written in go) has much lower cpu usage for the same request rates.

## 1. What version of the project are you using?

6.1.1

## 2. What operating system and processor architecture are you using?

- macOS Sierra 10.12.2
- 2.5 GHz Intel Core i7 (`sysctl hw | grep cpu` shows 4 physical cpus, 8 logical)

## 3. What did you do?

I'm using vegeta to call an app in an IBM Bluemix container. It's a simple python flask app run with gunicorn and has a /health route that returns 'ok'.

```
time echo 'GET https://ee16219bc5994b5ab349c951e35494f4.mybluemix.net/health' | vegeta attack -timeout 20s -rate 300 -duration 10s -keepalive true | vegeta report
```

varying the -rate parameter

I'm using the output of 'time' to calculate cpu time as a percentage of real time.

## 4. What did you expect to see?

CPU usage vary linearly with the rate.

## 5. What did you see instead?

CPU usage increases much faster than linear.

| rate | real | user | sys | (user+sys)/real | 50th | 95th | 99th | errors |
| ---- | ---- | ---- | --- | --------------- | ---- | ---- | ---- | ------ |
| 10 | 10.03 | 0.31 | 0.1 | 4.1% | 0.095 | 0.344 | 1.094 | 0.0% |
| 20 | 10.08 | 0.58 | 0.16 | 7.3% | 0.071 | 0.306 | 0.467 | 0.0% |
| 50 | 10.12 | 1.47 | 0.27 | 17.2% | 0.075 | 0.304 | 0.513 | 0.0% |
| 75 | 10.14 | 2.35 | 0.43 | 27.4% | 0.072 | 0.309 | 0.477 | 0.0% |
| 100 | 10.66 | 3.87 | 0.48 | 40.8% | 0.075 | 0.369 | 1.065 | 0.0% |
| 125 | 10.13 | 4.96 | 0.58 | 54.7% | 0.074 | 0.305 | 0.5 | 0.0% |
| 150 | 10.58 | 8.93 | 0.68 | 90.8% | 0.077 | 0.572 | 0.84 | 0.0% |
| 175 | 10.45 | 11.46 | 0.69 | 116.3% | 0.075 | 0.536 | 0.659 | 0.0% |
| 200 | 10.14 | 13.17 | 0.79 | 137.7% | 0.078 | 0.605 | 1.354 | 0.0% |
| 225 | 10.13 | 20.05 | 0.85 | 206.3% | 0.078 | 0.662 | 0.755 | 0.0% |
| 250 | 12.77 | 36.46 | 0.96 | 293.0% | 0.103 | 1.09 | 1.284 | 0.0% |
| 275 | 10.14 | 39.35 | 0.91 | 397.0% | 0.121 | 1.137 | 1.232 | 0.0% |
| 300 | 10.86 | 70.68 | 0.96 | 659.7% | 0.465 | 1.608 | 1.773 | 0.0% |
| 400 | 11.34 | 74.35 | 1.6 | 669.8% | 1.179 | 2.364 | 2.523 | 0.0% |
| 500 | 10.66 | 65.74 | 2.02 | 635.6% | 1.862 | 2.826 | 3.192 | 0.0% |
| 1000 | 14.47 | 94.8 | 2.36 | 671.5% | 1.043 | 8.55 | 8.909 | 50.8% |

![cpu usage](https://cloud.githubusercontent.com/assets/9014937/21736143/26fee004-d434-11e6-89d2-9e57c069e800.png)

This seems to depend on the endpoint being called. When I call https://httpbin.org/ip, I don't get this high cpu usage. I'm still trying to figure out what causes this difference.

| rps | real | user | sys | (user+sys)/real | 50th | 95th | 99th |
| --- | ---- | ---- | --- | --------------- | ---- | ---- | ---- |
| 10 | 10.05 | 0.16 | 0.09 | 2.50% | 0.09 | 0.328 | 0.547 |
| 20 | 10.11 | 0.19 | 0.13 | 3.20% | 0.095 | 0.264 | 0.526 |
| 50 | 10.16 | 0.39 | 0.29 | 6.70% | 0.096 | 0.228 | 0.475 |
| 100 | 10.15 | 0.63 | 0.42 | 10.30% | 0.098 | 0.311 | 0.516 |
| 200 | 11.27 | 1.18 | 0.75 | 17.10% | 0.097 | 0.325 | 0.503 |
| 500 | 10.17 | 3.53 | 1.29 | 47.40% | 0.136 | 2.168 | 2.96 |

![cpu usage](https://cloud.githubusercontent.com/assets/9014937/21736178/6c7fecc2-d434-11e6-9504-b322f09d7401.png)

It also doesn't happen when I use another program, [hey](https://github.com/rakyll/hey) (formerly called boom, also written in go), to do the test. That's why I think it's a problem with vegeta.

```
time -p hey -c 100 -n 5000 -m GET https://ee16219bc5994b5ab349c951e35494f4.mybluemix.net/health
```
varying -c (concurrency) and adjusting -n (number of requests) so that the test is about 10 seconds

| concurrency | rps | real | user | sys | (user+sys)/real | fastest | average | slowest |
| ----------- | --- | ---- | ---- | --- | --------------- | ------- | ------- | ------- |
| 1 | 11.175 | 9.02 | 0.06 | 0.03 | 1.0% | 0.067 | 0.089 | 0.481 |
| 10 | 113.044 | 8.92 | 0.6 | 0.17 | 8.6% | 0.067 | 0.085 | 0.431 |
| 20 | 187.029 | 10.77 | 1.25 | 0.35 | 14.9% | 0.069 | 0.091 | 0.549 |
| 30 | 289.149 | 10.45 | 2.01 | 0.48 | 23.8% | 0.066 | 0.093 | 1.004 |
| 50 | 421.542 | 9.56 | 3.4 | 0.61 | 41.9% | 0.066 | 0.108 | 0.797 |
| 75 | 586.192 | 9.41 | 4.94 | 0.7 | 59.9% | 0.066 | 0.117 | 0.898 |
| 100 | 692.189 | 9.61 | 5.87 | 0.75 | 68.9% | 0.066 | 0.132 | 1.139 |
| 300 | 689.372 | 10.09 | 16.69 | 0.76 | 172.9% | 0.071 | 0.369 | 4.144 |
| 500 | 675.723 | 9.7 | 26.83 | 0.79 | 284.7% | 0.068 | 0.593 | 5.991 |

![cpu usage](https://cloud.githubusercontent.com/assets/9014937/21736163/4c5986e2-d434-11e6-8bff-8962a1a01b47.png)

I left that app up at https://ee16219bc5994b5ab349c951e35494f4.mybluemix.net/health. Anyone who wants to do any debugging is free to hit it.

**Comment by tsenart** [comment]
Hello Chris,

Thanks for the very detailed issue report! Always glad to see this happen :-)

I'm investigating your report.

**Comment by tsenart** [comment]
I'm suspecting that we're not comparing apples to apples. The `hey -c` argument doesn't represent the same as `vegeta attack -rate`, `hey -q` does. Vegeta's worker count can be set with `-workers` too but will grow if needed to sustain the requested rate.

I tried to achieve a request rate of 1000 requests per second with hey but failed to do so. Here's what I ran.

```
$ time hey -q 1000 -n 10000 -m GET https://ee16219bc5994b5ab349c951e35494f4.mybluemix.net/health
44 requests done.
169 requests done.
296 requests done.
488 requests done.
651 requests done.
837 requests done.
969 requests done.
1149 requests done.
1335 requests done.
1529 requests done.
1721 requests done.
1915 requests done.
2089 requests done.
2237 requests done.
2436 requests done.
2622 requests done.
2802 requests done.
2982 requests done.
3176 requests done.
3371 requests done.
3500 requests done.
3644 requests done.
3798 requests done.
3985 requests done.
4073 requests done.
4247 requests done.
4436 requests done.
4630 requests done.
4828 requests done.
5001 requests done.
5131 requests done.
5306 requests done.
5490 requests done.
5676 requests done.
5868 requests done.
6055 requests done.
6247 requests done.
6415 requests done.
6585 requests done.
6710 requests done.
6904 requests done.
7074 requests done.
7245 requests done.
7444 requests done.
7599 requests done.
7763 requests done.
7958 requests done.
8115 requests done.
8308 requests done.
8498 requests done.
8688 requests done.
8862 requests done.
9055 requests done.
9253 requests done.
9418 requests done.
9559 requests done.
9693 requests done.
9764 requests done.
9856 requests done.
9928 requests done.
9972 requests done.
9993 requests done.
All requests done.

Summary:
  Total:	32.4832 secs
  Slowest:	2.4145 secs
  Fastest:	0.1246 secs
  Average:	0.1510 secs
  Requests/sec:	307.8516

Status code distribution:
  [200]	10000 responses

Response time histogram:
  0.125 [1]	|
  0.354 [9751]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.583 [185]	|∎
  0.812 [13]	|
  1.041 [0]	|
  1.270 [2]	|
  1.499 [29]	|
  1.728 [3]	|
  1.957 [0]	|
  2.186 [0]	|
  2.415 [16]	|

Latency distribution:
  10% in 0.1274 secs
  25% in 0.1291 secs
  50% in 0.1307 secs
  75% in 0.1332 secs
  90% in 0.1447 secs
  95% in 0.2358 secs
  99% in 0.4775 secs

real	0m32.505s
user	0m12.960s
sys	0m5.892s
```

One important thing you'll observe is that the time command will show more user time the more workers are used in hey. This can be changed with `-c`. Example of the above with `-c 1000`.

```
$ time ./hey -q 1000 -n 10000 -c 1000 -m GET https://ee16219bc5994b5ab349c951e35494f4.mybluemix.net/health
2 requests done.
13 requests done.
32 requests done.
79 requests done.
160 requests done.
270 requests done.
329 requests done.
514 requests done.
777 requests done.
987 requests done.
1208 requests done.
1563 requests done.
1958 requests done.
2411 requests done.
2788 requests done.
3182 requests done.
3646 requests done.
4107 requests done.
4618 requests done.
5125 requests done.
5603 requests done.
6074 requests done.
6530 requests done.
7009 requests done.
7457 requests done.
7932 requests done.
8372 requests done.
8822 requests done.
9265 requests done.
9747 requests done.
9981 requests done.
All requests done.

Summary:
  Total:	19.0183 secs
  Slowest:	17.2796 secs
  Fastest:	0.1249 secs
  Average:	1.4392 secs
  Requests/sec:	525.8107

Status code distribution:
  [200]	10000 responses

Response time histogram:
  0.125 [1]	|
  1.840 [8983]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  3.556 [22]	|
  5.271 [31]	|
  6.987 [73]	|
  8.702 [95]	|
  10.418 [135]	|∎
  12.133 [211]	|∎
  13.849 [315]	|∎
  15.564 [125]	|∎
  17.280 [9]	|

Latency distribution:
  10% in 0.1557 secs
  25% in 0.1980 secs
  50% in 0.2985 secs
  75% in 0.5342 secs
  90% in 2.4461 secs
  95% in 11.6775 secs
  99% in 14.1185 secs

real	0m19.059s
user	1m40.908s
sys	0m4.976s
```

I suspect this difference in CPU usage has something to do with more cores being utilised concurrently by default in Vegeta than in Hey.
