### ISSUE TITLE
Proposal: support custom http verbs

### ISSUE THREAD

**Issue by topliceanu** [tsenart/vegeta#214]
### rationale
- http/2 allows using custom http verbs (and I think they were allowed in http/1.1 as well) and there's no reason why vegeta can't support them.
- while not strictly RESTful, custom verbs have better semantics when working with resources.

### context 
- I ran `echo "SUBSCRIBE http://localhost" | vegeta attack -http2 | tee /tmp/results.vegeta | vegeta report` and I got back `2017/01/19 21:58:42 bad method: SUBSCRIBE` and an empty report.

### implementation
- ~~`vegeta attack` gets a new options `-allowed-methos=APPEND,SUBSCRIBE` which is a list of comma-separated verbs allowed in targets. This list of allowed methods gets passed to the Targeter~~ `vegeta attack` allows any ASCII upper-case word to be used as HTTP verb.
- I also added a test to make sure Targets are correctly configured
- ~~a WIP PR is here  https://github.com/tsenart/vegeta/pull/213~~ The new PR is here https://github.com/tsenart/vegeta/pull/217

**Comment by tsenart** [comment]
I'd just allow any string as method instead of defining the allowed ones per attack.

**Comment by topliceanu** [comment]
My thinking was that the targets file could come from a source you don't control, so you might need some method of checking. However you are absolutely right, allowing any word to be a verb is a MUCH simpler solution. I will open a PR for that.
