### ISSUE TITLE
Question: Can Vegeta do multiple GET/POST over single TCP session?

### ISSUE THREAD

**Issue by pngai1** [tsenart/vegeta#215]
Hi,

Can Vegeta do multiple GET/POST over single TCP session? If yes, what is the command options to use?

I would like to stress test my webserver with excessive VERB attack. That is single TCP session but many many times of GET/POST.

Thanks
Peter

**Comment by tsenart** [comment]
Reusing the underlying TCP connection controlled by the `-keepalive` flag and is enabled by default.
