### ISSUE TITLE
Trying to test 500 req/sec

### ISSUE THREAD

**Issue by brian-byungsookim** [tsenart/vegeta#219]
1. What version of the project are you using?
- v6.1.1
2. What operating system and processor architecture are you using?
- CentOS release 6.8 (Final), x86_64
3.  What did you do?
- `vegeta attack -targets=test.txt -rate=300 -duration=300s  > results.bin && vegeta report -inputs=results.bin -reporter=json > metrics.json`
4. What did you expect to see?
- success rate ≥ 0.95 in `metrics.json`
5. What did you see instead?
- success around ~0.75. The only error that appears in `metrics.json` is `socket: too many open files`, and I've already gradually modified the number of maximum file descriptors up to `ulimit -n 512000` on the server, and I still seem to get this error.

The contents of `test.txt` is just simply:
```
GET http://xx.xx.xx.xx:xxxx/health/check
Content-Type: application/json
```
which just returns a simple JSON object.

My question: should `vegeta` be able to handle 500 req/sec? This doesn't seem like it's too heavy of a load.

**Comment by tsenart** [comment]
It seems you're hitting file descriptor limits in your client machine, not the server.

**Comment by brian-byungsookim** [comment]
That was it, thanks! I don't know why I didn't consider that to be the issue at all...
