### ISSUE TITLE
is it possible to generate different data to POST?

### ISSUE THREAD

**Issue by skygragon** [tsenart/vegeta#221]
e.g. I need test an POST API with a json body, while there is a "timestamp" field that need to be different for individual request, so is it possible to do this with vegeta?

**Comment by tsenart** [comment]
Hello @skydragon,

You'll have to write a target generator that feeds into vegeta attack. Prior work on this: https://thisdata.com/blog/load-testing-api-interfaces-with-go-and-vegeta/

**Comment by skygragon** [comment]
Thanks! will try it.

**Comment by skygragon** [comment]
Just looked into the demo but seems may not fit my case.

If I understand it correctly, the pokemon will generate some json files in advance thus vegeta could pick them up in attack. However what I'm testing is try to simulate lots of time-series data to openTSDB, which requires each request must have different timestamp values, however I don't know how many requests/jsons should be prepared in the very beginning. Is there a way to let vegeta auto generate different data in the runtime instead of prepared?

**Comment by tsenart** [comment]
I think it does fit your case. You can create a program in any language that continuously generates new targets and their associated bodies that would be fed into vegeta attack with the `-lazy` flag set to true. What issues do you see with this approach?
