### ISSUE TITLE
Wrong latencies

### ISSUE THREAD

**Issue by stgleb** [tsenart/vegeta#223]
vegeta version Version 6.1.1
go version 1.8
os linux
arch amd64
GOMAXPROC 4

I make workload using command

`vegeta attack -targets=targets.txt -rate 500 -duration=1h|vegeta report`

Server I'm testing runs on localhost. I have monitoring established and I can observe latencies inside sysem with grafana. But results a very different, vegeta gives me

`Latencies     [mean, 50, 95, 99, max]  22.391007006s, 30.274744833s, 33.658350086s, 39.060970725s, 48.377163267s`

But in grafana I've got upper_99 percentie for latency equal to 63 ms. Max latency is about 110 ms. 
I've compared it by running workload with ab with 50 concurrent threads that gives  ~900 rps throughput, iso apache benchmark results are aligned well with grafana charts. What can be the reason this latencies in vegeta report?

**Comment by tsenart** [comment]
It looks like your server side metrics as well as `ab` are vulnerable to [Coordinated Omission](http://bravenewgeek.com/tag/coordinated-omission/), which Vegeta correctly accounts for.

**Comment by stgleb** [comment]
I'v tried the same with wrk2, that said to be coordinated omission safe and results are closer to ab than vegeta.

**Comment by tsenart** [comment]
OK. Need a way to reproduce your results to debug.

**Comment by stgleb** [comment]
I'll try to create somekind of playground to show you. By the way I thought that coordinated omission is only possible for client side benchmarking, but on server side all I do - measure time between start and end of function and send it to statd and display in grafana. Also when I run load test with vegeta - response time on server side monitoring increase too.

**Comment by tsenart** [comment]
@stgleb: Any news?

**Comment by torinaki** [comment]
@tsenart I have some different problem, but may be related problem.
Testing very simple server on NodeJS:
```
var http = require('http');

var srv = http.createServer(function (req, res) {
  var data, status;
  if(req.url === '/') {
    data = 'Hello world!';
    status = 200;
  } else {
    data = 'Not Found';
    status = 404;
  }
  res.writeHead(status, {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Length': data.length,
      'X-Powered-By': 'Node Server'
  });
  res.end(data);
});

srv.listen(8080, '0.0.0.0');
```

I can't get same latencies that I got with `wrk` tool. For example running following test with `wrk`:
```
wrk -t1 -c100 -d30s --latency http://127.0.0.1:8080/
```
here is the result:
```
Running 30s test @ http://127.0.0.1:8080/
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.71ms    2.77ms  83.72ms   96.77%
    Req/Sec    13.27k     1.71k   16.23k    86.33%
  Latency Distribution
     50%    7.18ms
     75%    7.81ms
     90%    8.63ms
     99%   16.86ms
  396192 requests in 30.01s, 68.01MB read
Requests/sec:  13202.33
Transfer/sec:      2.27MB
```

but running `vegeta` in following setup(Note! that request rate is much lower `-rate=3000`):
```
echo "GET http://127.0.0.1:8080/" | vegeta -cpus=1 attack -connections=100 -duration=30s -workers=1 -http2=false -rate=3000 -laddr=127.0.0.1 | vegeta report
``` 
i get worse latencies and even error appears:
```
Requests      [total, rate]            90000, 3000.04
Duration      [total, attack, wait]    30.006668944s, 29.999636596s, 7.032348ms
Latencies     [mean, 50, 95, 99, max]  34.085597ms, 260.796µs, 381.967139ms, 669.029088ms, 953.366714ms
Bytes In      [total, mean]            1078284, 11.98
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  99.84%
Status Codes  [code:count]             200:89857  0:143  
Error Set:
Get http://127.0.0.1:8080/: dial tcp 127.0.0.1:0->127.0.0.1:8080: socket: too many open files in system
```

**Comment by tsenart** [comment]
@torinaki: You're reaching resource limits on the attacking side. Use ulimit to adjust appropriately.
