### ISSUE TITLE
A body with x-www-form-urlencoded content type doesn't work

### ISSUE THREAD

**Issue by hectorj2f** [tsenart/vegeta#228]
I am trying to run an attack with a configuration using x-www-form-urlencode. It doesn't work but it works when I tried with `curl`. 

version: 6.3.0

Why isn't it working ?  or what am I doing wrong ?

```
echo "POST https://$URL" > targets
echo 'client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant=new&refresh_token=$REFRESH_TOKEN' > body.json

vegeta -profile cpu attack -body=body.json -header="Content-Type:application/x-www-form-urlencode" -targets=targets -rate=$RATE -duration=$DURATION > results_refresh_$i.bin

Duration      [total, attack, wait]    2.234227022s, 1.979999934s, 254.227088ms
Latencies     [mean, 50, 95, 99, max]  503.944537ms, 430.710359ms, 904.917724ms, 945.09527ms, 965.164951ms
Bytes In      [total, mean]            8400, 84.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  0.00%
Status Codes  [code:count]             400:100
Error Set:
400 Bad Request
```

Curl command that works.
```
  curl -H "Content-Type:application/x-www-form-urlencoded" -XPOST https://$URL --data "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant=new&refresh_token=$REFRESH_TOKEN"
```

**Comment by hectorj2f** [comment]
I appreciate any help :)

**Comment by tsenart** [comment]
I can't see anything immediately wrong. Would you provide a reproducible case for further debugging? It could be useful to see the difference of the curl and vegeta requests in your server's logs.

**Comment by hectorj2f** [comment]
@tsenart Unfortunately, I cannot. But, if you give me some tips where I could try to debug the problem or check where it might fail.

**Comment by tsenart** [comment]
Yeah, check your server logs for differences. If you can't do that, I'd try tcpdump and Wireshark on the client side.

**Comment by tsenart** [comment]
Any news?

**Comment by satishjaiswal** [comment]
Did you figured it out yet. I am running into similar issue.

**Comment by hectorj2f** [comment]
@satishjaiswal i didn't find time to trace the issue :/, yet.

**Comment by tsenart** [comment]
I'll re-open when you have more information.

**Comment by bhuvanvenkat-plivo** [comment]
@hectorj2f Try the following work around.
1. Convert the xml to encoded string format and save it to a text file.
2. -body=<your_text_file>.txt

PS: you text file should be of the format : key=url_encoded_string
ex:
if your xml is 
`<hello>
  <name> hectorj2f </name>
</hello>
`
url encoded string will be: 
`
%3Chello%3E%0D%0A++%3Cname%3E+hectorj2f+%3C%2Fname%3E%0D%0A%3C%2Fhello%3E
`
so, your text file wil be: key=%3Chello%3E%0D%0A++%3Cname%3E+hectorj2f+%3C%2Fname%3E%0D%0A%3C%2Fhello%3E

'key' as in payload to be sent to the server.

You can encode it [here](http://url-encode.online-domain-tools.com/)
Most of the https clients shall automatically encode the xml to url encoded string.
