### ISSUE TITLE
Bad Method: &{400 GO with Vegeta

### ISSUE THREAD

**Issue by matthew-fukui** [tsenart/vegeta#230]
<strong>1. What version of the project are you using?</strong>
mine was ??? 

<strong>2. What operating system and processor architecture are you using?</strong>
ubuntu 16.04 LTS 64bit, Intel Core i7-4710MQ @ 2.50GHz x 8 [Dual booting with windows]

<strong>3. What did you do?</strong>
I'm using this as a reference https://thisdata.com/blog/load-testing-api-interfaces-with-go-and-vegeta/
I ran this `body POST[Link unable to show due to confidential reasons] | \vegeta attack -rate=1 -duration=1s | vegeta report `
or
`body | vegeta attack -duration=2s | vegeta report`
I am still greeted with bad method error.
In my body.go, The content type is multipart/form-data and it is generated by Postman [Google chrome add on]

`UPDATE`
One thing is, The codes inside the body.go are suppose to add a user through the API I specified in the link, i got bad method: &{200. I checked and user is added but vegeta report is still not shown and bad method still exists. 

I have tested with GO alone and the POST is working. [No worries on the link POST link]
I have already get all the dependencies for GO, ran `go install body`. It works when i run body alone but if i pipe it with vegeta, an error is raised.

<strong>4. What did you expect to see?</strong>
to have vegeta report generated.

<strong>5. What did you see instead?</strong>
```
body POST [Link unable to show to due confidential reasons] | \vegeta attack -rate=1 -duration=1s | vegeta report
2017/05/08 17:47:44 bad method: &{400
Requests      [total, rate]            0, 0.00
Duration      [total, attack, wait]    0s, 0s, 0s
Latencies     [mean, 50, 95, 99, max]  -2562047h47m16.854775808s, 0s, 0s, 0s, 0s
Bytes In      [total, mean]            0, NaN
Bytes Out     [total, mean]            0, NaN
Success       [ratio]                  NaN%
Status Codes  [code:count]             
Error Set:
```

**Comment by optiomas** [comment]
Please share your body.go program so that we can debug this.

**Comment by matthew-fukui** [comment]
This is my body.go file. It's directly extracted by google Postman
```
package main

import (
	"fmt"
	"strings"
	"net/http"
	"io/ioutil"
)

func main() {

	url := "https://[LINK]"

	payload := strings.NewReader("------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"email\"\r\n\r\ntest@email.com\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"password\"\r\n\r\nPa$$word1\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"first_name\"\r\n\r\nTest1\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"last_name\"\r\n\r\wan\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"preferred_name\"\r\n\r\nyasha enryu\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"mobile_country_code\"\r\n\r\n65\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"mobile\"\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--")

	req, _ := http.NewRequest("POST", url, payload)

	req.Header.Add("content-type", "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW")
	req.Header.Add("cache-control", "no-cache")
	req.Header.Add("postman-token", "c0a4ecc4-abdf-570d-2cab-0d54ea485d4d")

	res, _ := http.DefaultClient.Do(req)

	defer res.Body.Close()
	body, _ := ioutil.ReadAll(res.Body)

	fmt.Println(res)
	fmt.Println(string(body))

}
```
