### ISSUE TITLE
Attack with cert is not working

### ISSUE THREAD

**Issue by tommysitu** [tsenart/vegeta#231]
I tried this with the latest vegeta: 
```
echo "GET https://www.my-test.com/api/bookings/1" | vegeta attack -duration=2s -header="Proxy-Authorization: Bearer some-token" -cert=my-cert.pem | tee results.bin | vegeta report
```

I got this error: `tls: found a certificate rather than a key in the PEM for the private key`

It doesn't make sense to me, because I am using the -cert flag, and the error is saying I need to pass it a key file? 

The cert I provided work fine in the browser or using curl, because it is trusted in my keychain.

**Comment by optiomas** [comment]
What are you trying to do? Is that a client certificate you are trying to use?

**Comment by tommysitu** [comment]
The target I am trying to load test required a self-signed certificate which is just a simple PEM encoded client certificate, and I am passing it with the `-cert` flag. 

If I don't provide a cert and run the command, I will get this error: 
```
Error Set:
Get https://www.my-test.com/api/bookings/1: net/http: TLS handshake timeout
```
By the way, I am using a proxy, and it is set by `export HTTP_PROXY=some-proxy:8500`

**Comment by optiomas** [comment]
If your PEM encoded file contains both your private key and your certificate, then pass it to the `-key` flag too.

**Comment by tommysitu** [comment]
The file is just the cert. Why do I need to pass a key? The client only need to present a certificate to SSL handshake with the server.

**Comment by optiomas** [comment]
https://security.stackexchange.com/questions/141048/client-private-key-in-tls-handshake

**Comment by tommysitu** [comment]
Sorry I got mixed up, the certification file I am using is a server certificate, not client certificate. It is a CA for the self-signed-certificate. I've tried passing it to `-root-certs`, and it returns `net/http: TLS handshake timeout`. 
The certificate is trusted in my keychains, and it works when I use curl.

**Comment by optiomas** [comment]
You don't pass a CA to the root-certs flag, you'd pass a server certificate signed by the CA.

**Comment by mogronalol** [comment]
@optiomas We currently have our own CA, which then signs our server certificates. Normally, we just trust the CA, which in turn means everything that it signs is trusted by our clients. For example, when using `curl` we pass in a _CA_ using the `cacerts` argument, not the server certificate itself. If we took the approach of passing in the certificate then we would have to download and trust every single certificate signed by it (which is a lot), as opposed to the single CA certificate.

**Comment by optiomas** [comment]
OK. So, you need to pass the CA to the `-root-certs` flag and the PEM encoded client certificate to `-cert` and `-key`

**Comment by mogronalol** [comment]
I don't think we actually require client certificates in our case, as it's not two-way SSL (Unless I am misunderstanding something). So all we need to do is trust our CA. However:

```
$ export https_proxy=junior-tennis-tommysitu.hoverfly.io:8500
$ echo "GET https://www.my-test.com/api/bookings/1" | vegeta attack -duration=2s -header="Proxy-Authorization: Bearer some-token" -root-certs=my-cert.pem | tee results.bin | vegeta report
```

Gives:

```
Error Set:
Get https://www.my-test.com/api/bookings/1: net/http: TLS handshake timeout
```

Whereas if we tried the same approach with something like curl, it works:

```
curl --header “Proxy-Authorization: Bearer some-token” --proxy junior-tennis-tommysitu.hoverfly.io:8500 https://www.my-test.com/api/bookings/1 --cacert=ca.pem
```

**Comment by tommysitu** [comment]
Tried `-insecure` option, I got the same error: 
```
$ export HTTPS_PROXY=junior-tennis-tommysitu.hoverfly.io:8500
$ export HTTP_PROXY=junior-tennis-tommysitu.hoverfly.io:8500
$ echo "GET https://www.my-test.com/api/bookings/1" | vegeta attack -duration=1s -header="Proxy-Authorization: Bearer $HFC_AUTH_TOKEN" -insecure | tee results.bin | vegeta report
Requests      [total, rate]            50, 51.02
Duration      [total, attack, wait]    16.691457372s, 979.999887ms, 15.711457485s
Latencies     [mean, 50, 95, 99, max]  12.751132876s, 12.204878248s, 15.709532611s, 15.784496102s, 15.811457485s
Bytes In      [total, mean]            2368, 47.36
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  32.00%
Status Codes  [code:count]             200:16  0:34
Error Set:
Get https://www.my-test.com/api/bookings/1: net/http: TLS handshake timeout
```

**Comment by tsenart** [comment]
Please re-open if this hasn't been resolved.
