### ISSUE TITLE
Is it possible to pass basic authentication credentials?

### ISSUE THREAD

**Issue by hanneslehmann** [tsenart/vegeta#232]
Hi,

I was checking the documentation but didn't find any hint, in curl I can pass user/password credentials via -u flag. Is it possible to use the tool for calling http endpoints secured by basic authentication somehow?

Thanks and regards,
Hannes

**Comment by optiomas** [comment]
Yes, put credentials in the URL: https://username:password@foobar.com/

**Comment by hanneslehmann** [comment]
Easy :+1: 
Thanks, that works

**Comment by optiomas** [comment]
Please close then :-)
