### ISSUE TITLE
Support for request rates less than 1/sec

### ISSUE THREAD

**Issue by kujenga** [tsenart/vegeta#233]
For certain endpoints, like batch data imports, it can be useful to perform load testing at a rate lower than 1 req/sec. Currently Vegata doesn't seem to support this use case due to the fact that the `rate` is specified in seconds as a `uint64`: https://godoc.org/github.com/tsenart/vegeta/lib#Attacker.Attack

One way I can think to add support for this functionality and avoid making a breaking change would be to add a `func Unit(d time.Duration) func(*Attacker)` that could be used to specify the unit in which the rate is specified.

Does this seem like a reasonable change, and a reasonable implementation path for it?

**Comment by Dieterbe** [comment]
@kujenga did you ever end up implementing this? this would be helpful to me as i need to benchmark what happens when our backend receives very expensive requests, which would be scheduled at 0.1Hz or so.

**Comment by tsenart** [comment]
Alternatively, we could change the -rate flag to read a string, expecting either an int which would assume per second rate or a string which would define the unit like: 200/s, 1/m, 20/ms, etc

What do you think about this UX?

**Comment by Dieterbe** [comment]
that sounds pretty nice. perhaps a bit awkward to write 0.1Hz as `6/m` but it is very flexible towards either extreme (e.g. makes it easy to write down 1 request per hour)

**Comment by tsenart** [comment]
How does the API proposed in https://github.com/tsenart/vegeta/issues/305 look like to you?

**Comment by kujenga** [comment]
Neat! I like that idea and what's sketched out in that ticket quite a bit.

Sorry for the late response here, but the path I took here was basically using some of vegata's reporting features and re-implementing a simpler version of the logic around actually sending requests, baking that into an internal testing tool. Would love to delete that code and use more of the library!

**Comment by Dieterbe** [comment]
seems reasonable
