### ISSUE TITLE
Real like traffic test

### ISSUE THREAD

**Issue by stereobooster** [tsenart/vegeta#235]
Thanks, for cool project.

I have requests breakdown from production system (getting this data from ELK).

It looks something like:

- request 1 - 50%
- request 2 - 20%
- request 3 - 10%
- request 4 - ...

So i want to script the same type of requests and make vegeta to do "real-like traffic" so it preserves distribution of requests. 

Then I want it slowly start to increase number of requests until service starts to fail. E.g. error rate get higher some level.

Is it possible?

**UPD**

So I was thinking of something like this:

```
POST http://goku:9090/things
@/path/to/newthing.json
%60

PATCH http://goku:9090/thing/71988591
@/path/to/thing-71988591.json
%40
```

**Comment by thalesfsp** [comment]
@stereobooster Have your changes been merged? @tsenart

**Comment by stereobooster** [comment]
no

**Comment by thalesfsp** [comment]
@stereobooster What’s missing so we can get a PR? Do you need help? Really cool and welcome the feature that you described!

**Comment by stereobooster** [comment]
https://github.com/tsenart/vegeta/pull/236#issuecomment-328530817
