### ISSUE TITLE
HTML plot not showing 

### ISSUE THREAD

**Issue by aidylewis** [tsenart/vegeta#237]
With a large file over 10GB (when compressed). Cannot add it here. 
results.bin: https://drive.google.com/open?id=0B2QklcOYaqCASUNGalhuMzNzSkE

**Comment by aidylewis** [comment]
Installed 'go version go1.8.3' from source and Vegeta HEAD. Still no graph.

**Comment by aidylewis** [comment]
Do we have any idea of what this issue could be?

**Comment by optiomas** [comment]
The HTML plot doesn't do any sort of smart tine series compression. It adds every single data point to the plot. Without further investigation, I imagine this is a scaling problem. The browser's Javascript engine probably can't handle that data size.
