### ISSUE TITLE
gob: encoded unsigned integer out of range

### ISSUE THREAD

**Issue by aidylewis** [tsenart/vegeta#238]
vegeta --version
6.3.0

echo "GET http://open.stage.bbc.co.uk/loadtest/2kb" | vegeta attack -duration=20m -rate=5000| tee results.bin | vegeta report

c4.8xlarge

gob: encoded unsigned integer out of range

**Comment by tsenart** [comment]
Is the OS version the release used matching the architecture? Also, have you tried running the latest release?

**Comment by aidylewis** [comment]
Was using LinuxBrew which would compile the source. I'll use the go commands to get and build the HEAD.

**Comment by aidylewis** [comment]
incorrect user install
