### ISSUE TITLE
Unable to get Vegeta

### ISSUE THREAD

**Issue by vectar31** [tsenart/vegeta#240]
I have golang-1.8
When I try to use `go get -u github.com/tsenart/vegeta`
It gives me the following response : 

```
# github.com/tsenart/vegeta/lib
go/src/github.com/tsenart/vegeta/lib/attack.go:99: undefined: http.ErrUseLastResponse

```
I thought its a version issue with go lang but it isn't. Help?

**Comment by aidylewis** [comment]
Try use the binary for your OS and architecture. 
https://github.com/tsenart/vegeta/releases

wget /usr/local/bin ...

**Comment by arafangion** [comment]
Update to the latest version of Go.  I was getting that error using Go 1.6 (which is the version installed on Ubuntu 16.04 LTS).

Updating to Go version 1.9 fixed it beautifully.
