### ISSUE TITLE
when i run in ubuntu 16 it is look like messy code;

### ISSUE THREAD

**Issue by buzai** [tsenart/vegeta#246]
1:./vegeta attack -rate 10000 --targets ./targ.txt

2:targ.txt->
POST http://0.0.0.0:7070/api/market/publish/buy
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAwMDgsImVtYWlsIjoiNzgzMjQzMDc3QHFxLmNvbSIsInVzZXJUeXBlIjowLCJpYXQiOjE1MDA5NjI3Mjd9.pApc7-PxhIsfVncp3k23nLMfKkMwPbd7LWXLMW6TMK8
@./body.json

3:so it stdout 
N(sH'��z�lnPost http://0.0.0.0:7070/api/market/publish/buy: dial tcp 0.0.0.0:0->0.0.0.0:7070: socket: too many open files�����
N(sL����\nPost http://0.0.0.0:7070/api/market/publish/buy: dial tcp 0.0.0.0:0->0.0.0.0:7070: socket: too many open files�����
N(sQj����pnPost http://0.0.0.0:7070/api/market/publish/buy: dial tcp 0.0.0.0:0->0.0.0.0:7070: socket: too many open files�����
N(sV����nPost http://0.0.0.0:7070/api/market/publish/buy: dial tcp 0.0.0.0:0->0.0.0.0:7070: socket: too many open files�����

**Comment by simonmurdock** [comment]
You have to output somewhere. add `` | vegeta report`` on the end

**Comment by buzai** [comment]
thank u @simonmurdock
