### ISSUE TITLE
Question: Using cookie session

### ISSUE THREAD

**Issue by MarcelGeo** [tsenart/vegeta#250]
Hello.

I have question about cookie session. Is it possible to attack website, which stores session into cookie. And consequently send back this cookie for manipulation in server?

Thank you.

**Comment by daluu** [comment]
I think your best bet might be to use this feature of vegeta: https://github.com/tsenart/vegeta#usage-library, if you can work with go.

**Comment by daluu** [comment]
You might want to look at #247 as well.

**Comment by tsenart** [comment]
Not possible at the moment.
