### ISSUE TITLE
get output in real-time

### ISSUE THREAD

**Issue by MarStarck** [tsenart/vegeta#251]
vegeta get output.bin after the attack is finished.  and then convert it to report afterwards. 
Can it provides real-time attack result?

**Comment by aidylewis** [comment]
While loop on 'vegeta report' in a seperate terminal.

**Comment by MarStarck** [comment]
Well, loop 'vegeta report' seems get report in total. How can I clear old result data every time?
for example, I run vegeta report every 1 second, and I want report the data only in this second, not all result.
I try to write some code but Report only has Add method, no Clean method or something...
