### ISSUE TITLE
Plotly.js for real-time analysis 

### ISSUE THREAD

**Issue by aidylewis** [tsenart/vegeta#252]
We know we can loop against the report to generate real-time stats. What do you think about sed/awk and posting to a service with Plotly?

**Comment by daluu** [comment]
that sounds like 3rd party / unix toolchain wrapping around vegeta and not native to vegeta itself?

**Comment by rs** [comment]
I published a tool to integrate vegeta with [jplot](https://github.com/rs/jplot), you might be interested: https://github.com/rs/jaggr#vegeta

**Comment by tsenart** [comment]
@rs: Looks great! Please add it to the README in Vegeta :)
