### ISSUE TITLE
report should support multiple results files on stdin

### ISSUE THREAD

**Issue by johnl** [tsenart/vegeta#254]
the "vegeta report" command should allow me to concat a bunch of result files into it at once, so I can easily merge several reports together using cat. When I try that, I get an error:

    $ cat results.bin.* | vegeta report
    2017/08/18 10:27:55 extra data in buffer

**Comment by optiomas** [comment]
It does support that via the `-inputs` flag.

**Comment by johnl** [comment]
I specifically want to be able to cat multiple files into it rather than specify them individually as inputs, as providing a comma separated list of inputs is quite fiddly to do. Alternatively #255 helps me instead if that's easier, but it's a common UNIX pattern to access input like this and I was surprised it didn't work.

**Comment by optiomas** [comment]
cat doesn't know how to merge the input files which are binary. Your other proposal looks interesting and backwards compatible.

**Comment by johnl** [comment]
yeah I was hoping vegeta would just recognise that files had been concatted on stdin, but #255 would be a huge improvement from a UI standpoint so that'd solve my real problem tbh. Feel free to reject this in favour of that.

**Comment by optiomas** [comment]
Hmmm, that may be possible. I have to investigate.

**Comment by tsenart** [comment]
Closed in favour of #255.
