### ISSUE TITLE
report should accept input files as standard files arguments

### ISSUE THREAD

**Issue by johnl** [tsenart/vegeta#255]
the -inputs argument for report accepts a comma separated list of results files. This isn't a very standard way of accepting file arguments - I'm having to jump through a load of hoops to turn a list of files into a command separated list for it.

if it just accepted input files directly as arguments, I could use a standard file pattern glob from bash, or use xargs even:

    vegeta report results.bin.*

or

    find . -name results.bin | xargs vegeta report

**Comment by tsenart** [comment]
Implementing this now. `vegeta plot` and `vegeta encode` already support this pattern.
