### ISSUE TITLE
Upper bound for vegeta rate

### ISSUE THREAD

**Issue by MarStarck** [tsenart/vegeta#256]
when visit some website, vegeta rate cannot reach given rate, and always goes into this part:
`
default: // all workers are blocked. start one more and try again
workers.Add(1)
go a.attack(tr, &workers, ticks, results)
}`
[These may be caused by the website visit limitations]
And the worker hardly stop after given duration.

**Comment by tsenart** [comment]
Please fill out a more detailed issue: https://github.com/tsenart/vegeta/issues/new/choose
