### ISSUE TITLE
error: flag provided but not defined: -header

### ISSUE THREAD

**Issue by rahulx411** [tsenart/vegeta#257]
./vegeta **-header=Content-Type:application/json**  attack -targets=target.txt -body=body.json -rate=100 -duration=10s | ./vegeta report |more
_flag provided but not defined: -header_

Would really appreciate any advice..
```
./vegeta -version
v6.3.0
```

**Comment by optiomas** [comment]
That flag needs to come after the command name.

**Comment by rahulx411** [comment]
had overlooked that ..works fine Thanks! 👍
