### ISSUE TITLE
Hit Target only once?

### ISSUE THREAD

**Issue by kmcrawford** [tsenart/vegeta#262]
Is to possible to hit each target only once, only for a dry run type of scenario?  I work with a lot of third parties and I do not want to call their service multiple times during a load test.  So I am using a utility called wiremock that I can record their responses prior to doing a load test.  So I am looking to do the following:

1.) Turn on wiremock recording
2.) Call third parties once using vegeta utilizing a input file
3.) Turn off wiremock recording
4.) Load test my service that will use wiremock endpoint vs third party.

I have all of this working except for calls for #2 that aren't idempotent (such as create a new user). If there is a way I can use vegeta to call the target file only once during recording, I can get around my issue.

I might also be about to get around this during wiremock record to ignore repeat requests, but still looking into it.

**Comment by daluu** [comment]
What was the resolution to the issue?

**Comment by kmcrawford** [comment]
I was able to make wire mock ignore repeated requests.
