### ISSUE TITLE
add proxy socks 5?

### ISSUE THREAD

**Issue by f4nff** [tsenart/vegeta#265]
Can I add support for bulk socks5? This makes it easy for different area requests

add proxy socks list?

"golang.org/x/net/proxy"

**Comment by mail3dexter** [comment]
I would also like to request adding SOCKs proxy support

**Comment by tsenart** [comment]
Can you please re-submit this feature request with the new template? Thank you.
https://github.com/tsenart/vegeta/issues/new?template=feature_request.md
