### ISSUE TITLE
Incremental load attack

### ISSUE THREAD

**Issue by mousavian** [tsenart/vegeta#271]
Do you think it would be useful to have a couple of more options for increasing the rate over time additional to "constant request rate"?
This will prevent bursts and would be good to test auto scalable apps in wider period of time.

What I propose is two more options like `inc-rate` and `inc-time`; to increment rate on every `inc-time`.

```
vegeta attack -duration=600s -rate=1000 -inc-rate=20% -inc-time=30s
```

**Comment by ankitg12** [comment]
Seems similar to https://github.com/tsenart/vegeta/issues/163

**Comment by tsenart** [comment]
This is easily done with a shell script starting successive attacks at higher rates. To be properly documented in #304.
