### ISSUE TITLE
Vegeta should support body file input via URL

### ISSUE THREAD

**Issue by pswenson** [tsenart/vegeta#272]
I think it would be useful for vegeta to support `-body` from a URL.  If running in a docker container or on multiple remote servers, it can be a hassle to move files to the correct location.  Having option to host file via URL make usage easier

**Comment by daluu** [comment]
Good suggestion. For docker though, couldn't you just store files in a central file store accessible by docker (host) infrastructure, and map that filestore path (on docker host) to a local path on the docker container? And that is same static path mapping for all vegeta docker containers that are started.

**Comment by pswenson** [comment]
sure, it's possible to map volumes to share the file.  But it's very nice to be able to ssh to a server and simply run a docker command to start a load test (no scping files)

**Comment by tsenart** [comment]
If you have curl in your Docker image, then this is trivial. What prevents you from using curl before the attack to download your body file?

**Comment by pswenson** [comment]
nothing prevents using curl.. it's a purely a convenience + a commonly used
pattern

e.g. if you are a kuberenetes user here are some sample commands:
$ kubectl create -f myresource.yaml                        # create
resource(s) from yaml file
$ kubectl create -f https://git.io/vPieo         # create resource(s) from
url

**Comment by tsenart** [comment]
While I understand where this request is coming from, it is quite at odds with the UNIX philosophy that Vegeta is built with and that I'm striving to maintain. In any case, thank you for the proposal!
