### ISSUE TITLE
Dynamic Request (all of them)

### ISSUE THREAD

**Issue by tonytcb** [tsenart/vegeta#273]
It's possible for Vegeta make each request different from the previous request, headers and body?

I made a script to generate the custom request like Vegeta expects, but Vegeta uses that same request every time in the current  test. I wanted one different request each time.

I wanted that because my API blocks equal requests after the first is successfully complete.

**Comment by optiomas** [comment]
Just define different targets. Why a single one?

**Comment by tonytcb** [comment]
So, if my test runs duration=3s and rate=2 (total of 6 requests), I should use 6 different targets?

:: I really appreciate your job with this project. It's simple, easier and efficient than anothers than I already used. Thanks!

**Comment by optiomas** [comment]
Per your use case, no need to define 6 targets, only 2 and cycle through both of them on each request.

**Comment by tonytcb** [comment]
I did as you said. 2 targets with the below command :
`go run main.go | ./vegeta attack -duration=3s -rate=2 | tee results.bin | ./vegeta report`

But, the test executed 6 requests. 3 with the first target and 3 with the second target. I wanted 6 different requests.

I'm doing something wrong yet?

**Comment by optiomas** [comment]
I thought you our backend just needed the previous request to be different from the next. If you need every request to be different then you need to generate a different target for every hit. Using a script to pipe these to vegeta attack would be the way to go.

**Comment by tonytcb** [comment]
I see. Anyway, thank you very much for your time.
