### ISSUE TITLE
README `cpus` parameter divergent defaults

### ISSUE THREAD

**Issue by streeck** [tsenart/vegeta#275]
When reading through README under **Usage Manual** section you'll first see:

```
global flags:
  -cpus int
      Number of CPUs to use (default 8)
```

Here it says that the number of CPUs default to 8, however, scrolling down a little further you will see:

```
-cpus
    Specifies the number of CPUs to be used internally. It defaults to the amount of CPUs available in the system
```

Here it says that the same parameter defaults to the CPUs available in your system.

**Comment by optiomas** [comment]
Yeah, that first instance is just a copy paste of running -h on my machine.

**Comment by streeck** [comment]
Ah okay, at first I was a bit confused. Thanks for the clarification ;).

Maybe changing the order in which things appear in the README could help making things a bit more clear, what do you think?

**Comment by optiomas** [comment]
I'd just remove the "(default 8)" part.
