### ISSUE TITLE
limit on 8192 simultaneously alive goroutines is exceeded, dying...

### ISSUE THREAD

**Issue by lnshi** [tsenart/vegeta#285]
I just follow the example on the homepage, which when i run with rate `50` duration `60` it is perfectly fine, but when i try to run with rate `200` duration `60`, then i am running into this issue:

    limit on 8192 simultaneously alive goroutines is exceeded, dying...

@tsenart  pls help, thanks for ur time.

**Comment by tsenart** [comment]
Hi @lnshi,

The vegeta process is hitting OS resource limits. Have you tried tuning those? Check https://github.com/tsenart/vegeta#limitations

**Comment by lnshi** [comment]
@tsenart hmm, i tried to search that error message, it doesn't look like related to the `ulimit`, but let me try that first.

**Comment by lnshi** [comment]
@tsenart  no, it is not the `ulimit` issue, i increased the ulimit to **655340**,  both for `-u` and `-n` still getting the same issue: `GOCACHE=off go test -v -race -tags load tests/load_test.go -run TestInceptionPredictAPILoad -args -rate=200 -duration 30`

    === RUN   TestInceptionPredictAPILoad
    race: limit on 8192 simultaneously alive goroutines is exceeded, dying
    FAIL	command-line-arguments	14.523s
