### ISSUE TITLE
Keep getting 0 Status code

### ISSUE THREAD

**Issue by calvinvoo2** [tsenart/vegeta#287]
I am on Mac OS and I use both the homebrew and the go package. 

It is fine when I use the command line
`vegeta attack -duration=5s -rate=150  -targets=targets.txt | vegeta report -reporter=text`
It will be 100% success

But when I use it inside a Go project,
It keeps getting 0 responses status code.
I expect to see the same result as the one using command line

**Comment by tsenart** [comment]
Please submit a more structured bug report: https://github.com/tsenart/vegeta/issues/new?template=bug_report.md
