### ISSUE TITLE
How may I get save the responses to local files?

### ISSUE THREAD

**Issue by pivdets** [tsenart/vegeta#290]
#### Question

I've tried `$ vegeta attack -rate=1 -duration=10s -targets=targets.txt | vegeta report` which show me the latencies and so on.

And tried `$ vegeta attack -rate=1 -duration=10s -targets=targets.txt | vegeta dump` which show me `"body":"eyJlcnJjb2RlIjotMywibXNnIjoiaW52YWxpZCBzZXNzaW9uIn0="` but I don't know what does it mean.

I have to check the response data in order to make sure my request is correct, but I don't know how to do.

**Comment by contactparthshah** [comment]
body is base64 encoded. if you are using linux then decode with something like:

parth~#:~# echo eyJlcnJjb2RlIjotMywibXNnIjoiaW52YWxpZCBzZXNzaW9uIn0= | base64 -d
{"errcode":-3,"msg":"invalid session"}.

Hope it helps

**Comment by tsenart** [comment]
Yep. You can use jq to take only the body out and then decode it with base64

**Comment by tsenart** [comment]
`... | vegeta dump | jq '.body| @base64d`
