### ISSUE TITLE
Can anyone explain more about vegeta report?

### ISSUE THREAD

**Issue by contactparthshah** [tsenart/vegeta#293]
#### Question

I ran test using vegeta and it has generated following report:

```
Requests      [total, rate]            200, 19.35
Duration      [total, attack, wait]    11.978051256s, 10.337022623s, 1.641028633s
Latencies     [mean, 50, 95, 99, max]  646.318364ms, 451.048775ms, 1.697808872s, 2.128540278s, 2.641028633s
Bytes In      [total, mean]            84733, 423.67
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  93.50%
Status Codes  [code:count]             403:13  200:187
Error Set:
403 Forbidden
```

It will be good if anyone can help me to understand the report.
> what to deduce from Duration      [total, attack, wait]    11.978051256s, 10.337022623s, 1.641028633s ?

> What to deduce from Latencies     [mean, 50, 95, 99, max]  646.318364ms, 451.048775ms, 1.697808872s, 2.128540278s, 2.641028633s ?

> what to deduce from Bytes Out     [total, mean]            0, 0.00 ?

> why Bytes Out is 0 ?

**Comment by tsenart** [comment]
> what to deduce from Duration [total, attack, wait] 11.978051256s, 10.337022623s, 1.641028633s ?

- **attack** is the amount of time taken issuing all requests (total - wait)
- **wait** is the amount of time waiting for the response to the last request (total - attack)
- **total** is the total amount of time taken in the attack (attack + wait).

> What to deduce from Latencies [mean, 50, 95, 99, max] 646.318364ms, 451.048775ms, 1.697808872s, 2.128540278s, 2.641028633s ?

- **latency** is the amount of time taken for a response to a request to be read (including the body).
- **mean** is the [arithmetic mean / average](https://en.wikipedia.org/wiki/Arithmetic_mean) of the latencies of all requests in an attack.
- **50, 95, 99** are the 50th, 95th an 99th [percentiles](https://en.wikipedia.org/wiki/Percentile), respectively, of the latencies of all requests in an attack. To understand more about why these are useful, I recommend [this article](https://bravenewgeek.com/everything-you-know-about-latency-is-wrong/) from @tylertreat.
- **max** is the maximum latency of all requests in an attack.

> what to deduce from Bytes Out [total, mean] 0, 0.00 ?
> why Bytes Out is 0 ?

The **BytesOut** section describes summary metrics of the number of bytes sent out in request **bodies** during attacks. If you haven't defined a body, it will be zero.

**Comment by tsenart** [comment]
Please re-open if you have further questions.

**Comment by contactparthshah** [comment]
Thank you.

**Comment by jzaefferer** [comment]
Those details would be pretty useful in the readme! I'm still not quite sure what to make of this, after running with `-duration=5s`:

> Duration      [total, attack, wait]    26.126396344s, 4.982672s, 21.143724344s

**Comment by tsenart** [comment]
Hi @jzaefferer! Is the explanation in the comment above clear to you?
