### ISSUE TITLE
Inline post request body in targets file

### ISSUE THREAD

**Issue by mbrookes1304** [tsenart/vegeta#298]
#### Proposal
Currently custom POST bodies are specified by referencing a separate file which contains the body to be sent. Instead it should be possible to specify the POST body in the file alongside the target

#### Background
We are load testing a service by injecting actual requests collected from the logs. Each request has a different body and because we are using 1000s of requests we do not want to have 1000s of files, one for each body.

#### Workarounds
We created a wrapper using the library that would read the list of requests & construct targets before launching the attack.

**Comment by tsenart** [comment]
See #260.
