### ISSUE TITLE
Default -format=json example not working for me

### ISSUE THREAD

**Issue by swilsonian** [tsenart/vegeta#310]
#### Version and Runtime

```
Version: 8.1.0
Commit: e1fcaf58d8313d186bce0b923b38e2fd0002bd6d
Runtime: go1.10.3 darwin/amd64
Date: 2018-07-11T10:36:45Z"
```

#### Expected Behaviour

The default JSON format not working
https://github.com/tsenart/vegeta#-format
When i run it, it should attack http://goku.

#### Actual Behaviour
I get a message that the required method is missing, so it seems unable to parse the provided JSON

vegeta-8.1.0-darwin-amd64 sean$ jq -ncM '{method: "GET", url: "http://goku", body: "Punch!" | @base64, header: {"Content-Type": ["text/plain"]}}' |   ./vegeta attack -format=json -rate=100 | ./vegeta dump
2018/07/12 13:16:19 target: required method is missing

#### Steps to Reproduce

vegeta-8.1.0-darwin-amd64 sean$ jq -ncM '{method: "GET", url: "http://goku", body: "Punch!" | @base64, header: {"Content-Type": ["text/plain"]}}' |   ./vegeta attack -format=json -rate=100 | ./vegeta dump
2018/07/12 13:16:19 target: required method is missing

I also tried using plain echo, got a different error:
[root@h5-services-8869 vegeta]# echo  {"method":"GET", "url":"https://goku", "header":{"Content-Type":["text/plain"]}} | ./vegeta attack -format=json -rate=100
2018/07/12 05:22:56 invalid character 'm' looking for beginning of object key string

Then i added single quotes and got the original error again:
[root@h5-services-8869 vegeta]# echo  '{"method":"GET", "url":"https://goku", "header":{"Content-Type":["text/plain"]}}' | ./vegeta attack -format=json -rate=100
2018/07/12 05:23:20 target: required method is missing

#### Additional Context
I tried on macbook and also centos 7 server, both had the same issue.
jq version is the same on macbook and centos: version 1.5

**Comment by tsenart** [comment]
Hey, thanks for the bug report @swilsonian. This will be fixed in https://github.com/tsenart/vegeta/pull/311/files
