### ISSUE TITLE
mac 上生成的html显示错误

### ISSUE THREAD

**Issue by zhangya4548** [tsenart/vegeta#319]
The version of the brew install vegeta installed on mac: v8.0.0

Analysis command:

`vegeta attack -targets="demo.txt" -rate=500 -duration=5s  > results.bin && cat results.bin | vegeta report -reporter=plot > plot.html`

The error color displayed by html is wrong.

![xnip2018-07-16_18-35-20](https://user-images.githubusercontent.com/8876518/42754419-0464fcf0-8927-11e8-82ae-00547cba8ecf.png)

**Comment by tsenart** [comment]
Hey, please write in English so that I can understand your issue.

**Comment by zhangya4548** [comment]
Translation ok

**Comment by tsenart** [comment]
The error color is not wrong.

**Comment by zhangya4548** [comment]
linux color  ok
[https://dahuzhi.3ddysj.com/yache.html](url)
