### ISSUE TITLE
Add library option to disable saving response bodies

### ISSUE THREAD

**Issue by bluekeyes** [tsenart/vegeta#325]
#### Proposal

Add an option for `Attacker` that does not save the response body into a buffer, but copies it directly to `ioutil.Discard`. I've implemented this in my fork: https://github.com/bluekeyes/vegeta/tree/bluekeyes/discard-body

#### Background

This is similar to #302, but slightly different. I'm using Vegeta as a library to test a download server, with file sizes ranging from 1kb to several GB. While the latest version of the CLI allows me to filter out the body from result files (or I could set the body to `nil` when using the library and processing results), reading large responses quickly uses up available memory during the test. 

For the largest downloads in my test (0.25GB - 4GB), my test containers were running out of memory unpredictably based on the download rate (I tested with up to 8GB of available memory.) Since I don't use the response body for anything, discarding it keeps the memory usage low and allows the large tests to run with the same system resources as tests for smaller files.

#### Workarounds

Running tests on hosts with more memory or distributing the load across more machines can solve this problem, but is wasteful and may be hard to setup.

**Comment by tsenart** [comment]
Thanks for reporting this with such useful context. Out of curiosity, would test your servers with HEAD instead of GET solve the issue? Or do they not handle that method?

**Comment by tsenart** [comment]
Released: https://github.com/tsenart/vegeta/releases/tag/cli/v11.1.0

**Comment by tsenart** [comment]
Feedback welcome :-)

**Comment by bluekeyes** [comment]
Thanks for the quick turnaround on this. I haven't tested it out yet, but looking at the implementation I'm a bit worried that when setting the max body size to 0, the `LimitReader` won't actually read any data from the server, which could lead to weird behavior like the client closing the connection before reading the full body. When I get a chance to try it in my application, I'll update this with the results.
