### ISSUE TITLE
plot command: point with sequence number 5 in timeseries: non monotonically increasing timestamp

### ISSUE THREAD

**Issue by MatrixFrog** [tsenart/vegeta#333]
#### Version and Runtime
built from 23d58764f1258b57058f59490907322c86f2f236. Ubuntu 18.04

#### Expected Behaviour

Ran a few separate tests, `>`ing the results to different files:
```
... | vegeta attack -format=json > results-0.bin
... | vegeta attack -format=json > results-1.bin
```
etc

and then `vegeta report results-*.bin` produces a nice textual report as expected. So `vegeta plot results-*.bin > plot.html` should work too, if I've understood the documentation correctly.

#### Actual Behaviour

The above `vegeta plot` command produces an error: `point with sequence number 5 in timeseries: non monotonically increasing timestamp.`

**Comment by tsenart** [comment]
You need to name each attack for that purpose. Try passing `-name` flag on each attack.

**Comment by tsenart** [comment]
Otherwise vegeta plot wouldn’t be able to partition results from different attacks. What’s happening now is that it’s treating all results as part of the same attack (named “”) which is obviously wrong.

**Comment by MatrixFrog** [comment]
> ... if I've understood the documentation correctly

So, apparently I did not :)

Thanks for the quick response!
