### ISSUE TITLE
Customizable/templatable attack batch requests

### ISSUE THREAD

**Issue by toh2526** [tsenart/vegeta#334]
#### Proposal

Customizable/templatable attack batch requests.

#### Background

Sometimes we have to load test one URL with variety mix of POST body or GET params. Untill all items in the list get consumed.
It could help a lot with template requests + CSV/JSON param lists like what's been done in jMeter.

#### Workarounds

For now? Maybe with parallel command used in here:
https://www.simonholywell.com/post/2015/06/parallel-benchmark-many-urls-with-apachebench/

**Comment by tsenart** [comment]
This is already possible today by writing a small program or script that generates targets on the fly. I had good experiences using ‘jq’ for that purpose.

**Comment by tsenart** [comment]
You need to use the `-lazy` flag in `vegeta attack` together with that script.

**Comment by majkinetor** [comment]
Does this solution works in cross platform manner ?

**Comment by tsenart** [comment]
Not sure if Windows has any sort of pipes. But Windows 10 has a Linux sub-system with Bash so you can use that. https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by majkinetor** [comment]
Yes, windows [has pipes](https://docs.microsoft.com/en-us/windows/desktop/ipc/named-pipes).  PowerShell pipeline can also 'feed' the app [continiously](https://docs.microsoft.com/en-us/previous-versions/technet-magazine/hh413265(v=msdn.10)).

Should I really install linux subsystem for load test ? :) No, not at all.

**Comment by tsenart** [comment]
Great, so feel free to test it!

**Comment by lhauspie** [comment]
> This is already possible today by writing a small program or script that generates targets on the fly. I had good experiences using ‘jq’ for that purpose.

Hi, thanks for this information. But I'm afraid it's not enough for me to begin.

Do you have an example of script to do that ?
Very interested by this feature.

Thanks in advance.

**Comment by tsenart** [comment]
@lhauspie: `vegeta attack` can consume targets that are generated on the fly by specifying the `-lazy` flag. Then any program can produce those targets and write them to a file or pipe that `vegeta attack` takes in.

```sh
./your_target_generating_program.sh | vegeta attack -lazy ...
```

You can produce those targets in [the JSON format](https://github.com/tsenart/vegeta#json-format) which is much easier to work with than the HTTP format.
