### ISSUE TITLE
Ordered Sequence Question

### ISSUE THREAD

**Issue by tateexon** [tsenart/vegeta#342]
#### Question
Does vegeta support an ordered sequence in a load test? For example I have 3 requests that need to be made in a very specific order (1 must finish before 2 begins, 2 must finish before 3 begins). I have a need to load test this sequence of calls but am not seeing a way to do it currently or maybe do not know what the terminology would be to look for. Any help in answering this is greatly appreciated!

**Comment by tsenart** [comment]
Vegeta was designed originally for testing HTTP APIs without any concept of a user session or flow. Is this what you're trying to do?

**Comment by tateexon** [comment]
Ah, yes that would be what I am trying to do. Guess it won't work for what I am trying to do. Thanks for the quick reply!

**Comment by tsenart** [comment]
Take a look at https://k6.io
