### ISSUE TITLE
Workers count hard limit - currently workers leak on slow target

### ISSUE THREAD

**Issue by misiek08** [tsenart/vegeta#344]
#### Proposal
Introduce new setting (like -workers-hard-limit true/false, default: false) to prevent workers from leaking

#### Background
When targets is slowing down, worker are spawned without any limits and this can lead to consuming all system memory and finally - crash vegeta.
It is caused by this code: https://github.com/tsenart/vegeta/blob/master/lib/attack.go#L255
Probably this is expected behavior, but when one is trying to check what target limits are - it causes everything to explode.

#### Workarounds
You have to specify rate below target capabilities, so if you over estimate this value you have to stop test, change rate and run it again.

**Comment by tsenart** [comment]
This is by design, to prevent coordinated omition and to sustain the desired request rate.

http://highscalability.com/blog/2015/10/5/your-load-generator-is-probably-lying-to-you-take-the-red-pi.html

**Comment by tsenart** [comment]
You can run vegeta from a more capable machine and fine tune system resource limits to alleviate the issue.

**Comment by tsenart** [comment]
Also, vegeta isn’t so much a benchmarking tool to hammer a system to it’s limits. It’s a load test tool to understand your system behavior at different load points.

**Comment by misiek08** [comment]
According to bigger machine - I run tests on servers with 64G RAM and it can be eaten in 30-40 seconds sometimes :)

Ok, if the behavior is by design then no need to introduce this new option.

**Comment by tsenart** [comment]
FYI: Latest vegeta version has a `-max-workers` option to be able to replicate results from other load testing tools with controlled concurrency at the expense of potentially introducing coordinated omission (but that's not the default).
