### ISSUE TITLE
Support reporting while piping

### ISSUE THREAD

**Issue by fenollp** [tsenart/vegeta#345]
#### Proposal

Add a flag to `vegeta report` that displays some information while binary data is piped to its STDIN.

#### Background

My current `vegeta` calls look like this:
```
vegeta attack -rate 1 -header 'Authorization: Bearer ...' -targets ~/bouillotte -insecure -duration 20m |pv -rt |vegeta report
```
Where `pv` acts as a time & volume indicator.

I'd rather not wait for the whole attack to finish before having some information which look like it could be parsed & displayed as the attack is running. (But then I may be wrong!)

#### Workarounds

The `pv` trick works fine but doesn't show anything that `vegeta report` shows: only `0:06:13 [34.6KiB/s]`

There's also https://github.com/tsenart/vegeta/issues/299 & the two are not incompatible: `vegeta attack` could detect if it is being piped.

**Comment by tsenart** [comment]
Good one. I can see two options and I'd like your take on what you think of each:

1. Screen redrawing ala ncurses, enabled via a flag.
2. CTRL-D to print current status to the screen.

**Comment by tsenart** [comment]
Released!
