### ISSUE TITLE
Combine results

### ISSUE THREAD

**Issue by tiagoliveira9** [tsenart/vegeta#348]
#### Question
I want to make a plot with several results, how can I do that?

Thanks

**Comment by tiagoliveira9** [comment]
that option does not exist but I found the solution:

vegeta plot results.bin results2.bin > plot.html
Thanks for the great work on Vegeta!

**Comment by tsenart** [comment]
The help flag doesn’t exist? That’s a problem. Can you share the details of your version and OS?

**Comment by tiagoliveira9** [comment]
I'm on Fedora 28, 4.18.16-200.fc28.x86_64. I've downloaded the binary vegeta-12.1.0-linux-amd64.tar.gz .

**Comment by tsenart** [comment]
And what’s the output of `vegeta report -h`

**Comment by tiagoliveira9** [comment]
`Usage: vegeta report [options] [<file>...]

Outputs a report of attack results.

Arguments:
  <file>  A file with vegeta attack results encoded with one of
          the supported encodings (gob | json | csv) [default: stdin]

Options:
  --type    Which report type to generate (text | json | hist[buckets]).
            [default: text]

  --every   Write the report to --output at every given interval (e.g 100ms)
            The default of 0 means the report will only be written after
            all results have been processed. [default: 0]

  --output  Output file [default: stdout]

Examples:
  echo "GET http://:80" | vegeta attack -rate=10/s > results.gob
  echo "GET http://:80" | vegeta attack -rate=100/s | vegeta encode > results.json
  vegeta report results.*

`

**Comment by tsenart** [comment]
Sorry, I meant: `vegeta plot -h`

**Comment by tiagoliveira9** [comment]
`Usage: vegeta plot [options] [<file>...]

Outputs an HTML time series plot of request latencies over time.
The X axis represents elapsed time in seconds from the beginning
of the earliest attack in all input files. The Y axis represents
request latency in milliseconds.

Click and drag to select a region to zoom into. Double click to zoom out.
Choose a different number on the bottom left corner input field
to change the moving average window size (in data points).

Arguments:
  <file>  A file with vegeta attack results encoded with one of
          the supported encodings (gob | json | csv) [default: stdin]

Options:
  --title      Title and header of the resulting HTML page.
               [default: Vegeta Plot]
  --threshold  Threshold of data points to downsample series to.
               Series with less than --threshold number of data
               points are not downsampled. [default: 4000]

Examples:
  echo "GET http://:80" | vegeta attack -name=50qps -rate=50 -duration=5s > results.50qps.bin
  cat results.50qps.bin | vegeta plot > plot.50qps.html
  echo "GET http://:80" | vegeta attack -name=100qps -rate=100 -duration=5s > results.100qps.bin
  vegeta plot results.50qps.bin results.100qps.bin > plot.html`

**Comment by tiagoliveira9** [comment]
I'm doing this "vegeta plot results2.bin results3.bin > plot2.html" and it's working okay for me. I don't understand the point of having the flag "h", what is supposed to do?

**Comment by tsenart** [comment]
Protip: You can three backticks for multiline blocks of code.

So, regarding the output of `vegeta plot -h`, there you go, that's what I wanted you to see when I wrote my first reply [here](https://github.com/tsenart/vegeta/issues/348#issuecomment-432794887).

It is the user manual. `-h` stands for `help`. So you can call `-h` on any command to learn how to use ii!

**Comment by tsenart** [comment]
Estou em modo didático, Tiago :-)

**Comment by tsenart** [comment]
De nada.
