### ISSUE TITLE
How to do multiple (chain) request?

### ISSUE THREAD

**Issue by ajiyakin** [tsenart/vegeta#349]
#### Question

So I need to do multiple request (chaining) in one scenario. For example, I need to log-in the user and then get list of items and then buy the items. What is the best way to do that in vegeta? Currently I'm using this template to do that:

```go
userLoginTargeter := ...........................
rate := vegeta.Rate{Freq: 1, Per: time.Second}
for response := range attacker.Attack(userLoginTargeter, rate, time.Second, "User Login")
   var token token.Response
   json.Unmarshal(response.Body, &tokenResponse)

   itemListTargeter := ..................
   resItemList := <-attacker.Attack(itemListTargeter, vegeta.Rate{Freq: 1, Per: time.Millisecond}, time.Millisecond, "Get Item List")
   var items []item.Response
   json.Unmarshal(resItemList.Body, &items)

   createOrderTargeter := ..................
   resCreateOrder := <-attacker.Attack(createOrderTargeter, vegeta.Rate{Freq: 1, Per: time.Millisecond}, time.Millisecond, "Create Order")

   results.Add(resCreateOrder)
}
```

**Comment by tsenart** [comment]
Vegeta wasn't designed with user sessions in mind, so this is not easy to do. I suppose what you're trying could work, but have you considered load testing one endpoint at a time, separately?

**Comment by ajiyakin** [comment]
I see. I have done it, doing load test per-endpoint. I just want to try to simulate what user do in real world scenario with vegeta if possible.
Thanks @tsenart

**Comment by ajiyakin** [comment]
Looks really cool. Going to try it :+1:

**Comment by thinkerou** [comment]
interesting...

**Comment by thinkerou** [comment]
> I see. I have done it, doing load test per-endpoint. I just want to try to simulate what user do in real world scenario with vegeta if possible, so I can replace Gatling with vegeta completely since Gatling needs a lot of memory to run.
> Thanks @tsenart

@ajiyakin still use Gatling? thanks! I want to solve the issue.

**Comment by fai555** [comment]
@theikalman Which tools would you recommend? Is vegeta good for simulating complex transactions?
