### ISSUE TITLE
Plot throughput

### ISSUE THREAD

**Issue by zommerfelds** [tsenart/vegeta#354]
#### Proposal

It would be nice if Vegeta would support plotting of the throughput by HTTP code instead of just latencies. 
Maybe `vegeta plot -throughput`. Or even two plots in the same `HTML` file, like the screenshot below.

#### Background

This would be interesting to show how a system behaves under overload. A low latency is not necessarily good if no successes are going through. It's nice to see what errors codes are returned at what time.

#### Workarounds

You can use the report tool to get an average success metric. Or you can use https://github.com/tsenart/vegeta#usage-real-time-analysis to get some kind of real time usage.

---

As an example, here is how [Artillery](https://github.com/shoreditch-ops/artillery) plots a report:
![image](https://user-images.githubusercontent.com/1260622/48587930-07cf4d00-e903-11e8-8430-80c3aecb226d.png).
Vegeta performs so much better though, so I would love to use it instead. :) Thanks for the great tool.

**Comment by tsenart** [comment]
Vegeta maintains a fairly constant request rate, and hence, throughput, so I'm not sure what this would show you.

**Comment by zommerfelds** [comment]
Hi, thanks for the answer. What I meant is that you could show how many responses where a 200 vs a 504 or 503 at each point in time, for example. I found that to be very helpful for analysis of what is happening.

**Comment by tsenart** [comment]
You can graph Vegeta results easily with any third party tool via the `vegeta encode` command. I don't have the bandwidth to extend vegeta to cover this use case now.
