### ISSUE TITLE
How to test multiple URLs?

### ISSUE THREAD

**Issue by wizurijyq** [tsenart/vegeta#360]
Is there a way to load urls from a file?

**Comment by tsenart** [comment]
Please read the documentation.

Sent via Superhuman iOS ( https://sprh.mn/?vip=tsenart@gmail.com )

**Comment by wizurijyq** [comment]
I only see that I could echo a single URL to vegeta. Is there a way to load multiple URLs at once?

**Comment by wizurijyq** [comment]
Oh I see it an example would have been great! thanks you!
