### ISSUE TITLE
-bash: /usr/local/bin/vegeta: cannot execute binary file

### ISSUE THREAD

**Issue by asen477** [tsenart/vegeta#361]
How to solve this problem when running on linux?

**Comment by tsenart** [comment]
You probably didn't `chmod +x /usr/local/bin/vegeta`. If that's not the case, please don't bypass the issue templates I have setup. They are meant to help diagnose issues from the beginning without all the conversational back and forth.

https://github.com/tsenart/vegeta/issues/new?template=bug_report.md
