### ISSUE TITLE
could we provide some examples for operating with docker image and container?

### ISSUE THREAD

**Issue by chuanchang** [tsenart/vegeta#364]
#### Question
As subject, for example, how to pull an image and create a container by vegeta?  thanks in advance!

https://docs.docker.com/engine/api/v1.24/
https://success.docker.com/article/how-do-i-enable-the-remote-api-for-dockerd

**Comment by tsenart** [comment]
There are multiple published vegeta Docker images in Docker hub that you can look into or reuse: https://hub.docker.com/search?q=vegeta&type=image

**Comment by chuanchang** [comment]
> There are multiple published vegeta Docker images in Docker hub that you can look into or reuse: https://hub.docker.com/search?q=vegeta&type=image

@tsenart Have new year! thanks for quickly reply,  I need to clarify it, I don't want a docker image for vegeta, I wanna some vegeta's examples to test docker by docker remote API, for instance, How to pull an busybox image concurrently via docker remote API  by vegeta? and then how to create multi-container concurrently via docker remote API by vegeta? thanks a lot!

**Comment by tsenart** [comment]
Hey, sorry, but I don't think I can help you with that.
