### ISSUE TITLE
following example in readme about integrate with jplot does not work

### ISSUE THREAD

**Issue by victor61zhong** [tsenart/vegeta#369]
can anyone give me a workable example ?

ip-192-168-1-42:vegeta victor$ vegeta attack -targets="test.txt" -rate=10 -duration=2m | vegeta dump| jaggr @count=rps hist[100,200,300,400,500]:code p25, p50, p95:latency sum:bytes_in sum:bytes_out|jplot rps+code.hist.100+code.hist.200+code.hist.300+code.hist.400+code.hist.500 latency.p95+latency.p50+latency.p25 bytes_in.sum+bytes_out.sum
2019/01/17 14:07:29 vegeta dump has been deprecated and succeeded by the vegeta encode command
jplot:  Data source error:  input error: invalid character 'j' looking for beginning of value
ip-192-168-1-42:vegeta victor$ vegeta attack -targets="test.txt" -rate=10 -duration=2m | vegeta encode| jaggr @count=rps hist[100,200,300,400,500]:code p25, p50, p95:latency sum:bytes_in sum:bytes_out|jplot rps+code.hist.100+code.hist.200+code.hist.300+code.hist.400+code.hist.500 latency.p95+latency.p50+latency.p25 bytes_in.sum+bytes_out.sum
jplot:  Data source error:  input error: invalid character 'j' looking for beginning of value

this is what happened on my machine. 

If I use the example on readme, I can see the picture, but there is no out put, I mean there is no data.

thanks.

**Comment by tsenart** [comment]
The needle in the haystack: `2019/01/17 14:07:29 vegeta dump has been deprecated and succeeded by the vegeta encode command`

Just replace `dump` with `encode`. I'll update the README.

**Comment by tsenart** [comment]
Well, actually, the README is already up to date. Where did you get that example from?
