### ISSUE TITLE
Provide go templating for targets in order to randomise contents

### ISSUE THREAD

**Issue by Overbryd** [tsenart/vegeta#370]
#### Proposal

Next to the round-robin target selection, vegeta could benefit from iterating over a set of given targets that are stored as a template.
So that a user could provide a number of endpoints, but vegeta would randomize the params according to simple rules.

It would be a compromise to using vegeta as a library versus using vegeta from the command line without knowing any Go.

##### Example:

```
GET https://example.com/get?page={{ seq 10 | shuffle | first 1 }}
```

#### Background

Some users may be able to resort to using vegeta as a library, while others just need to provide a random selection to a range of values to vegeta targets.

I am proposing this for the users who need the latter. A simple mechanism like go templating could cater 80% of the needs for parameter randomisation.

#### Workarounds

The only known workaround I know is to create an absurdly high number of targets before starting the test.

Or use vegeta as a library, but that is far from my reach. Working on it.

**Comment by majkinetor** [comment]
Without templates any load testing tool is limited. You may try superbenchmarker which can accept request details from CSV or library.

**Comment by Overbryd** [comment]
I actually found an already supported way of doing this.
I kind of overlooked the `-lazy` flag, that does read the targets from a given STDIN lazily.

And UNIX-pipes will do their thing just fine.
I whipped up a small helper script, that runs some Python (anything goes here actually) and constantly outputs targets from a given jinja2 template.

Due to the nature of UNIX-pipes, any writes beyond the pipe buffer size will block. So they are backpressure aware.
And every request vegeta does will use one newly generated target from STDIN.

#### Example

**generate.py**:

```python
#!/usr/bin/env python
import sys
import jinja2
from uuid import uuid4

loader = jinja2.FileSystemLoader("./")
env = jinja2.Environment(autoescape=True, loader=loader)

def uuid_filter(rnd):
    return uuid4()

env.filters['uuid'] = uuid_filter

tmpl = env.get_template(sys.argv[1])

while True:
    try:
        print tmpl.render()
        print
    except IOError:
        sys.exit()
    except KeyboardInterrupt:
        sys.exit()
```

**request.tmpl**:

```
GET https://example.com/?random={{range(0, 10) | random}}
```

**Usage*

```console
$ ./generate.py request.tmpl | vegeta attack -lazy -duration=60s -rate=10 | vegeta report --every=1s
```

Hope this helps somebody stumbling over this issue.
I will leave the issue open, as I think this should go into the README documentation, and the feature request is still up for discussion.

**Comment by tsenart** [comment]
Please take a look: https://github.com/tsenart/vegeta/pull/373
