### ISSUE TITLE
-format=json example in README does not work

### ISSUE THREAD

**Issue by mgartner** [tsenart/vegeta#381]
The example in the README for using `-format=json` does not work. https://github.com/tsenart/vegeta#json-format

```
jq -ncM '{method: "GET", url: "http://goku", body: "Punch!" | @base64, header: {"Content-Type": ["text/plain"]}}' |
  vegeta attack -format=json -rate=100 | vegeta encode
```

The body is not correctly sent to the server. Vegeta should be un-base64-encoding the string and passing to the server. It appears that it is sending nothing to the server in the body.

It's also weird that the body needs to be base64 encoded. It would be nice if that extra ceremony were not necessary.

**Comment by tsenart** [comment]
Please open a [Bug Report](https://github.com/tsenart/vegeta/issues/new?template=bug_report.md)
