### ISSUE TITLE
Support Unix socket HTTP endpoints (per curl) 

### ISSUE THREAD

**Issue by zootalures** [tsenart/vegeta#387]
#### Proposal

Some services (e.g. Docker) use Unix sockets to front HTTP traffic  - I'd like to support making Vegeta call these services for load testing per curl (--unix-socket /path/to/socket) 

#### Background

I'm already using vegeta for other load testing and benchmarking for straight HTTP and HTTP/2 services - and wasn't able to find a decent tester that supports  HTTP/1.1 over unix sockets. 

#### Workarounds
Nothing simple beyond putting an Nginx in front of the socket

**Comment by tsenart** [comment]
Released in https://github.com/tsenart/vegeta/releases/tag/cli%2Fv12.3.0
