### ISSUE TITLE
Plot not starting at t=0 when there are error responses

### ISSUE THREAD

**Issue by mightyguava** [tsenart/vegeta#391]
#### Version and Runtime

v12.3.0@7bf09f4fab4d852141935796455c17459d212098

#### Expected Behaviour

`vegeta plot` creates a graph at t=0

#### Actual Behaviour

`vegeta plot` created a graph starting at t=892

![vegeta-plot (2)](https://user-images.githubusercontent.com/2769275/56372155-76734800-61cc-11e9-9619-36d92eb23e34.png)
[exp-009-read.html.zip](https://github.com/tsenart/vegeta/files/3095089/exp-009-read.html.zip)

#### Steps to Reproduce

I used vegeta as a library in my load test, against DynamoDB, to test what happens when requests go over the provisioned capacity. My requests started getting throttled at around the 15 minute mark, which is exactly where the plot starts. I'm guessing a bug in plotting specifically.

Unfortunately I can't share the repo, but the setup I think is pretty standard:

```go
func main() {
	rate := vegeta.Rate{Freq: flags.RPS, Per: time.Second}
	duration := flags.Duration
	sess := session.Must(session.NewSession(&aws.Config{
		Region: &flags.AWSRegion,
	}))
	svc := dynamodb.New(sess)
	attacker := vegeta.NewAttacker()

	var res <-chan *vegeta.Result
	switch flags.Op {
	case "write":
		targeter := loadtest.DynamoWriteTargeter(svc, flags.TableName)
		res = attacker.Attack(targeter, rate, duration, "PutItem")
	case "read":
		targeter, err := loadtest.DynamoReadTargeter(svc, flags.TableName, flags.ReadSetSize)
		if err != nil {
			return errors.Wrapf(err, "failed to create read targeter")
		}
		res = attacker.Attack(targeter, rate, duration, "GetItem")
	default:
		logrus.Fatalf("invalid op %s", flags.Op)
	}
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt)

	var out io.WriteCloser
	out, err := file(flags.Out, true)
	if err != nil {
		return err
	}
	defer out.Close()
	if strings.HasSuffix(flags.Out, ".gz") {
		out = gzip.NewWriter(out)
		defer out.Close()
	}
	enc := vegeta.NewEncoder(out)

encodeLoop:
	for {
		select {
		case <-sig:
			attacker.Stop()
			return nil
		case r, ok := <-res:
			if !ok {
				break encodeLoop
			}
			if err := enc.Encode(r); err != nil {
				return err
			}
		}
	}
}
```

**Comment by tsenart** [comment]
Would you be able to store your results in a file with the response body and other sensitive data elided? Sharing that with me would really help debugging.

**Comment by mightyguava** [comment]
Sure, here's the results gzipped in gob format. https://s3-us-west-2.amazonaws.com/yunchi-dynamodb-test/exp-009-stripped.bin.gz
