### ISSUE TITLE
Treat timeouts as errors

### ISSUE THREAD

**Issue by mb720** [tsenart/vegeta#402]
#### Question
Hi and thanks a lot for vegeta!

I'm testing my locally running server using

    vegeta attack -targets targets.txt -timeout=6s -duration=5m > results.bin

When I create the metrics with

    vegeta report -type=json results.bin > metrics.json

I can see in `metrics.json` that an image did not load in time:

>Get http://localhost:8080/myImg.jpg: net/http: timeout awaiting response headers

But when creating an HTML plot with

    cat results.bin | vegeta plot > plot.htm

those errors are not displayed, making it seem that the test completed all requests successfully.

Is there a way to make those errors stand out?

**Comment by tsenart** [comment]
Would you be able to provide me with your `results.bin` for debugging please?

**Comment by mb720** [comment]
Thanks for looking into it. [Here's](https://mega.nz/#!XtJXHSrA!FrvGu-U65NqfVG92nvQqXTMNVjUlA8CpVm5xdrEtjk8) the `results.bin` containing a couple of reported timeouts.

**Comment by tsenart** [comment]
Fix released: https://github.com/tsenart/vegeta/releases/tag/cli%2Fv12.5.1
