### ISSUE TITLE
Shows weird character output on `attack` command

### ISSUE THREAD

**Issue by uudashr** [tsenart/vegeta#405]
#### Version and Runtime

Version: cli/v12.5.1
Commit: 0f5577eaf11a136541b8c667273b6bc5eba51a8b
Runtime: go1.12.5 darwin/amd64
Date: 2019-05-13T06:43:04Z+0100

#### Expected Behaviour

Should no weird characters

#### Actual Behaviour

https://asciinema.org/a/Tzyja3hwL75PBr2fnAVR5kdJd

#### Steps to Reproduce

1. Exec this on terminal `echo GET http://localhost:8000 | vegeta attack -duration=5s -rate=5`

**Comment by tsenart** [comment]
You need to pipe the binary output to a file or vegeta report, for instance.

Sent via Superhuman iOS ( https://sprh.mn/?vip=tsenart@gmail.com )

**Comment by uudashr** [comment]
Cool.. Thanks
