### ISSUE TITLE
How to generate results.bin from code?

### ISSUE THREAD

**Issue by michael-iglesias** [tsenart/vegeta#407]
#### Question
How do I generate a `results.bin` file from Go. I'm trying to create a report and corresponding plot but I continue to receive the following error (`encode: can't detect encoding of "results.bin"`) when using both of the files I'm creating (below). Any ideas would be much appreciated! :)

```
fmt.Printf("aggregateMetrics: %v\n\n", aggregateMetrics.Requests)
file, _ := json.MarshalIndent(aggregateMetrics, "", " ")
_ = ioutil.WriteFile("results.json", file, 0644)

dataFile, err := os.Create("results.bin")
if err != nil {
     log.Fatalf("Could not create results.bin %s", err)
}
dataEncoder := gob.NewEncoder(dataFile)
dataEncoder.Encode(aggregateMetrics)
dataFile.Close()
```

**Comment by tsenart** [comment]
Take a look at how the `vegeta attack` command does it: https://github.com/tsenart/vegeta/blob/master/attack.go#L180

**Comment by michael-iglesias** [comment]
Got everything working by referencing how `vegeta attach` does it. Thanks!

**Comment by nimrodshn** [comment]
@tsenart its still not clear to me how to `plot` as I'm seeing consistently `encode: can't detect encoding of "..."` when running the `plot` command, any suggestions?
