### ISSUE TITLE
Attack Vegeta shows set error

### ISSUE THREAD

**Issue by majdisaadani** [tsenart/vegeta#410]
#### Question

Hi All,
I tried to use Vegeta to test an end point in our system, but unfortunately,i get an error:

My cmd : 
vegeta attack -rate=10 -duration=5s -targets=targets.txt | vegeta report

My target file look like this : 
POST https://xxxxxxxxxx
Content-Type: application/x.xxx-event+json
@/Users/majdi.saadani/Documents/Commande/event_v1.json
  
and My event_v1.json:
{
   "version":"v000",
   "created_ts":"2019-06-07T15:54:20.723Z",
   "category":"xxx",
   "attributes":{
      "event":{
         "id":"xx-xx-xx-xx-xx",
         "name":""
      }
   }
}

My error : 

Requests      [total, rate]            50, 10.21
Duration      [total, attack, wait]    4.91182373s, 4.898947142s, 12.876588ms
Latencies     [mean, 50, 95, 99, max]  16.510991ms, 11.647052ms, 13.69748ms, 181.919699ms, 181.919699ms
Bytes In      [total, mean]            0, 0.00
Bytes Out     [total, mean]            10200, 204.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             201:50  
Error Set:

Thank you for help

**Comment by tsenart** [comment]
That’s not an error. That’s the report output.
