### ISSUE TITLE
onion website

### ISSUE THREAD

**Issue by lucmski** [tsenart/vegeta#411]
Hi guys,

Would it possible to test onion website with vegeta ? with slow requests or fast

Cheers,

**Comment by tsenart** [comment]
Vegeta only speaks HTTP. If you can reach your Onion website via an HTTP proxy, then yes.

**Comment by anpic** [comment]
> If you can reach your Onion website via an HTTP proxy, then yes

but `vegeta` doesn't know how to work with `tor` even through its http proxy
