### ISSUE TITLE
Support for attacking a set of interfaces

### ISSUE THREAD

**Issue by sanxun0325** [tsenart/vegeta#415]
#### Question
For the set of interfaces I want to attack, I call the user login interface first and call the next interface by returning value.
Finally, I want to count the reports that attack this group of interfaces. Is there any good method？

I don't want to attack interfaces separately，because I want to test the user login and query interface can withstand the pressure
![image](https://user-images.githubusercontent.com/28588342/60379820-3b16b480-9a6c-11e9-8922-26c6114af927.png)

**Comment by sanxun0325** [comment]
@tsenart

**Comment by sanxun0325** [comment]
@fxkr You can help me?

**Comment by tsenart** [comment]
Vegeta was built to test individual HTTP endpoints separately. Take a look at https://k6.io/
