### ISSUE TITLE
Support HTTP CONNECT proxy headers

### ISSUE THREAD

**Issue by SalmaanP** [tsenart/vegeta#416]
#### Question

I see there is a way to make plain HTTP requests, just wondering if its possible to make HTTP CONNECT requests? So the client would specify HTTP CONNECT in the plain request with some extra headers optionally, the proxy would reply with `HTTP 200 OK Connection Established`. SSL handshake starts with the client sending client hello. If someone has tried this already, is there an example? Thanks!

**Comment by tsenart** [comment]
Have you tried it?

**Comment by SalmaanP** [comment]
Yes, I tried it out with setting the `HTTPS_PROXY` environment variable set, and it works as expected. The only thing I can figure out is how to send CONNECT headers. In curl you can specify it using `--proxy-headers`. I can see that the CONNECT request already has `User-Agent: Go-http-client/1.1` added so it might be just adding a conf?

**Comment by tsenart** [comment]
Gotcha. It seems like we'd have to implement another `AttackerOpt` that sets `ProxyConnectHeader` in https://golang.org/pkg/net/http/#Transport, and expose that as `vegeta attack` flag (e.g. `-proxy-header`).

**Comment by SalmaanP** [comment]
I'm gonna try and pick this up this week.
