### ISSUE TITLE
connection error: COMPRESSION_ERROR

### ISSUE THREAD

**Issue by justancoder** [tsenart/vegeta#419]
When I am sending traffic from Vegeta to my application, I am getting an error 
**connection error: COMPRESSION_ERROR**
at every alternate message.
I also saw the Wireshark capture but in that Vegeta is closing the connection before even receiving the last data packet from the server
Can you explain why it is happening?

**Comment by tsenart** [comment]
Please file a bug report so I can have enough information to debug: https://github.com/tsenart/vegeta/issues/new?template=bug_report.md
