### ISSUE TITLE
Latency unit measure when report -type=json

### ISSUE THREAD

**Issue by barbabjetolov** [tsenart/vegeta#422]
The unit measure for latencies when `report -type=json` is unclear. It doesn't look like being ms, since the example in the README shows an average latency of 2371194: if we assume it's in ms, it'd correspond to ≈ 0.66h.

**Comment by tsenart** [comment]
It’s nanoseconds!

Sent via Superhuman iOS ( https://sprh.mn/?vip=tsenart@gmail.com )
