### ISSUE TITLE
Headers are being rearranged, which breaks digital signature checks

### ISSUE THREAD

**Issue by 0xhaggis** [tsenart/vegeta#424]
#### Version and Runtime

```
Version: 12.7.0
Commit: 9c95632b3e8562be6df690c639a3f5a6f40d3004
Runtime: go1.12.4 darwin/amd64
Date: 2019-07-21T12:38:16Z
```

#### Expected Behaviour

When running Vegeta using custom headers and body I expected Vegeta to honor the order in which the headers were supplied and to avoid manipulating headers like "Content-length". These MUST be kept EXACTLY as they are in my payload files because they contain cryptographic hashes of the headers/body. If the headers change (
or the order in which the headers appear changes), the hashes no longer match the headers/body and the server will refuse to accept my requests.

#### Actual Behaviour

Vegeta re-ordered the headers (moved Content-length from last header to 3rd header for example, and it also randomly re-orders other headers) and it altered the Content-length. As a result the server rejects my payload because the cryptographic hashes no longer match.

#### Steps to Reproduce

Run Vegeta against a server that verifies cryptographically hashed HTTP headers/bodies.

**Comment by 0xhaggis** [comment]
Is there an option to tell Vegeta to pass headers/body verbatim instead of processing/re-ordering them?

**Comment by tsenart** [comment]
> Is there an option to tell Vegeta to pass headers/body verbatim instead of processing/re-ordering them?

No, I don't think this is possible. In fact, per [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html):

> The order in which header fields with differing field names are received **is not significant**. However, it is "good practice" to send general-header fields first, followed by request-header or response- header fields, and ending with the entity-header fields.
