### ISSUE TITLE
How to use dynamic request parameter when attacking/test a service every time?

### ISSUE THREAD

**Issue by fengnex** [tsenart/vegeta#428]
#### Question
We want to use different input parameter whenever invoking a new request to a URL with parameters in the url through vegeta, how to implement that?

**Comment by fengnex** [comment]
for example in the following test:
echo "GET http://localhost/?p1=123&p2=abc" | vegeta attack -duration=5s | tee results.bin | vegeta report

if we need use different values for p1 & p2 for every test request, how to do to achieve that?

**Comment by fengnex** [comment]
Got the following error when using jq, what's jq? Is anything in the context?
jq -ncM 'while(true; .+1) | {method: "POST", url: "http://:6060", body: {id: .} | @base64 }'
jq: Unknown option -ncM
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq

**Comment by fengnex** [comment]
Have addressed the problem, it's due to the wrong version of jq

**Comment by fengnex** [comment]
Another question:
For any GET and POST request, if we want it has dynamic parameter, the document said that we can use the option "-target", but what could the content of target file be? Are there any example? thx

**Comment by fengnex** [comment]
how to read parameters from a file and then randomly fetch one line as parameter in jq?

**Comment by fengnex** [comment]
jq -ncM 'while(true; .+1) 

in the above while loop, hot to set the initial value for the loop when there is certain business requirement related to it?

**Comment by tsenart** [comment]
I lost track of what your current problem is. Can you reformulate and summarise so I can help?

**Comment by fengnex** [comment]
@tsenart Thanks a lot for your kind concern!
I have addressed all the mentioned questions. For the last one, we can initiate a value instead of 1 in the following way:
jq -ncM '18 | while(. < 28; . + 1)|{method: "POST", url: "http://:6060", body: {id: .} | @json }'

Now my new question is: if we need to read dynamic parameters from a static file and then generate one target (url) for each line, how to use jq to implement it?

Would you be so kind as to provide one or several examples? Thank you very much! @tsenart

**Comment by tsenart** [comment]
When you get to those use cases, I recommend you write your own script / program that generates targets.

This old blog post goes into detail on how to do that: https://web.archive.org/web/20180304073213/https://thisdata.com/blog/load-testing-api-interfaces-with-go-and-vegeta/

At that time, JSON target format didn't exist yet, so these days you should use that because it's much easier to generate.

**Comment by fengnex** [comment]
Sadly found that both cannot be opened:
I cannot successfully open  https://web.archive.org/web/20180304073213/ 

Not Found  ---- https://thisdata.com/blog/load-testing-api-interfaces-with-go-and-vegeta/
The requested URL /blog/load-testing-api-interfaces-with-go-and-vegeta/ was not found on this server.

Apache/2.2.15 (CentOS) Server at blog Port 80

**Comment by tsenart** [comment]
The URL is exactly what I wrote above, not two separate URLs: https://web.archive.org/web/20180304073213/https://thisdata.com/blog/load-testing-api-interfaces-with-go-and-vegeta/
