### ISSUE TITLE
Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [tsenart/vegeta#429]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Also might be related to https://github.com/tsenart/vegeta/issues/140

Cheers,
Yevgeny

**Comment by tsenart** [comment]
@yevgenypats: This is a welcome proposal. Thank you for offering to work on it. I'd be glad to receive such a contribution!

**Comment by yevgenypats** [comment]
@tsenart Sounds good. I'll probably will have some questions while trying to identify the interesting places to fuzz and write the fuzzers. 

Also, I need to mention that we have a [reward program](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.

**Comment by tsenart** [comment]
> I'll probably will have some questions while trying to identify the interesting places to fuzz and write the fuzzers.

I'll do my best to answer those questions promptly.

> Also, I need to mention that we have a reward program in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.

Time is limited currently, so I'd accept your contribution gladly.
