### ISSUE TITLE
How to config the body file

### ISSUE THREAD

**Issue by alsmn** [tsenart/vegeta#430]
**version: 12.7.0**

**the method 1 does not work:**
vegeta -profile cpu attack  -targets="/home/vegeta-test/config/post1.txt" -rate=10 -duration=2s -output="/home/aaa.log" vegeta -profile cpu attack -body="/home/vegeta-test/config/post1.json" 
**cat /home/vegeta-test/config/post1.txt**
POST https://www.xxx.com/getUserInfoForPhone
Content-Type:application/x-www-form-urlencode;charset=utf-8
**cat /home/vegeta-test/config/post1.json**
phone=123456

**the method 2 does not work:**
vegeta -profile cpu attack  -targets="/home/vegeta-test/config/post1.txt" -rate=10 -duration=2s -output="/home/aaa.log" vegeta -profile cpu attack  
**cat /home/vegeta-test/config/post1.txt**
POST https://www.xxx.com/getUserInfoForPhone
Content-Type:application/x-www-form-urlencode;charset=utf-8
@/home/vegeta-test/config/post1.json
**cat /home/vegeta-test/config/post1.json**
phone=123456

**only the method 3 works:**
vegeta -profile cpu attack  -targets="/home/vegeta-test/config/post1.txt" -rate=10 -duration=2s -output="/home/aaa.log" vegeta -profile cpu attack  
**cat /home/vegeta-test/config/post1.txt**
POST https://www.xxx.com/getUserInfoForPhone?phone=123456
Content-Type:application/x-www-form-urlencode;charset=utf-8

How to config the body file? Or how to make method 1 and moethod 2 work？

I appreciate any help.

**Comment by tsenart** [comment]
Please submit a [Bug Report](https://github.com/tsenart/vegeta/issues/new?template=bug_report.md)
