### ISSUE TITLE
Can I ask how to ensure a fixed number of attack requests according to the specified rate in implementation?

### ISSUE THREAD

**Issue by fengnex** [tsenart/vegeta#433]
#### Question
This is a question on how to implement fixed RATE attack.
When specifying a rate, for example 100, which means that vegeta needs to ensure that there will be 100 requests sent to the objective http service.
My question is how to use Go code to implement the feature? Having briefly scanned the code, but still want to know about that. Thanks a lot first.

**Comment by tsenart** [comment]
If you want to send only 100 requests, then you can specify `-rate=100/s` and `-duration=1s`.

**Comment by fengme** [comment]
Could you please explain about relevent go code pieces that implement the feature you mentioned above?@tsenart
Thank you very much

**Comment by tsenart** [comment]
Are you interested in the implementation? Well, look at this code sample and then drill down: https://github.com/tsenart/vegeta#usage-library
