### ISSUE TITLE
jq does not work when using combined with psh, how to fix it?

### ISSUE THREAD

**Issue by fengnex** [tsenart/vegeta#435]
#### Question
pssh -h host_ip.txt -i -t 100000 -P "jq -ncM '18900000000 | while(. < 18900000009; . + 1)|{method: "POST", url: "http://:6060", body: {id: .} | @ base64 }'"

The above command does not work when it is distributed  to several machines, and it's ok once there is no psh. 
My question is: how to correctly use psh & jq TOGETHER? 
For instance, what should the above command be in order to be successfully executed on different servers after the psh distribution?

**Comment by fengnex** [comment]
Even if we write the abouve command into a bash script, and then execute the script file, it does not work either.

**Comment by tsenart** [comment]
Please submit a [Bug Report](https://github.com/tsenart/vegeta/issues/new?template=bug_report.md)
