### ISSUE TITLE
jq does not work when using combined with psh

### ISSUE THREAD

**Issue by fengme** [tsenart/vegeta#436]
#### Version and Runtime

```
vegeta v12.7
```

#### Expected Behaviour

We can successfully execute a combined command which contains psh, jq and vegeta directive.
For example, The following command can correctly run:
pssh -h host_ip.txt -i -t 100000 -P "jq -ncM '18900000000 | while(. < 18900000009; . + 1)|{method: "POST", url: "http://:6060", body: {id: .} | @ base64 }'"

#### Actual Behaviour
When vegeta directive is combined with jq, it can only correctly run on ONE server, and it always fails to run once being distributed to different machines through psh.

I guess there is something wrong in the process of character ' or ".
#### Steps to Reproduce

1. Prepare a complex command which consists of psh, jq and vegeta directives
1. Execute the above command and expect it will be successfully distributed 
3. Check whether the above command can be successfully executed on any machines, the command should be able to run successfully on all machines

**Comment by fengnex** [comment]
@tsenart Are there any fix plans in the future?

**Comment by fengnex** [comment]
Found another bug: when there is a character & in http URL and distribute the url with psh, the url will be splited in the character &, so vegeta will not correctly attack objective URL.
Hope to see its fix too.

**Comment by tsenart** [comment]
You have to share reproducible steps for me to debug.

**Comment by fengnex** [comment]
@tsenart You can try similar steps like the following to reproduce the bug:
1. Please execute command: ./pssh -h /data/host_ip.txt -i -t 100000000 -P "'/data/fixrps/jq-1.5/jq -ncM 'while(true; .+1)|{method: "POST" | @base64 }''"
2. If you observe the output of the above command, and then you will get some errors which look like the following:
[1] 17:13:23 [FAILURE] 172.18.9.100:58022 Exited with error code 1
Stderr: bash: -c: line 0: syntax error near unexpected token `true'
bash: -c: line 0: `'/data/fixrps/jq-1.5/jq -ncM 'while(true; .+1)|{method: POST | @base64 }'''

OR:
[1] 17:12:23 [FAILURE] 172.18.9.100:58022 Exited with error code 3
Stderr: jq: error: POST/0 is not defined at <top-level>, line 1:
while(true; .+1)|{method: POST | @base64 }                          
jq: 1 compile error

Anyway, the bug could be get around by moving those jq code snippets into a bash script file and then distributing the file to servers instead.

**Comment by tsenart** [comment]
I just don't see vegeta being invoked in there. Am I missing something?
