### ISSUE TITLE
How to know which request produced 5xx error?

### ISSUE THREAD

**Issue by aoyama-val** [tsenart/vegeta#437]
#### Question

I am feeding  multiple request settings (`targets` in Vegeta term?), but `vegeta report` only informs me the status codes and the numbers. I would like to know which request produced the 5xx errors. Is this possible? It would be even better if we could get the stats grouped by the targets.

```
Status Codes  [code:count]               200:5  400:5  502:5
Error Set:
400 Bad Request
502 Bad Gateway
```

**Comment by tsenart** [comment]
After #438 is merged, you'll be able to use tools like `xsv` or `jq` to achieve your goal by converting the results of an attack to JSON or CSV with `vegeta encode`.
