### ISSUE TITLE
How to set attack circularly？

### ISSUE THREAD

**Issue by JFRabbit** [tsenart/vegeta#440]
#### How to set attack circularly？
I want to attach a request circularly, and repeat about 30 times, like jmeter 'loop count' function, so how to set attack param?

**Comment by tsenart** [comment]
I don't know what jMeter's "circular" behaviour is. vegeta repeats the same request at the specified `-rate` for the given `-duration`. Does that help?

**Comment by sbilello** [comment]
Is there a way to specify a file that contains a list of requests and loop through them?

**Comment by tsenart** [comment]
Looping through the requests is the default behavior unless you specify the `-lazy` flag. You can pass all the targets you want to stdin or with the `-targets` flag. They can be defined in either the JSON or HTTP `-format`. See the README for more details and examples.

**Comment by JFRabbit** [comment]
It looks like use ```-rate=0 -max-worker=1``` can make it work.  
Only one thread, and attack after response repeatedly.
