### ISSUE TITLE
Is it possible to wait for initial set of requests to finish before bombarding next set of requests using Vegeta Lib

### ISSUE THREAD

**Issue by nishant-shah-social** [tsenart/vegeta#444]
#### 1) N jobs or requests are submitted at Once. Once all of them complete, then submit next N jobs.
Is this scenario possible using vegeta Library ?
Can you please provide more info here?
2) Also, I did not find proper documentation of the library, can you please point me to the same
3) One last question :- is it possible to get the results in the form of :- 90 percentile, 95 percentile...so on?
Thanks in advance.

**Comment by tsenart** [comment]
> 1) N jobs or requests are submitted at Once. Once all of them complete, then submit next N jobs.

- You can limit how many concurrent requests vegeta sends with the `-rate` flag. Look into the [implementation of `vegeta attack`](https://github.com/tsenart/vegeta/blob/master/attack.go#L171) to see how it's done with the library.
- You can limit how many workers send requests with the `-max-workers` flag or `vegeta.MaxWorkers` attacker option in library.

We don't have any functionality implemented to wait for N requests to finish before sending the next N. If you want something like this, you can implement your own [Pacer](https://godoc.org/github.com/tsenart/vegeta/lib#Pacer).
 
>  Also, I did not find proper documentation of the library, can you please point me to the same

- https://godoc.org/github.com/tsenart/vegeta/lib
- https://github.com/tsenart/vegeta#usage-library

>  One last question :- is it possible to get the results in the form of :- 90 percentile, 95 percentile...so on?

Yes: https://godoc.org/github.com/tsenart/vegeta/lib#LatencyMetrics
