### ISSUE TITLE
Interaction between `rate` and target list?

### ISSUE THREAD

**Issue by kqr** [tsenart/vegeta#459]
I have used Vegeta to discover at what request rate our API fails to serve requests in time, and breaks off into queuing behaviour behaviour (which is somewhere between 200 and 300 requests/second.)

When I supplied a list of five different backend servers running this API service as the target list to Vegeta, I expected to also be able to increase the rate from 200 to 500 without running into queueing, since then each endpoint would be loaded with a rate of 100, which is well below their maximum of 1000.

However, it seemed the limit was still just beyond 200. This makes me suspect maybe Vegeta interprets the rate as the rate with which to hit each target specified in the target list. Is this correct? I couldn't seem to get this information out of the documentation.

**Comment by tsenart** [comment]
> This makes me suspect maybe Vegeta interprets the rate as the rate with which to hit each target specified in the target list. Is this correct?

No, this is not correct. The specified `-rate` should be the aggregate rate across targets. What does the `vegeta report` and `vegeta plot` look like?

**Comment by kqr** [comment]
The file `requests-one.http` contains a single request. The file `requests-many.http` contains five requests, each to a different server providing the same API service.

I run Vegeta against a single server with a rate of 200 (and a duration that gets me about 5000 requests):

```
$ < requests-one.http vegeta attack -duration=25s -rate=200 | vegeta report
Requests      [total, rate, throughput]  5000, 200.04, 199.13
Duration      [total, attack, wait]      25.109462599s, 24.994957984s, 114.504615ms
Latencies     [mean, 50, 95, 99, max]    79.496623ms, 71.055631ms, 130.313093ms, 161.110703ms, 223.118019ms
Bytes In      [total, mean]              53190000, 10638.00
Bytes Out     [total, mean]              115000, 23.00
Success       [ratio]                    100.00%
Status Codes  [code:count]               200:5000
Error Set:
```

Latencies are within parameters because 200 requests/second is something this service can do. Just to check, I also run it with 300 requests/second (again, with a duration that aims for about 5,000 requests to make it fair.) This should make the maximum latency shoot through the roof, and it does:

```
$ < requests-one.http vegeta attack -duration=17s -rate=300 | vegeta report
Requests      [total, rate, throughput]  5100, 300.06, 153.27
Duration      [total, attack, wait]      32.40681727s, 16.996665537s, 15.410151733s
Latencies     [mean, 50, 95, 99, max]    2.760229009s, 2.00361593s, 4.097516423s, 30.000246267s, 30.000345099s
Bytes In      [total, mean]              52838946, 10360.58
Bytes Out     [total, mean]              114241, 22.40
Success       [ratio]                    97.39%
Status Codes  [code:count]               0:133  200:4967
Error Set:
Post http://engine-v421-dev.example.com/api/_new: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Then I try 200 requests/second using the five different targets, which is fine:

```
$ < requests-many.http vegeta attack -duration=25s -rate=200 | vegeta report
Requests      [total, rate, throughput]  5000, 200.04, 199.24
Duration      [total, attack, wait]      25.095822207s, 24.995050074s, 100.772133ms
Latencies     [mean, 50, 95, 99, max]    168.017219ms, 161.385692ms, 264.373164ms, 328.522362ms, 463.939705ms
Bytes In      [total, mean]              52647000, 10529.40
Bytes Out     [total, mean]              115000, 23.00
Success       [ratio]                    100.00%
Status Codes  [code:count]               200:5000
Error Set:
```

But, and this is what puzzles me: when I increase the rate to 300 (which should amount to 60 requests/second/target and no sweat at all), the services start to choke again:

```
Requests      [total, rate, throughput]  5100, 300.06, 141.11
Duration      [total, attack, wait]      35.063629791s, 16.996676329s, 18.066953462s
Latencies     [mean, 50, 95, 99, max]    3.832708499s, 768.486663ms, 15.85253826s, 30.000244216s, 30.009085503s
Bytes In      [total, mean]              52094970, 10214.70
Bytes Out     [total, mean]              113804, 22.31
Success       [ratio]                    97.02%
Status Codes  [code:count]               0:152  200:4948
Error Set:
Post http://engine-v421-dev-3.example.com/api/_new: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Post http://engine-v421-dev.example.com/api/_new: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Post http://engine-v421-dev-2.example.com/api/_new: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Post http://engine-v421-dev-5.example.com/api/_new: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Post http://engine-v421-dev-4.example.com/api/_new: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by kqr** [comment]
It'll take me slightly longer to get the plot, since I'm running the load generation on a machine that doesn't have a graphical interface. But before I take the time to do that, I'll just be very clear about one thing:

This could also be because the service I'm testing is hitting a different bottleneck. I.e. maybe all five API servers hit the same database and run into high lock contention in that, or a million other possibilities.

That's why I wanted to ask what Vegeta is supposed to do in this case: if Vegeta is meant to split the request rate over all targets, then I think it is much more likely that there is a different bottleneck in my system, rather than Vegeta being broken!

**Comment by kqr** [comment]
Okay, only after installing Vegeta locally in order to be able to run the plot command did I realise that the plot command doesn't actually require a GUI – it simply outputs HTML to render a plot. This is such a nice tool to work with. Awesome.

one-25s-r200:

![image](https://user-images.githubusercontent.com/356598/68116323-d0cebe80-fefa-11e9-89fa-1aa87287f676.png)

one-17s-r300:

![image](https://user-images.githubusercontent.com/356598/68116378-ff4c9980-fefa-11e9-971a-282d01e75b74.png)

many-25s-r200:

![image](https://user-images.githubusercontent.com/356598/68116412-0ecbe280-fefb-11e9-937c-869f58191ec5.png)

many-17s-r300:

![image](https://user-images.githubusercontent.com/356598/68116431-1ab7a480-fefb-11e9-8b9b-dca959d75f0f.png)

**Comment by kqr** [comment]
Thanks. Considering this resolved.
