### ISSUE TITLE
merging two results with plot command generate scatter graph

### ISSUE THREAD

**Issue by aca** [tsenart/vegeta#460]
#### Question
Hi, I'm having some struggles with plot command, failed to find any related documents for this.
I expected results like the image in https://github.com/tsenart/vegeta#plot-command
But I just can't generate graph like that one.

Instead, I get scattered graph like this which is almost impossible to analyze.
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/50316549/68219108-c9a5ce80-0028-11ea-9c3f-2877e2c9a8d5.png">

I followed exact same command as the example suggests.
```
  echo "GET http://:80" | vegeta attack -name=50qps -rate=50 -duration=5s > results.50qps.bin
  cat results.50qps.bin | vegeta plot > plot.50qps.html
  echo "GET http://:80" | vegeta attack -name=100qps -rate=100 -duration=5s > results.100qps.bin
  vegeta plot results.50qps.bin results.100qps.bin > plot.html
```

Is there any other things to generate normal line graph like the image?

By the way, thanks for the great program.

**Comment by aca** [comment]
Oops. There was button controlling this. closing.

**Comment by hanneshapke** [comment]
Hi @aca,

Can you please add some more comments what you changed to turn your scatter plot into a line chart?
I am seeing the same problem, but I don't know which button you mean. Thank you for the additional comments!

**Comment by aca** [comment]
@hanneshapke sorry for the late response.
![image](https://user-images.githubusercontent.com/50316549/86996368-7226b680-c1e6-11ea-9375-274326626add.png)

Change the number, on the page. 
```
Click and drag to select a region to zoom into. Double click to zoom out.
Choose a different number on the bottom left corner input field
to change the moving average window size (in data points).
```
