### ISSUE TITLE
Proposal: Add a correlation ID to the Target that is shared with the Result to help trace slow queries.

### ISSUE THREAD

**Issue by jacquesbernier** [tsenart/vegeta#462]
#### Proposal

**Option 1**:

The proposal is to attach the `Result.Seq` (https://github.com/tsenart/vegeta/blob/master/lib/attack.go#L338-L342) to the `Target` that is passed to the `Targeter` https://github.com/tsenart/vegeta/blob/master/lib/attack.go#L351.
`Result.Seq` is set before the Targeter is called. Therefore, adding the a field `Target.Seq` and set it to the same value is a possibility.
I believe this one can be backward compatible and a low cost option.

**Option 2**:

Add a new option to the `Attacker` that allows the user to provide a correlation ID generator (this can be a function that returns a string). Add the generated correlation ID to the target and the Result in the `Attacker.attack` method.

#### Background

We use vegeta for load testing and we report `Result`s for slow queries. We would love to have a way to correlate a `Result` to the request that was made to help us analyze if there is a systematic problem with particular queries that we use.

We use vegeta in library mode and are able to store the requests. We would want to have a correlation id and we believe that the `Result.Seq` could be it.

Note:
I recognized that it may seem related to https://github.com/tsenart/vegeta/issues/205 to which you answer that server logs could be used. However, I see 2 cases where this may be hard. Logging all requests on the server may affect the performances that we trying to test. In other cases, we may not have that possibility. I.E. we are sometimes load testing against vendors and have little visibility into their logs.

#### Workarounds

By providing a custom http client that intercepts the request and response.
However, this means that the body may be read multiple times.

**Comment by tsenart** [comment]
Would adding an `X-Vegeta-Seq` header to each request that is done be sufficient?

**Comment by jackdbernier** [comment]
The goal is to have the information in the `Result` https://github.com/tsenart/vegeta/blob/44a49c878dd6f28f04b9b5ce5751490b0dce1e18/lib/results.go#L23. The headers are not attached to the Result. That is why I proposed different ways.

**Comment by tsenart** [comment]
@jackdbernier: However, the `Seq` number is already in the `Result`, so if we add a `X-Vegeta-Seq` header to each `Target`, you'd know how to correlate.

**Comment by jackdbernier** [comment]
@tsenart yes. I feel like an idiot now 😄. I think this would be an elegant solution and 100% backward compatible.

**Comment by tsenart** [comment]
> @tsenart yes. I feel like an idiot now 😄. I think this would be an elegant solution and 100% backward compatible.

No reason to feel that way :) I could potentially get a patch going over the weekend, but can't guarantee. Since this is such a small change, I encourage you to take a stab at it.
