### ISSUE TITLE
Use with proxy

### ISSUE THREAD

**Issue by alkaphreak** [tsenart/vegeta#463]
I'm sorry to coming back on this topic but in can't figure out what i'm doing wrong.

Post multipart/form-data request are fine with Postman and Curl but not with Vegeta and i can't figure out why.

So i'm trying to use a http proxy (Camilla) to see what's going by and compare requests. Postman and Curl are fine but i can't go through my proxy with Vegeta.

I used your methods described in the issue [196](https://github.com/tsenart/vegeta/issues/196#issuecomment-244564599)

In my script `vegeta_test.sh` : 
```
...
export HTTP_PROXY="http://127.0.0.1:8888/"
vegeta attack -targets="targets.txt" -header "api-key: $APIKEY" -rate=$RATE -duration=$DURATION -name=$TEST_NAME >results.$TEST_NAME.bin && vegeta plot results.$TEST_NAME.bin >plot.$TEST_NAME.html && rm results.$TEST_NAME.bin
```

And in `targets.txt` : 
```
...
# Post
POST http://127.0.0.1:8089/
Content-Type: multipart/form-data; boundary=--------------------------994143362645270230245724
@./vegeta-test.txt
```
Could you help me on this one ?

Thanks for this great tool. It's awesome. :)

**Comment by tsenart** [comment]
>  are fine but i can't go through my proxy with Vegeta.

I'd need more information to help. What do you expect to see and what are you seeing instead? Are there any errors being reported by Vegeta?

**Comment by tsenart** [comment]
Basically, please submit an actual Bug Report (it includes the questions I need answered to be able to help): https://github.com/tsenart/vegeta/issues/new?template=bug_report.md
