### ISSUE TITLE
Whether is it possible to test consecutive several urls through vegeta?

### ISSUE THREAD

**Issue by fengnex** [tsenart/vegeta#465]
#### Question
Let's consider a scenario which is common in some real businesses as the following:

If a business operation to be pressed contains three consecutive URLs, the first one encrypts parameters by some encryption method, one of which is the real-time timestamp of the operation system. The return result of this URL is one of the input parameters of the second URL, and part of the data in the response result of the second URL is the input parameter of the third URL.

My question is whether we can do stress tests for such a scenario and how to do the tests then?

**Comment by tsenart** [comment]
Vegeta  doesn't have this capability today and there are no plans to implement it in the near future. For such user session aware load tests, I'd recommend you look into https://k6.io/ or https://gatling.io/.
