### ISSUE TITLE
Whether is it possible to do a stress test for more than one URL?

### ISSUE THREAD

**Issue by fengnex** [tsenart/vegeta#467]
#### Question
I wonder whether it is possible if we want to test TWO urls within one stress test, and we may want to distribute different amount of requests to each url every second. How to implement that if we can do? Thanks in advance.

**Comment by tsenart** [comment]
Yes... As documented in the README, just pass multiple targets to `vegeta attack`. Example:

```
printf "GET http://target-1:8080/\nGET http://target-2:8080\n" | vegeta attack ...
```

**Comment by yc2984** [comment]
@tsenart When you give several targets, what is the distribution of the attack? Does vegeta go through the targets one by one uniformly? If I want to test unbalanced test, I need to repeat certain targets more times than others right?
