### ISSUE TITLE
Max-workers flag and rate=0 do not work in v12.7.0

### ISSUE THREAD

**Issue by kurnifamili** [tsenart/vegeta#468]
#### Question
Hi guys, from the commits I see that are included in v12.7.0, there should be a capability to specify `-rate=0` and `-max-workers` flag. However, when I run the following command
`echo "GET http://localhost:8080/test" | vegeta attack -rate=0 -max-workers=10`

It returns an error saying `flag provided but not defined: -max-workers` and `rate frequency and time unit must be bigger than zero`. The command help message also does not include usage of `max-workers` flag. I have checked and I am definitely using v12.7.0 of vegeta. Any ideas what might be the cause?

**Comment by tsenart** [comment]
That's so strange. I must have messed up the last release. I'll update the assets of that release.

**Comment by tsenart** [comment]
Actually, scrap that. I just downloaded the latest `v12.7.0` release (https://github.com/tsenart/vegeta/releases/download/v12.7.0/vegeta-12.7.0-linux-amd64.tar.gz), and I can run that command without any issue.

Are you sure you unpacked the right tarball? It also happened to me that I unpacked an old vegeta tarball I had in my dowloads directory, hence the previous message :)

**Comment by kurnifamili** [comment]
I have never downloaded/installed a different version before as I just started using this library.

But anyway, I just tried downloaded the tar and tried again and it's working now. Not sure what happened before. Sorry for the false alarm.
