### ISSUE TITLE
How to plot with Vegeta lib

### ISSUE THREAD

**Issue by francescomormile** [tsenart/vegeta#473]
Hi, can you explain how to plot - or how to generate plottable file with vegeta lib in go. I guess I have to use `NewHDRHistogramPlotReporter`, but I can't understand how. Can you help me?

**Comment by tsenart** [comment]
You can see how to use it in the implementation of the `vegeta plot` command: https://github.com/tsenart/vegeta/blob/85244b4acb411f39075b7f47533ec04ac438201b/plot.go#L79

**Comment by francescomormile** [comment]
Sorry, still can't see how should it plot my results

**Comment by tsenart** [comment]
What do you mean? The code is there. It takes in results and spits out an HTML file that you can open in your browser.

**Comment by francescomormile** [comment]
got it!, I've seen your tests indeed. Thank you very much!
