### ISSUE TITLE
Make rate calculation of the instantaneous rate of attack exportable

### ISSUE THREAD

**Issue by francescomormile** [tsenart/vegeta#476]
#### Proposal

I wish I could get the instantaneous rate of attack. It means make exportable rate function in pacer.go at line 272

#### Background

It would be useful to me to observe the growth of the rate when using linear pacer.

#### Workarounds

I can't find any other workaround

**Comment by tsenart** [comment]
What interface change do you propose concretely? It'd be easier to discuss over that.

**Comment by francescomormile** [comment]
Well, if you simply write the rename the function "rate(...)" to Rate(...)" at line 272, I can reuse it in my code so that I can print the instantaneous rate whenever I need. It's a little change but really useful in my humble opinion. I could even stop the attack when getting a given rate. Don't you think?

**Comment by blakewatters** [comment]
I'd probably argue for an interface method on `Pacer` like: `RequestsPerSecond(elapsed time.Duration) (rps uint64)`
