### ISSUE TITLE
Vegeta with Jenkins

### ISSUE THREAD

**Issue by dilshan5** [tsenart/vegeta#478]
#### Question
Hi,

Can we invoke vegeta using Jenkins? If possible can anyone share me the steps which I need to follow.

Thanks

**Comment by tsenart** [comment]
Since vegeta is a cli tool, you can invoke it from anywhere you can run commands. I don't know about your specific environment so can't say exactly what you need.

**Comment by dilshan5** [comment]
@tsenart - I have integrate Vegeta test results with Grafana. For more details please refer:

https://www.linkedin.com/pulse/how-integrate-vegeta-performance-test-results-grafana-fernando/?fbclid=IwAR1V23ng6cIM_FkBA0s_Ooe9xkH5bBkggWnvpGHTZcmd8nWPw_qMome772U
