### ISSUE TITLE
How to parse and obtain each url's stress test result records from the output csv file that is generated through command 'vegeta encode'?

### ISSUE THREAD

**Issue by fengme** [tsenart/vegeta#482]
#### Question
I was glad these days as I had confirmed that multiple URLs can be successfully tested under certain stress at the same time, and I want to say that it's really cool!

But after that, I found a new question since I cannot get the corresponding test records of every URL from the CSV file outputted by executing the command 'vegeta encode'. This is because there is no way to distinguish what results belong to a certain or another URL in the CSV file even though we can get the whole output. However, there is no any URL for those successful test records in the file.

What I want to know is how to address the above problem.

**Comment by tsenart** [comment]
You can always post process the results, group by URL into different groups, and then feed each of those grouped result sets to vegeta report.
