### ISSUE TITLE
Can vegeta output result file integrate with Grafana or Kibana

### ISSUE THREAD

**Issue by dilshan5** [tsenart/vegeta#484]
#### Question

I want to display vegeta test results in open source Data visualization dashboards such as Grafana/Kibana. How can I achieve this?

**Comment by blakewatters** [comment]
Use the JSON output report and ingest it into your system

**Comment by dilshan5** [comment]
@blakewatters  - thanks for the reply. 

Without sending the JSON once the test is completed, are there any listener where we can directly ingest data to Grafana?

**Comment by dilshan5** [comment]
@blakewatters - Hope you are doing good. 
 Any update on this?

**Comment by fengnex** [comment]
@dilshan5 You can use vegeta encode to output your test rest records into a file, and then you can use filebeat or logstash to import the file into ES. Finally, you can use kibana or Grafana to  analyze or display your data or analysis results.

So, I don't think it's necessary or urgent to develop the feature you mentioned above.

**Comment by fengnex** [comment]
@tsenart It's suggested that corresponding URL of each output record is printed out in the final result file though.

**Comment by tsenart** [comment]
> I want to display vegeta test results in open source Data visualization dashboards such as Grafana/Kibana. How can I achieve this?

I'm not sure, there's probably a few different ways via `vegeta encode`, but nothing built-in.
