### ISSUE TITLE
How to define example load

### ISSUE THREAD

**Issue by fvosberg** [tsenart/vegeta#487]
Sorry for bothering you.

I'm going to write my bachelor thesis about the comparison of cloud providers. For that, I would like to host an example service on each of the three big cloud providers. Then I would like to simulate usage with Vegeta and measure things like latency and costs. 

Do you have any idea how to define "example traffic"? I've searched for example traffic for small services like basket/shopping cart services or auth services. But I can't find anything. I suspect that something like this gets published. I think it is ok to use the same load on all cloud providers, but as I've never worked with load testing, it's hard for me to define load, which is sufficient for this test. I'm expecting something like for a day:

8:00 -18:00 moderate traffic
18:00-21:00 peak traffic
21:00-8:00 very low traffic

this would take into account, that cloud applications should scale. But do you have any tips on defining low traffic, moderate traffic and peak traffic for a small microservice?

thanks in advance
cheers
Fredi

**Comment by tsenart** [comment]
> this would take into account, that cloud applications should scale. But do you have any tips on defining low traffic, moderate traffic and peak traffic for a small microservice?

This is entirely variable and dependent on the business, environment and a number of other things. I don't think you can generalize this, so if I were you I'd pick an example company and a service of them that has published numbers and try to replicate that.
