### ISSUE TITLE
form post

### ISSUE THREAD

**Issue by tcurdt** [tsenart/vegeta#496]
I need to test an endpoint that receives input from a form. I am generating the input json like this

```
jq -ncM 'while(true; .+1) | {method: "POST", url: "http://localhost:8080/s/1", body: {a: . | "\(.)-some" } }'
...
{"method":"POST","url":"http://localhost:8080/s/1","body":{"a":"21375-some"}}
...
```

As documented in the README I tried to stream this into

```
jq -ncM 'while(true; .+1) | {method: "POST", url: "http://localhost:8080/s/1", body: {a: . | "\(.)-some" } }' | \
vegeta attack -rate=50/s -lazy -format=json -duration=30s | tee results.bin | vegeta report
```

but what I am getting as output (pretty much immediately - not after 30s)

```
Requests      [total, rate, throughput]         3, 81.66, 0.00
Duration      [total, attack, wait]             36.78ms, 36.737ms, 43.034µs
Latencies     [min, mean, 50, 90, 95, 99, max]  43.034µs, 309.894µs, 164.507µs, 722.142µs, 722.142µs, 722.142µs, 722.142µs
Bytes In      [total, mean]                     0, 0.00
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           0.00%
Status Codes  [code:count]                      0:3  
Error Set:
parse error: expected string near offset 59 of 'body'
```

I guess it's sending json instead of form encoding?
But I still don't understand the error message.

**Comment by tcurdt** [comment]
That's slightly better. But it does not send 

```
Content-Type: application/x-www-form-urlencoded
```

**Comment by tsenart** [comment]
There's no built-in conversion of the JSON body field to URL encoded format. You might have some success using the HTTP target format instead.

**Comment by tcurdt** [comment]
That's a bit of a shame. Would be nice if this could be done through the JSON.
But I just managed to get it working by adding manually encoding it and setting the header like this

```
vegeta attack -header "Content-Type: application/x-www-form-urlencoded" ...
```

**Comment by tsenart** [comment]
Cool! Happy this is sorted out :-)
