### ISSUE TITLE
v12.8.0 cannot be imported as a Go module

### ISSUE THREAD

**Issue by mxey** [tsenart/vegeta#497]
#### Version and Runtime

v12.8.0

#### Expected Behaviour

Vegeta can be imported as a Go module

#### Actual Behaviour

`github.com/tsenart/vegeta v12.8.0+incompatible` in `go.mod`: 

```
go: github.com/tsenart/vegeta@v12.8.0+incompatible/go.mod: verifying module: github.com/tsenart/vegeta@v12.8.0+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/tsenart/vegeta@v12.8.0+incompatible: 410 Gone
        server response: not found: github.com/tsenart/vegeta@v12.8.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

`github.com/tsenart/vegeta v12.8.0` in `go.mod`: 

```
go: errors parsing go.mod:
…/go.mod:8: require github.com/tsenart/vegeta: version "v12.8.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v12
```

#### Steps to Reproduce

1. `git clone https://github.com/mxey/vegeta-go-mod`
1. `cd vegeta-go-mod`
1. `go build`

**Comment by tsenart** [comment]
You need to import `github.com/tsenart/vegeta/lib`

**Comment by mxey** [comment]
In the `main.go` I am importing the `lib` package. But `go build` will resolve that to its containing module, which is `github.com/tsenart/vegeta`.

```
vegeta-go-mod [master] $ go build
go: finding module for package github.com/tsenart/vegeta/lib
go: found github.com/tsenart/vegeta/lib in github.com/tsenart/vegeta v12.7.0+incompatible
```

**Comment by tsenart** [comment]
Actually not sure how to fix this. Haven't really caught up with go modules to be honest. Any clue how to fix it?

**Comment by tsenart** [comment]
This seems to work? https://github.com/timakin/fukaziroh/blob/master/go.mod#L6

**Comment by mxey** [comment]
> Actually not sure how to fix this. Haven't really caught up with go modules to be honest. Any clue how to fix it?

Yes. Your go.mod needs to contain `module github.com/tsenart/vegeta/v12`. Major versions higher than 1 are part of the import path. See https://blog.golang.org/publishing-go-modules.

> This seems to work? https://github.com/timakin/fukaziroh/blob/master/go.mod#L6

Because it refers to an older version which did not contain a `go.mod` yet.

**Comment by tsenart** [comment]
Cool! Thanks :) Can you open small PR for this please?

**Comment by wetcod** [comment]
The same problem still occurs after #501 is merged.

When I import `github.com/tsenart/vegeta/lib` into my `main.go` and build,
`github.com/tsenart/vegeta v12.7.0+incompatible` is added to my `go.mod`

When I import `github.com/tsenart/vegeta/v12/lib` into my `main.go` and build, 
the following error occurs.
```
$ go build main.go
go: finding github.com/tsenart/vegeta/v12/lib latest
go: finding github.com/tsenart/vegeta/v12 v12.8.0
build command-line-arguments: cannot load github.com/tsenart/vegeta/v12/lib: module github.com/tsenart/vegeta@latest found (v12.7.0+incompatible), but does not contain package github.com/tsenart/vegeta/v12/lib
```

**Comment by tsenart** [comment]
@wetcod: Does importing `github.com/tsenart/vegeta/lib/v12` work?

**Comment by wetcod** [comment]
> @wetcod: Does importing `github.com/tsenart/vegeta/lib/v12` work?

It also doesn't work.

```
$ go build main.go
go: finding github.com/tsenart/vegeta/lib/v12 v12.3.0
go: finding github.com/tsenart/vegeta/lib v1.2.0
build command-line-arguments: cannot load github.com/tsenart/vegeta/lib/v12: module github.com/tsenart/vegeta@latest found (v12.7.0+incompatible), but does not contain package github.com/tsenart/vegeta/lib/v12
```

**Comment by mxey** [comment]
There is no release yet with the fixed import path.

**Comment by wetcod** [comment]
Oh I see. If release is required to apply it, I'll wait for next version. Thank you.

**Comment by tsenart** [comment]
I tagged it. Does it work now?

**Comment by mxey** [comment]
looks good:

```
go: finding module for package github.com/tsenart/vegeta/v12/lib
go: found github.com/tsenart/vegeta/v12/lib in github.com/tsenart/vegeta/v12 v12.8.1
```
