### ISSUE TITLE
Two different .bin file plotting color wonder

### ISSUE THREAD

**Issue by ARuei** [tsenart/vegeta#498]
#### Question

Hi guys,

I just used _vegeta_ tool to create two different bin files, and plot them by 
_$vegeta plot result1.bin result2.bin > plot.html_

The colors generated by plot look similar which make it hard to tell. Is there any change I could make to adjust the line color distribution? The illustrated figure looks like distinct and easy to tell by simply looking at the color. 

Also, the number in bottom left corner means _moving average window size (in data point)_, I do not understand why we just simply modify the values and the latency will change respectively.

Sorry if I asked the dumb questions...

**Comment by mciastek** [comment]
It looks like line colors are hardcoded in the script. See:

https://github.com/tsenart/vegeta/blob/19b74586217105bbde8ded6077c70095e97146bf/lib/plot/plot.go#L273-L276
https://github.com/tsenart/vegeta/blob/19b74586217105bbde8ded6077c70095e97146bf/lib/plot/plot.go#L253-L261

Maybe it could be a parameter passed to `plot` command? @tsenart what do you think?

**Comment by tsenart** [comment]
This has been fixed in 60c2d660882aa630a4dd08a110955de94beb4cb6
