### ISSUE TITLE
Make the flags and types public for reuse

### ISSUE THREAD

**Issue by bzon** [tsenart/vegeta#499]
#### Proposal

Make the flags and types public so we can use the same flags when we build our own **vegeta** attacker binary.

**Comment by tsenart** [comment]
I don't understand this proposal. Please elaborate appropriately.

**Comment by bzon** [comment]
@tsenart we are trying to use vegeta as a library to customize our attack code. Our goal is to build a new binary out of our custom code.

We want to use the same fs.FlagSet that the main vegeta code is using but we cannot because they are private or unexported.

https://github.com/tsenart/vegeta/blob/master/attack.go

**Comment by tsenart** [comment]
I see. In the meantime, can't you fork vegeta and change the code directly to your needs?

**Comment by tsenart** [comment]
I don't think this is a common enough use case that it justifies the added API surface. I think forking is a fine approach.
