### ISSUE TITLE
How to send a body with x-www-form-urlencoded content type

### ISSUE THREAD

**Issue by dilshan5** [tsenart/vegeta#504]
#### Question
Hi,

With Vegeta, i'm trying to send a body with x-www-form-urlencoded content type. I converedt the text to url encoded string format and save it to a text file. And then sent using -body. But i'm getting 401. 

How can we send a body with x-www-form-urlencoded content type using Vegeta?

Thanks,
Dilshan

**Comment by josancamon19** [comment]
Hi @dilshan5, wondering if you've found a solution.

I'm trying this:
```
jsonData := map[string]interface{}{"email": "joan@123.com", "password": "123"}
data, _ := json.Marshal(jsonData)
vegeta.Target{
	Method: "POST",
	URL:    BaseUrl + "auth",
	Header: http.Header{
		"Content-Type": []string{"multipart/form-data"},
	},
	Body: data,
}
```

**Comment by dilshan5** [comment]
This was helped me..

`echo "POST <url>" | vegeta attack bodyf='client_id=test&client_secret=test' -header 'Content-Type: application/x-www-form-urlencoded' -rate=100 -duration=10s -timeout=100s | vegeta report`
