### ISSUE TITLE
nginx http2 problems

### ISSUE THREAD

**Issue by freesamw** [tsenart/vegeta#511]
#### Question
During the Web server HTTP/2 benchmark test, problems occur only on nginx.
Latency increases abnormally with each request count of 1000.
Have you ever reported a problem like this?

I am using it well and received a lot of help. thanks.

**Comment by tsenart** [comment]
If you want help, please five detailed information in a [Bug Report](https://github.com/tsenart/vegeta/issues/new?assignees=&labels=&projects=&template=bug_report.md).
