### ISSUE TITLE
what's mean about 9000?

### ISSUE THREAD

**Issue by thinkerou** [tsenart/vegeta#514]
#### Question

```HTTP load testing tool and library. It's over 9000! ```
here 9000 is what mean? thanks!

**Comment by 512banque** [comment]
https://en.wikipedia.org/wiki/It%27s_Over_9000!

**Comment by kadaan** [comment]
https://en.wikipedia.org/wiki/It's_Over_9000!

**Comment by molecula451** [comment]
![Over_9000!](https://user-images.githubusercontent.com/41552663/81478060-f2ca3600-91e8-11ea-88a9-833b0435716d.png)

**Comment by cupen** [comment]
@kadaan your url is broken. :smiley:  
fix it with `<https://en.wikipedia.org/wiki/It%27s_Over_9000!>`
<https://en.wikipedia.org/wiki/It%27s_Over_9000!>

**Comment by tsenart** [comment]
Linked in README :D https://github.com/tsenart/vegeta/commit/ca2362d5485e0022229a05047e43c7e114070b3e
