### ISSUE TITLE
rps distribution over two targets

### ISSUE THREAD

**Issue by 3quanfeng** [tsenart/vegeta#519]
#### Question
I have two targets A and B, I set the rps=6, attack duration is 5s
from the log, I can see the total requests sent is 30, and 15 requests go to A, the other 15 goes to B.
In this case, A and B only get rps=3 instead of 6 respectively, is it correct?

**Comment by tsenart** [comment]
Yes, that’s correct.

Sent via Superhuman iOS ( https://sprh.mn/?vip=tsenart@gmail.com )

**Comment by 3quanfeng** [comment]
Thanks!
