### ISSUE TITLE
Does vegeta prevent coordinated omission?

### ISSUE THREAD

**Issue by toaler** [tsenart/vegeta#520]
#### Question

Similar to this question [1] does vegeta prevent coordination omission. I haven't been able to find a load generator that supports h2 and prevents coordinated omission.

[1] https://github.com/artilleryio/artillery/issues/721#issue-469383966

**Comment by tsenart** [comment]
Yes, it does. By default it will keep sending requests at specified rate, regardless of how slow the server is to respond.

Sent via Superhuman iOS ( https://sprh.mn/?vip=tsenart@gmail.com )

**Comment by toaler** [comment]
Thanks for the quick response @tsenart. Does it make sense to include that as a feature on the Readme.md? This is a great differentiator of this workload generator compared to others.

**Comment by Michael-Frank** [comment]
second that! A statement about coordintated ommision should be on top of the readme, preferable line 2 in <h1>
It is THE most important feature in the sea of load generators. Tool and its features do not matter, if the produced numbers are garbage.
There should be a "A+ Fixed Coordinated Ommission" banner or something like that 😀

**Comment by nukemberg** [comment]
Well, not exactly. Vegeta properly handles it if the request is TCP accepted but if it is waiting on the TCP socket backlog queue it will be backpressured and act as a closed system with coordinated omission. Don't know how common this is for most ppl but worth mentioning in case someone runs into it.

**Comment by tsenart** [comment]
Added to the README: https://github.com/tsenart/vegeta/commit/53fd7bace2f7aeea5c9c17be94bbcb3cfb162190
