### ISSUE TITLE
How to run load test with spesific users and rps ?

### ISSUE THREAD

**Issue by rifqiazam** [tsenart/vegeta#521]
#### Question

I want to run a load test with the specified number of users/workers and rps

example
- Runs 1000 users with 600 request per second

how to do it?

`vegeta attach -rate=600 -users=1000` ?

thanks in advance

**Comment by 3quanfeng** [comment]
-workers=1000 -max-workers=1000

**Comment by tsenart** [comment]
Users is an ill-defined load unit. Workers approximates one notion of it — concurrency units. See this answer: https://github.com/tsenart/vegeta/issues/546
