### ISSUE TITLE
How to send data-raw as post requests' data in vegeta?

### ISSUE THREAD

**Issue by fengnex** [tsenart/vegeta#528]
#### Question
When attaching a specified applicatin, we need to send a raw string as the only request parameter through a post request, but don't know how to achieve that with vegeta.

 The request method is POST, the parameter is not key-value style, it's just a single encrypted string. The problem is that we now have no way to send the string to the server in the setting of vegeta.

The command we executed is:
POST http://testURL
eq: Y6IxBROYbOAA5RxSJSCbUw==
@/data/fixrps/target/postd
The file named postd includes the string we want to send to the server. Whenever executing the above block in vegeta, the server always complains no data has been received.

The following command works fine, but how to write the command script for vegeta in order to successfully send the data-raw part specified in the command to the serverside system?
curl --location --request POST 'http://testURL' \
--header 'eq: Y6IxBROYbOAA5RxSJSCbUw==' \
--header 'Content-Type: text/plain' \
--data-raw '6+7JxfoPsvEsjADT8WWYFx1PJRmeVle1UXZJGBniea5J3DuB8OV67JAH1Uty296rTy0ReTBU4Sf1WcAPmN7WPGadp76DWypQKoKOxA4TYUtfJnrfSWndtxvm+VNU4h7u84Ao2t4kd3eFtccIu95C784bZx4F9lSICS6R0eVVHNj5zSn/PkwfiMS7rczSPL1Q0Ixn2rCgmG6zbrqvzw+PrOzSb/spclDG9BM2Xgjpe/ydXpQXUV50Ncg6CYLOKEU7qDSe4JQiKycHGnKFLljv6uzhJWvlIXsvyGF7B6BT6jM0BHF+z45W1j0rNDIH9Zxx6jyEel7FDHBA44K4KnF2PsyecRgDuY1UV579pAZjCji0UFb3Lsu2jJiLT6gcjG3j5pJgWY85H2C+fLjfU48BY9X4iWtJpeoISHwbqJ/4kzE1tdVUGN4fwWLYx5afX4bcbZbzMelAnXcK+huaUA/GLOqR2neNIfifBrg1MLcUW+BNorAJwfRJIf0/Lvc0t+q/'

We can also successfully access the server with the following command:
curl -H 'eq:Y6IxBROYbOAA5RxSJSCbUw==' -X POST https://testURL -d '6+7JxfoPsvEsjADT8WWYFx1PJRmeVle1UXZJGBniea5J3DuB8OV67JAH1Uty296rTy0ReTBU4Sf1WcAPmN7WPGadp76DWypQKoKOxA4TYUtfJnrfSWndtxvm+VNU4h7u84Ao2t4kd3eFtccIu95C784bZx4F9lSICS6R0eVVHNj5zSn/PkwfiMS7rczSPL1Q0Ixn2rCgmG6zbrqvzw+PrOzSb/spclDG9BM2Xgjpe/ydXpQXUV50Ncg6CYLOKEU7qDSe4JQiKycHGnKFLljv6uzhJWvlIXsvyGF7B6BT6jM0BHF+z45W1j0rNDIH9Zxx6jyEel7FDHBA44K4KnF2PsyecRgDuY1UV579pAZjCji0UFb3Lsu2jJiLT6gcjG3j5pJgWY85H2C+fLjfU48BY9X4iWtJpeoISHwbqJ/4kzE1tdVUGN4fwWLYx5afX4bcbZbzMelAnXcK+huaUA/GLOqR2neNIfifBrg1MLcUW+BNorAJwfRJIf0/Lvc0t+q/'

**Comment by fengnex** [comment]
Could anyone be so kind as to give some tips or solutions?

**Comment by tsenart** [comment]
This should work:

```
echo "6+7JxfoPsvEsjADT8WWYFx1PJRmeVle1UXZJGBniea5J3DuB8OV67JAH1Uty296rTy0ReTBU4Sf1WcAPmN7WPGadp76DWypQKoKOxA4TYUtfJnrfSWndtxvm+VNU4h7u84Ao2t4kd3eFtccIu95C784bZx4F9lSICS6R0eVVHNj5zSn/PkwfiMS7rczSPL1Q0Ixn2rCgmG6zbrqvzw+PrOzSb/spclDG9BM2Xgjpe/ydXpQXUV50Ncg6CYLOKEU7qDSe4JQiKycHGnKFLljv6uzhJWvlIXsvyGF7B6BT6jM0BHF+z45W1j0rNDIH9Zxx6jyEel7FDHBA44K4KnF2PsyecRgDuY1UV579pAZjCji0UFb3Lsu2jJiLT6gcjG3j5pJgWY85H2C+fLjfU48BY9X4iWtJpeoISHwbqJ/4kzE1tdVUGN4fwWLYx5afX4bcbZbzMelAnXcK+huaUA/GLOqR2neNIfifBrg1MLcUW+BNorAJwfRJIf0/Lvc0t+q/" > body.txt

echo "POST http://testURL" | vegeta attack -rate 50/s -duration 1m -body body.txt -header "eq: Y6IxBROYbOAA5RxSJSCbUw==" -header "Content-Type: text/plain" > results.bin

vegeta report results.bin
```

**Comment by fengnex** [comment]
@tsenart The problem still exists after using the solution you offered above.
Sigh, we need to go on trying solving it.
