### ISSUE TITLE
Feature: signal vegeta to increase/decrease attack rate

### ISSUE THREAD

**Issue by mikz** [tsenart/vegeta#53]
Would be great if vegeta could receive signals (TTIN/TTOU)[http://unicorn.bogomips.org/SIGNALS.html] to increase rate during the attack.

This could be used to simulate traffic waves.

**Comment by MarStarck** [comment]
How about this feature now? It sounds really useful

**Comment by aidylewis** [comment]
Solution from @tsenart. 
https://github.com/bbc/FOSS-Load-Tools/blob/master/vegeta/vegeta.md#ramp-up

I think either @tsenart is too busy with something else or is just happy with his work the way it is. Probably a bit of both. Vegeta is solid basic URL basher which I think was it's intention. Speak to me privately if you are not happy with this solution. My email is on my profile.

**Comment by daluu** [comment]
One could also expand on the mentioned solution with the distributed vegeta attack method https://github.com/tsenart/vegeta#usage-distributed-attacks, although it doesn't have to be implemented exactly like that example but taking that similar approach.

**Comment by tsenart** [comment]
Ramp-up is easily doable with a little shell script. This is a documentation problem. See: https://github.com/tsenart/vegeta/issues/304
