### ISSUE TITLE
No ARM64 build in the 12.8.4 release

### ISSUE THREAD

**Issue by martin-g** [tsenart/vegeta#544]
#### Question

There is no arm64 build at  https://github.com/tsenart/vegeta/releases/tag/v12.8.4

There are several more architectures at https://github.com/tsenart/vegeta/releases/tag/v12.8.3

Could you please re-add the arm64 build for the new releases ? Or add an entry to the README how to build it ourselves
Thank you!

**Comment by martin-g** [comment]
`GOOS=linux GOARCH=arm64 go build`

**Comment by aliesbelik** [comment]
Seems to be fixed in the recent - [12.9.0](https://github.com/tsenart/vegeta/releases/tag/v12.9.0), [12.10.0](https://github.com/tsenart/vegeta/releases/tag/v12.10.0) - releases and can be closed.

**Comment by tsenart** [comment]
@Elnadrion: There are arm64 releases in https://github.com/tsenart/vegeta/releases/tag/v12.11.1.

<img width="1190" alt="image" src="https://github.com/tsenart/vegeta/assets/67471/07e0b3d9-6bb0-48d2-8e20-187195c7d9e4">

**Comment by Elnadrion** [comment]
Oh no, I didn't clicked on this button
Sorry, I'm so ashamed 😅
![image](https://github.com/tsenart/vegeta/assets/33313896/83894db7-1d24-4b8c-966e-0dd0bf806741)
