### ISSUE TITLE
vegeta -version not emitting values as expected in v12.8.4

### ISSUE THREAD

**Issue by surenderssm** [tsenart/vegeta#547]
#### Version and Runtime
v12.8.4
```
Version:
Commit:
Runtime: go1.14.2 linux/amd64
Date:
```

#### Expected Behaviour

Version , commit and date to be populated as per v12.8.4 on running vegeta -version

#### Actual Behaviour

Empty values in version, commit and date
#### Steps to Reproduce

1. Install latest version (v12.8.4)
```
sudo wget https://github.com/tsenart/vegeta/releases/download/v12.8.4/vegeta_12.8.4_linux_amd64.tar.gz \
&& tar xfz vegeta_12.8.4_linux_amd64.tar.gz \
&& rm -f vegeta_12.8.4_linux_amd64.tar.gz \
&& sudo mv vegeta /usr/bin/vegeta
```

2. Run the command to get version

```vegeta -version```

Looks like this broke in latest release, it works as expected in v12.8.3 and earlier bits

**Comment by tsenart** [comment]
Fixed in latest releases. Thanks for reporting!
