### ISSUE TITLE
MaxBody(0) seems to be causing server to leak connections

### ISSUE THREAD

**Issue by antoineco** [tsenart/vegeta#549]
#### Question

I am flagging this as a question and not a bug because I haven't gathered sufficient proof yet, but I have a strong suspicion that `maxBody=0` causes the target to leak connections.

I performed the same test multiple times against the exact same server and observed similar results: a ramp to 8000 req/s with a payload of 2 KB and a client timeout of 3s.

The charts below show the receive throughput measured from the target (not from vegeta), in one case with `maxBody=-1`, in the other case with `maxBody=0`. The "rt" series is the receive throughput, the "q" series is just an internal queue which has no influence on the results of the attack.

---

 `maxBody=-1`

![image](https://user-images.githubusercontent.com/3299086/98609716-39aafc80-22ee-11eb-8239-249f8d24844a.png)

```
Running attack Ramp{5 intervals, 1600 hits/1s increments} for 20s
Attack completed
---- Results ----
duration     : 20.002541209s
bytes out    : {196608000 2048}
bytes in     : {0 0}
requests     : 96000
wait time    : 8.562478ms
rate         : 4799.390187323073
throughput   : 4797.336593801439
success %    : 100
status codes : map[200:96000]
errors       : []
```

---

 `maxBody=0`

![image](https://user-images.githubusercontent.com/3299086/98612417-69f59980-22f4-11eb-90d3-03e3a5f859a2.png)

```
Running attack Ramp{5 intervals, 1600 hits/1s increments} for 20s
Attack completed
---- Results ----
duration     : 31.093824885s
bytes out    : {189184000 1987.8742027340836}
bytes in     : {0 0}
requests     : 95169
wait time    : 5.578920017s
rate         : 3060.704186505873
throughput   : 2518.9006235244256
success %    : 97.06417005537517
status codes : map[0:2794 200:92375]
errors       : [Post "http://thrpt-receiver.perf-thrpt-receiver": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]
```

---

In the second case, I do observe some failures at about the same threshold every time, and noticed that the wait time was about 5s, which is my server's `IdleConnTimeout` (this could also be a pure coincidence).

This particular server only returns HTTP headers and no body, so I suppose it is normal to see `0 byte in` in both results, regardless of the value of `maxBody`(?)

I checked the code of the lib and confirmed that the response body was being closed correctly in a deferred statement, so I'm a bit puzzled about what may be happening here.

**Comment by tsenart** [comment]
Sorry for not responding to this when you first posted it. I'm spending time maintaining Vegeta again. If you're still interested in looking into this, please re-open.
