### ISSUE TITLE
metrics issues when I use the vegeta as library

### ISSUE THREAD

**Issue by apolloyang2017** [tsenart/vegeta#552]
following is my test code which use the vegeta as library: 

func TestWithVegeta(wg *sync.WaitGroup, s int, c int, down int, url string) {
	defer wg.Done()
	bodys := make(chan string, c*down)
	defer close(bodys)
	for i := 0; i < down; i++ {
		for j := 0; j < c; j++ {
			id := s + j
			clientID := fmt.Sprintf("iSurpass%d", id)
			var jstr string
			if i%2 == 0 {
				jstr = fmt.Sprintf(`{"method": "thing.service.OpenLock", "deviceid": "%s", "nodeid":  2, "params":{"Mode": 0}}`, clientID)
			} else {
				jstr = fmt.Sprintf(`{"method": "thing.service.CloseLock", "deviceid": "%s", "nodeid":  2}`, clientID)
			}
			bodys <- jstr
		}
	}

	targeter := newCustomTargeter(url, bodys)
	attacker := vegeta.NewAttacker()
	var metrics vegeta.Metrics
	defer metrics.Close()
	rate := vegeta.Rate{Freq: c, Per: time.Second}
	duration := time.Duration(down) * time.Second
	for res := range attacker.Attack(targeter, rate, duration, "Openservice HTTP Load Test") {
		metrics.Add(res)
	}
	fmt.Printf("%+v\n", metrics)
}

func newCustomTargeter(url string, bodys <-chan string) vegeta.Targeter {
	return func(t *vegeta.Target) error {
		if t == nil {
			return vegeta.ErrNilTarget
		}
		payload := <-bodys
		fmt.Printf("will send: %s\n", payload)
		t.Method = "POST"
		t.URL = url
		header := make(http.Header)
		header.Add("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBrZXkiOiJpU3VycGFzc0FwcCIsInRpbWVzdGFtcCI6IjEyMzQ1Njc4OTAifQ.KRLkB8N-3w-_tkUfUbHbZCBtZrHuOwKbmQeNK1w08_0")
		header.Add("Content-Type", "application/json")
		t.Header = header
		t.Body = []byte(payload)
		return nil
	}
}

the following is the metrics result:
{Latencies:{Total:1h20m26.935493975s Mean:0s P50:0s P90:0s P95:0s P99:0s Max:1.595828772s Min:2.357833ms estimator:0xc00088f338} Histogram:<nil> BytesIn:{Total:724620 Mean:0} BytesOut:{Total:747000 Mean:0} Earliest:2020-12-11 14:46:53.521444143 +0800 CST m=+30.920274284 Latest:2020-12-11 14:47:23.518052918 +0800 CST m=+60.916883059 End:2020-12-11 14:47:23.9633219 +0800 CST m=+61.362152041 Duration:0s Wait:0s Requests:9000 Rate:0 Throughput:0 Success:0 StatusCodes:map[200:9000] Errors:[] errors:map[] success:9000}8} Histogram:<nil> BytesIn:{Total:724620 Mean:0} BytesOut:{Total:747000 Mean:0} Earliest:2020-12-11 14:46:53.521444143 +0800 CST m=+30.920274284 Latest:2020-12-11 14:47:23.518052918 +0800 CST m=+60.916883059 End:2020-12-11 14:47:23.9633219 +0800 CST m=+61.362152041 Duration:0s Wait:0s Requests:9000 Rate:0 Throughput:0 Success:0 StatusCodes:map[200:9000] Errors:[] errors:map[] success:9000}

**Comment by apolloyang2017** [comment]
why total is 1h20m26.935493975s? P50:0s P90:0s P95:0s P99:0s ? and Rate:0 Throughput:0 Success:0?

**Comment by tsenart** [comment]
You need to call `metrics.Close()` before `fmt.Printf("%+v\n", metrics)`.

**Comment by apolloyang2017** [comment]
@tsenart , I get it , thank you!
