### ISSUE TITLE
Load test GET and POST API concurrently with given`read/write` ratio as x/y at any given moment.

### ISSUE THREAD

**Issue by achawla-Branch** [tsenart/vegeta#565]
#### Question
Is possible to load test GET and POST API concurrently where we have a use case of `read/write` ratio as x/y at any given moment?

**Challenge I am facing is how do I load test GET API as well simultaneously?**  

I have written script using vegeta-library for POST API that creates and store resource with unique identifier for each attack. GET API will return stored data using identifier created as part of load test.

**Comment by tsenart** [comment]
It's not easy to do this with Vegeta yet. Check this issue: #570
