### ISSUE TITLE
vegeta report on Windows - encode: can't detect encoding of "results.bin"

### ISSUE THREAD

**Issue by brunolm** [tsenart/vegeta#569]
#### Version and Runtime

Installed with `$ go get -u github.com/tsenart/vegeta` on `2021-05-14` master branch on commit `d73edf2bc2663d83848da2a97a8401a7ed1440bc`

vegeta --version output:
```
Version:
Commit:
Runtime: go1.16.4 windows/amd64
Date:
```

#### Expected Behaviour

Report to work

#### Actual Behaviour

```
encode: can't detect encoding of "stdin"
```

or this if running just `vegeta report results.bin`

```
encode: can't detect encoding of "results.bin"
```

#### Steps to Reproduce

1. `echo "GET http://localhost:8080/" | vegeta attack -duration=2s -rate=1/s | tee results.bin | vegeta report`

#### Additional Context

The issue is when `vegeta report` runs.

OS info:

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
```

Linux (left) | Windows (right)
![image](https://user-images.githubusercontent.com/706078/118296495-6b766900-b4b3-11eb-96f9-239672f49fb8.png)

Same command on WSL works.

### Workaround

Instead of following the examples in README.md if you use `--output` it'll output the file with the correct encoding.

```
echo "GET http://localhost:8080/" | vegeta attack -duration=2s -rate=1/s --output results.bin;
vegeta report results.bin
```

**Comment by tsenart** [comment]
What shell are you using? I don't think piping works in exe. Have you tried it on PowerShell?

**Comment by tsenart** [comment]
Also try the latest version. Please re-open if it's still happening.
