### ISSUE TITLE
How to send dependent requests

### ISSUE THREAD

**Issue by maxtar** [tsenart/vegeta#570]
Hi.

I couldn't understand how I can use response from one request in another one?
For example the following scenario:
1. Do request for authorization.
2. Get token from answer.
3. Use this token in the next request.

I couldn't use dynamic targeter in attacker.
How I can implement such a scenario?

**Comment by rgarrigue** [comment]
Hi

I'm looking for the same answer, any luck implenting it ?

**Comment by flupec** [comment]
@maxtar  I'm afraid that there's only one solution -- use vegeta as library and embed it's logic in your own go code

**Comment by maxtar** [comment]
> 

The question has occurred to me exactly because I started to write code. :)

**Comment by flupec** [comment]
@maxtar I guess vegeta not designed for such case. You can try to init three different attackers for  each step from scenario above. First attacker will make authorization and return chan of result. This chan of result will be an input for second attacker and so on. In that case you will need different implementation for Targeter function. Try to research by yourself :)  But there's no guarantee of performance, it will depend on your implementation of this
