### ISSUE TITLE
write: no buffer space available

### ISSUE THREAD

**Issue by Seo-yul** [tsenart/vegeta#574]
#### Question
I am using vegeta to load test my response server.
I put huge data into the vegeta's Target body (for example, a string of size 10 mib).
As a result [a write: no buffer space available] error appears.

I think, if I set vegeta's writeBuffer, I can fix the problem.

Is it possible to solve it this way? Or is there any other way?

```
targeter := vegeta.NewStaticTargeter(vegeta.Target{
                 Method: "POST",
		URL:    url,
		Body:   'there is huge data',
	})
```

**Comment by tsenart** [comment]
Sorry, this isn't enough context for me to help.
