### ISSUE TITLE
Support for Apple M1 chip

### ISSUE THREAD

**Issue by kishaningithub** [tsenart/vegeta#578]
#### Proposal

Given go 1.16 supports building for apple's new M1 chip (ARM architecture) can we produce native binary for the same and wire it up in the brew formula?

#### Background

Having native support for apple M1 chip would be really nice

#### Workarounds

Use x86 binary for apple m1 macs

**Comment by kishaningithub** [comment]
My bad - 

https://github.com/Homebrew/homebrew-core/blob/0ee76eac77377070b7d00a90713ace3dcd2917b1/Formula/vegeta.rb#L9

M1 Chip binary is already in brew formula

**Comment by kishaningithub** [comment]
Can the binary also be present in github releases?

https://github.com/tsenart/vegeta/releases

**Comment by tsenart** [comment]
Done!
