### ISSUE TITLE
Vegeta is not able to hit total request which mention through rate

### ISSUE THREAD

**Issue by Khushbukela** [tsenart/vegeta#593]
so here I have set 
```
 rate := vegeta.Rate{Freq: 2000, Per: time.Second} // change the rate here
 duration := 4 * time.Minute
```
as per my understanding, total request should be 480000 
2000*1*4*60=480000

but why here total is 840000

rate:  2000  per:  1s  duration:  4m0s
Requests      [total, rate, throughput]  840000, 1166.66, 1166.65
Duration      [total, attack, wait]      12m0.00774586s, 12m0.005126434s, 2.619426ms
Status Codes  [code:count]               200:840000  
Error Set:

**Comment by tsenart** [comment]
This isn't enough information for me to help you. Please re-open with a Bug Report.
