### ISSUE TITLE
go 1.18 compatibility: import latest `github.com/streadway/quantile` commit

### ISSUE THREAD

**Issue by WolfWFr** [tsenart/vegeta#595]
#### Proposal

I would like to ask to update this repository by importing the latest commit of the `github.com/streadway/quantile` dependency.

Currently, trying to import the `tsenart/vegeta` repository into a go v1.18 project, I get the following error on running `go mod tidy`:

```
bitbucket.org/innius/api/test/throttling tested by
	bitbucket.org/innius/api/test/throttling.test imports
	github.com/tsenart/vegeta/v12/lib tested by
	github.com/tsenart/vegeta/v12/lib.test imports
	github.com/streadway/quantile tested by
	github.com/streadway/quantile.test imports
	.: "." is relative, but relative import paths are not supported in module mode
```

This relative import statement in `github.com/streadway/quantile` appears to have been removed in their latest commit.

#### Background

Using go v1.18 and importing this repo yields errors from go mod commands and is preventing successful builds.

#### Workarounds

revert to older version of go.

**Comment by abdukhashimov** [comment]
Is there any updates on this issue?
