### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by InCogNiTo124** [tsenart/vegeta#605]
#### Is this project unmaintained?

**Comment by tsenart** [comment]
What do you need?

**Comment by InCogNiTo124** [comment]
Just wondering, there was no new commits for 2.5 years so I thought this wasn't maintained anymore

**Comment by munepom** [comment]
I thought it was unfortunate that Taurus stopped supporting Vegeta 😢 
https://github.com/Blazemeter/taurus/pull/1689

**Comment by tsenart** [comment]
It's in low-maintenance mode. I don't plan on adding any new features anytime soon, or spend significant effort in reviewing and integrating patches, but if there's a critical vulnerability I'll look into it.

**Comment by munepom** [comment]
I'm relieved to hear that maintenance is continuing. Thank you :)
