### ISSUE TITLE
using max-workers flag impacts peak TPS generated as compared to without the flag

### ISSUE THREAD

**Issue by gokulb** [tsenart/vegeta#620]
In general, my understanding was as long as we set the rate at a certain TPS, we should see our avg and p90 TPS to be close enough to the rate and we may see the peak TPS spike a bit at Vegeta. However, in my load tests, I see despite rate set at 50, the peak TPS goes upto 134 which completely screws up my test results as our system is not designed to support that rate. How can I control the rate to not hit that high a peak TPS without touching the workers flag?

**Comment by tsenart** [comment]
Please open this as a Bug Report with all the needed info. Can't help without additional info.
