### ISSUE TITLE
I am getting a lot of HTTP zero in the results, how can I troubleshoot it?

### ISSUE THREAD

**Issue by fombico** [tsenart/vegeta#668]
I am running vegeta v12.8.4 on a kubernetes pod, sending 5000 RPS for 60s with an JWT authorization header. The pod had 4 CPU and 8 GB of memory. I am seeing a success rate of 34%, where all the status codes are either 0 or 200.

I understand from the readme that HTTP 0 means a request failed to be sent. Does this mean:
- vegeta cannot send 5000 RPS?
- vegeta needs more CPU/memory?
- things are failing on at a TCP level?

I am trying to eliminate the variables and wondering if this 5000 RPS is too much load to send from Vegeta.

Thanks

**Comment by ryan-hixcare** [comment]
any updates?

**Comment by tsenart** [comment]
You need to share what the specific errors are. What does vegeta report show?

**Comment by fombico** [comment]
It's been about a year, so my knowledge is now fuzzy. 

I was getting several errors like:

```
Get "http://the-url": read tcp 10.96.177.28:39771->10.96.190.196:80: read: connection reset by peer
Get "http://the-url": read tcp 10.96.177.28:33969->10.96.190.196:80: read: connection reset by peer
Get "http://the-url": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
context deadline exceeded (Client.Timeout or context cancellation while reading body)
Get "http://the-url": read tcp 10.96.177.28:50861->10.96.190.196:80: read: connection reset by peer (Client.Timeout exceeded while awaiting headers)
Get "http://the-url": read tcp 10.96.177.28:59319->10.96.190.196:80: read: connection reset by peer (Client.Timeout exceeded while awaiting headers)
Get "http://the-url": read tcp 10.96.177.28:49545->10.96.190.196:80: read: connection reset by peer (Client.Timeout exceeded while awaiting headers)
```

As far as I could tell, the target application was too overloaded. The current requests were taking too long to run, and there are no free connections in the thread pool. The errors from the log are probably timeouts from waiting for a connection.

I obtained a tcpdump and I believe I did see requests going out of vegeta.

I was testing a Java app on k8s. Increasing the MaxDirectMemorySize from 10MB to 512MB helped.

Anyway, I think I determined vegeta was working properly, so I'm closing the issue.

**Comment by ryan-hixcare** [comment]
@fombico good informative solve!!
