### ISSUE TITLE
Feature:Randomize source addresses

### ISSUE THREAD

**Issue by ehmueller** [tsenart/vegeta#68]
Could you please add a feature to allow a CIDR to be specified as the source network to generate traffic. The IP addresses that are part of the CIDR provided would then be added to the interface using the ifconfig command. 

An alternate method would to allow the user to specify the list of IP addresses in a file and then have the user also configure their interface with this list of IP addresses (or have the program generate traffic based on all of the IP's configured on a given interface).

I have a use-case where the security devices I test use a src/dst hashing algorithm and will load share the traffic based on these flows. I could do this based on destination address however this would not simulate a real life scenario such as hundreds of users accessing a single web server.

**Comment by haoyehaoye** [comment]
@tsenart 
thanks for your suggestion!
I tried to  specify source ip by using -laddr, but the following error happened.
`Requests      [total, rate]            18, 6.35
Duration      [total, attack, wait]    2.833074015s, 2.833074015s, 0s
Latencies     [mean, 50, 95, 99, max]  0s, 0s, 0s, 0s, 0s
Bytes In      [total, mean]            0, 0.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  0.00%
Status Codes  [code:count]             0:18
Error Set:
Get https://abc.com: dial tcp 10.0.0.100:0->182.22.108.203:443: bind: cannot assign requested address`

Do you have any idea about it?

**Comment by tsenart** [comment]
> btw, I do not assign 10.0.0.100 to any interface of the server. Is the -laddr must be specified by a assigned ip? not work with fake ip?

You need to use IPs that are bound to a network interface. Luckily, creating such IPs is doable. Example: https://www.ostechnix.com/how-to-assign-multiple-ip-addresses-to-single-network-card-in-linux/

**Comment by haoyehaoye** [comment]
understood, thanks!
