### ISSUE TITLE
Can the latest version be published on Go packages?

### ISSUE THREAD

**Issue by crisog** [tsenart/vegeta#681]
#### Question

It hasn't been updated there since 2019 - I know we can build from source but it would be handy that the current latest gets published again!
https://pkg.go.dev/github.com/tsenart/vegeta

Thank you in advance 🙏🏽

**Comment by shuLhan** [comment]
@crisog I believe you need to append "/v12" to view the latest module version, see https://pkg.go.dev/github.com/tsenart/vegeta/v12 .
