### ISSUE TITLE
Use `go generate` for packaging dygraphs

### ISSUE THREAD

**Issue by tsenart** [tsenart/vegeta#83]
Currently the `dygraphs` plotting library is being packaged in the binaries with https://github.com/jteeuwen/go-bindata.

[With the advent](https://docs.google.com/document/d/1V03LUfjSADDooDMhe-_K59EgpTEm3V8uvQRuNMAEnjg/edit) of the `go generate` in Go 1.4, this process can likely be improved with automation.

**Comment by mickey** [comment]
@tsenart What about just using [cdnjs](https://cdnjs.com/) in the html template?

**Comment by tsenart** [comment]
@mickey: That requires the user to be connected to the Internet which is not possible under certain environments.

**Comment by tsenart** [comment]
Fixed with #317.
