### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by tsenart** [tsenart/vegeta#86]
Create packages for:
- Homebrew
- Nixpkgs

**Comment by mickey** [comment]
@tsenart For your information, a vegeta formula was just merged into homebrew: https://github.com/Homebrew/homebrew/pull/36685

**Comment by tsenart** [comment]
@mickey: This is fantastic! Thank you so much. I'm leaving some comments on the above mentioned PR.

**Comment by tsenart** [comment]
Could you please also update the README to let users know they can install Vegeta with Homebrew?

**Comment by mickey** [comment]
Sure I'll do it, this weekend.

> What is this testing exactly? Wouldn't it be enough to run vegeta -h?

I originally did that but the thing is `vegeta -h` doesn't return a success code:

```shell
❯ vegeta -h
Usage: vegeta [globals] <command> [options]
....
❯ echo $?
2
```

**Comment by mikemcquaid** [comment]
> I originally did that but the thing is vegeta -h doesn't return a success code:

Also, we prefer to have tests that actually exercise the tool beyond printing a string.
